== 空調機サブシステムテストに関する作業メモ

=== 2022.01.14

==== 空調機サブシステムのモデリング
VAV全体システムモデル（JSBC2018_updated_VAVsystem.idf）から以下の点を変更する。	

===== 不要なゾーン、空調機器の削除
空調機サブシステムの対象ゾーン（NP、NEP、NWP）以外のゾーンをすべて削除した。削除対象オブジェクトは、Zone, BuildingSurface:Detailed, SurfaceProperty:ConvectionCoefficients, People, Lighting, OtherEquipment, Infiltration。また、これに併せて不要な空調機、VAVも削除した。最終的に残るのは3つの対象ゾーンのVAVとAHU1台のみである。

===== 対象ゾーンの設定

====== Surface
表面は天井、床、外壁のみを残し、内壁は削除した。天井、床、外壁についてはすべて同様に1mの断熱材とし、外表面の日射・風への曝露は無し、さらに断熱境界とした。

```
  Material,
    JP- XPS Extruded Polystyrene_1m,  !- Name
    Rough,                   !- Roughness
    1.00,                    !- Thickness {m}
    .04,                     !- Conductivity {W/m-K}
    25,                      !- Density {kg/m3}
    100,                     !- Specific Heat {J/kg-K}
    .9,                      !- Thermal Absorptance
    .8,                      !- Solar Absorptance
    .8;                      !- Visible Absorptance
  
  Construction,
    W1m - IBEC,               !- Name
    JP- XPS Extruded Polystyrene_1m;  !- Layer 4

  BuildingSurface:Detailed,
    2X6F:04X1XOfficeNP_ExtFloor_0_0_0,  !- Name
    Floor,                   !- Surface Type
    W1m - IBEC,              !- Construction Name
    2X6F:04X1XOfficeNP,      !- Zone Name
    Adiabatic,               !- Outside Boundary Condition
    ,                        !- Outside Boundary Condition Object
    NoSun,                   !- Sun Exposure
    NoWind,                  !- Wind Exposure
    AutoCalculate,           !- View Factor to Ground
    4,                       !- Number of Vertices
    8.05070303,17.98340717,23.2,  !- X,Y,Z ==> Vertex 1 {m}
    -24.44929697,17.98340717,23.2,  !- X,Y,Z ==> Vertex 2 {m}
    -29.44929697,22.98340717,23.2,  !- X,Y,Z ==> Vertex 3 {m}
    13.05070303,22.98340717,23.2;  !- X,Y,Z ==> Vertex 4 {m}
```

====== 内部発熱
顕熱内部発熱としてOtherEquipmentにて指定の熱量を一定値で与える。

```
  OtherEquipment,
    2X6F:04X1XOfficeNP Equipment gain 1,  !- Name
    Electricity,             !- Fuel Type
    2X6F:04X1XOfficeNP,      !- Zone or ZoneList Name
    JP Office - office equipments NP,  !- Schedule Name
    EquipmentLevel,          !- Design Level Calculation Method
    13800,                   !- Design Level {W}
    ,                        !- Power per Zone Floor Area {W/m2}
    ,                        !- Power per Person {W/person}
    0,                       !- Fraction Latent
    0,                       !- Fraction Radiant
    0,                       !- Fraction Lost
    0,                       !- Carbon Dioxide Generation Rate {m3/s-W}
    ELECTRIC EQUIPMENT#2X6F:04X1XOfficeNP#05;  !- End-Use Subcategory
```

===== 空調機ファン
Fan total efficiencyはモータ効率とファン効率の積のようで、これと定格風量、静圧から定格消費電力が計算されるようである。Fan total efficiencyは性能曲線からファン効率の最大値（0.62）、モータ効率（0.90）、インバータ効率（0.97）を掛け合わせた数字とした。

Fan power coefficientはファン電力消費率を風量比の4次式で近似する際の係数である。給気ファン、還気ファンともに指定の抵抗曲線と合致するように与えた。2つ目のファンの名前がExtract fanとなっているが、これが還気ファンである。

```
  Fan:VariableVolume,
    AHU1-1 AHU Supply Fan,   !- Name
    On 24/7,                 !- Availability Schedule Name
    0.541,                   !- Fan Total Efficiency
    838.00,                  !- Pressure Rise {Pa}
    2.076700,                !- Maximum Flow Rate {m3/s}
    Fraction,                !- Fan Power Minimum Flow Rate Input Method
    0.400,                   !- Fan Power Minimum Flow Fraction
    0.000000,                !- Fan Power Minimum Air Flow Rate {m3/s}
    0.900000,                !- Motor Efficiency
    1.00,                    !- Motor In Airstream Fraction
    0.0597,                  !- Fan Power Coefficient 1
    0,                       !- Fan Power Coefficient 2
    0,                       !- Fan Power Coefficient 3
    0.9403,                  !- Fan Power Coefficient 4
    0.0000000000,            !- Fan Power Coefficient 5
    AHU1-1 AHU Cooling Coil Air Outlet Node,  !- Air Inlet Node Name
    AHU1-1 Supply Side Outlet 1,  !- Air Outlet Node Name
    General;                 !- End-Use Subcategory

  Fan:VariableVolume,
    AHU1-1 AHU Extract Fan,  !- Name
    On 24/7,                 !- Availability Schedule Name
    0.541,                   !- Fan Total Efficiency
    348.00,                  !- Pressure Rise {Pa}
    2.076700,                !- Maximum Flow Rate {m3/s}
    Fraction,                !- Fan Power Minimum Flow Rate Input Method
    0.400,                   !- Fan Power Minimum Flow Fraction
    0.000000,                !- Fan Power Minimum Air Flow Rate {m3/s}
    0.900000,                !- Motor Efficiency
    1.00,                    !- Motor In Airstream Fraction
    0,                       !- Fan Power Coefficient 1
    0,                       !- Fan Power Coefficient 2
    0,                       !- Fan Power Coefficient 3
    1,                       !- Fan Power Coefficient 4
    0.0000000000,            !- Fan Power Coefficient 5
    AHU1-1 Supply Side Inlet,!- Air Inlet Node Name
    AHU1-1 AHU Extract Fan Air Outlet Node,  !- Air Outlet Node Name
    General;                 !- End-Use Subcategory
```

===== 給気温度リセット制御
EnergyPlusでは以下の4つの制御を選択できる（link:https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-setpoint-managers.html#setpointmanagerwarmest[Link]）。

.給気温度制御の種類
|======================================
| SetpointManager:Scheduled | スケジュールで設定値を与える。最もシンプルな設定。
| SetpointManager:Warmest | 冷房用のリセット制御。最大風量ベースでリセットするため風量は大きくなる。
| SetpointManager:Coldest | 暖房用のリセット制御。Warmestと同様、風量は大きくなる。
| SetpointManager:WarmestTemperatureFlow | 冷房用のリセット制御。温度優先と風量優先を選択可能。
|======================================

給気温度リセット制御を行わないCase 100, 110, 120はSetpointManager:Scheduledを使用し、給気温度リセット制御を行う残りの2ケースについてはSetpointManager:WarmestとSetpointManager:WarmestTemperatureFlowの両方を試した。

```
  SetpointManager:Scheduled,
    AHU1-1 Setpoint Manager Cooling,  !- Name
    Temperature,             !- Control Variable
    Air loop cooling set point temperature: Always 16.0 C, !- Schedule Name
    AHU1-1 Setpoint Manager Cooling Node List;  !- Setpoint Node or NodeList Name
```

```
  SetpointManager:Warmest,
    AHU1-1 Setpoint Manager Cooling,   !- Name
    Temperature,   !- Control Variable
    AHU1-1,   !- HVAC Air Loop Name
    16,   !- Minimum Setpoint Temperature
    22,   !- Maximum Setpoint Temperature
    MaximumTemperature,   !- Strategy
    AHU1-1 Setpoint Manager Cooling Node List;   !- Setpoint Node or NodeList Name
```

```
  SetpointManager:WarmestTemperatureFlow,
    AHU1-1 Setpoint Manager Cooling, !- Name
    Temperature, !- Control Variable
    AHU1-1, !- HVAC Air Loop Name
    16, !- Minimum Setpoint Temperature
    22, !- Maximum Setpoint Temperature
    TemperatureFirst, !- Strategy
    AHU1-1 Setpoint Manager Cooling Node List, !- Setpoint Node or NodeList Name
    0.4; !- Minimum Turndown Ratio
```

===== 熱源システム
AHP1台のみを残し、もう1つのAHPとARは削除した。AHPの容量は空調機と合わせた。

==== 計算結果
「AHS_results_EnergyPlus.xlsx」を参照。

* Case 100, 110, 120については他のツールとほぼ同様の結果となった。
* "Warmest"を用いる場合、Case 200（負荷均一）では給気温度が上限値となり、他のツールよりも風量が大きくなる。Case 300（負荷偏在）では、他のツールと近い結果になった。
* "WarmestTemperatureFlow"を用いる場合、Case 200（負荷均一）では他のツールと近い結果になった。Case 300（負荷偏在）では、なぜか負荷率の低いゾーンNPでは室温設定を満たせず過剰冷房となった。link:https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SetPointManager.cc[ソースコード]（6692行目）を見ると、最も大きいVAV風量比を空調機の最小風量比として設定しているようも見える？そうすると風量過剰になり、風量分配と給気温度の再計算が行われ、おかしな状態になってしまっているのかもしれない。参考までに、この時の空調機風量比はゾーンNWPとNEPの負荷を下限給気温度16℃で満たすVAV風量比とほぼ一致している。
* エネルギーの観点で見ると、冷水コイル処理熱量はどちらの場合でも他のツールとほぼ同等の値となっている。一方、ファン電力については両制御でCase 200, 300で逆の傾向になっている。

==== 今後の課題
* EnergyPlusの給気温度リセット制御についてもう少し詳細な勉強、調査が必要。"WarmestTemperatureFlow"は負荷偏在時に室温設定値を満たせないとすると致命的な欠陥があると言える。また、暖房時は"WarmestTemperatureFlow"と対になる制御がない。
* 以上で3つのサブシステムテストを概ね完了した。ただし、これらは現在ガイドライン制定委員会で行っている更新作業の前の旧バージョンであるため、新ガイドラインに掲載するためには更新後のサブシステムテストを実施する必要がある。また、サブシステムテストとしてはもう1つ蓄熱サブシステムテストがある。

=== 2022.02.16

ガイドライン制定委員会で改定を行っている2022年版ガイドラインの空調機サブシステムテストを対象に再度トライアルを行った。2022年版ではVAV冷房運転だけでなく、CAV冷房運転およびVAV暖房運転も計算対象となる点で前ガイドラインの空調機サブシステムテストとは大きく異なっている。熱源はすべてのケースでDistrict Cooling/Heatingオブジェクトを使用した。

==== CAV冷房運転用モデル（JSBC2018_updated_AHUsubsystem_2022_CAV.idf）
主な変更点は以下の2点である。

* VAVオブジェクト（AirTerminal:SingleDuct:VAV:HeatAndCool:NoReheat）をCAVオブジェクト（AirTerminal:SingleDuct:ConstantVolume:NoReheat）に変更

* 給気温度のSetpotintManagerをSetpointManager:MultiZone:Cooling:Averageに変更

* 冷水コイルのスペックを高負荷条件に対応できるよう修正

```
  AirTerminal:SingleDuct:ConstantVolume:NoReheat,
    2X6F:04X1XOfficeNP Single Duct VAV No Reheat,  !- Name
    HVAC schedule,                 !- Availability Schedule Name
    AHU1-1 Zone Splitter Outlet Node 1,  !- Air Inlet Node Name
    2X6F:04X1XOfficeNP Single Duct VAV No Reheat Supply Outlet,  !- Air Outlet Node Name
    1.153100,                !- Maximum Air Flow Rate {m3/s}
    ;                        !- Per Person Ventilation Rate Mode

  SetpointManager:MultiZone:Cooling:Average,
    AHU1-1 Setpoint Manager Cooling,  !- Name
    AHU1-1,                  !- HVAC Air Loop Name
    16.00,                   !- Minimum Setpoint Temperature {C}
    32.00,                   !- Maximum Setpoint Temperature {C}
    AHU1-1 Setpoint Manager Cooling Node List;  !- Setpoint Node or NodeList Name
  
  Coil:Cooling:Water,
    AHU1-1 AHU Cooling Coil, !- Name
    On 24/7,                 !- Availability Schedule Name
    0.002117,                !- Design Water Flow Rate {m3/s}
    2.076700,                !- Design Air Flow Rate {m3/s}
    7.00,                    !- Design Inlet Water Temperature {C}
    29.50,                   !- Design Inlet Air Temperature {C}
    15.10,                   !- Design Outlet Air Temperature {C}
    0.013100,                !- Design Inlet Air Humidity Ratio {kgWater/kgDryAir}
    0.010200,                !- Design Outlet Air Humidity Ratio {kgWater/kgDryAir}
    AHU1-1 AHU Cooling Coil Water Inlet Node,  !- Water Inlet Node Name
    AHU1-1 AHU Cooling Coil Water Outlet Node,  !- Water Outlet Node Name
    AHU1-1 AHU Mixed Air Outlet,  !- Air Inlet Node Name
    AHU1-1 AHU Cooling Coil Air Outlet Node,  !- Air Outlet Node Name
    SimpleAnalysis,          !- Type of Analysis
    CrossFlow,               !- Heat Exchanger Configuration
    ;                        !- Condensate Collection Water Storage Tank Name
```

link:https://bigladdersoftware.com/epx/docs/9-4/engineering-reference/setpoint-managers.html#multizone-cooling-average[SetpointManager:MultiZone:Cooling:Average]は全ゾーンの合計負荷を合計風量で除すことで給気温度を求める。

外気導入を行うS-VAV120-cではコイル入口条件が設計条件よりも高温・高湿であるため過負荷条件となる。EnergyPlusは設計流量以上の流量をコイルに流すことができないようであるため、能力不足で室温設定を満たせない状態となった。そこで、冷水コイルのスペックを入口空気温度27.5→29.5℃、入口絶対湿度12.1→13.1g/kgに修正した。このような措置を良しとするか、あるいはテスト条件の方を見直すかについて委員会・WGで議論する必要がある。

==== VAV冷房運転用モデル（JSBC2018_updated_AHUsubsystem_2022_VAVcooling.idf）
大きな変更は行っていない。給気温度リセット制御についてはエネルギーの観点で他のツール近い結果となるSetpointManager:WarmestTemperatureFlowを選択した。

==== VAV暖房運転用モデル（JSBC2018_updated_AHUsubsystem_2022_VAVheating.idf）
主な変更点は以下の2点である。

* 冷水コイルを温水コイルに変更

* 気化式加湿器を模擬するために気化式冷却器（link:https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-evaporative-coolers.html#evaporativecoolerdirectresearchspecial[EvaporativeCooler:Direct:ResearchSpecial]）を追加

```
  Coil:Heating:Water,
    AHU1-1 AHU Cooling Coil, !- Name
    Only winter,                 !- Availability Schedule Name
    2419.69,                !- U-Factor Times Area Value {W/K}
    0.00175,                !- Maximum Water Flow Rate {m3/s}
    AHU1-1 AHU Cooling Coil Water Inlet Node,  !- Water Inlet Node Name
    AHU1-1 AHU Cooling Coil Water Outlet Node,  !- Water Outlet Node Name
    AHU1-1 AHU Mixed Air Outlet,  !- Air Inlet Node Name
    AHU1-1 AHU Cooling Coil Air Outlet Node,  !- Air Outlet Node Name
    NominalCapacity,         !- Performance Input Method
    46700.00,                !- Rated Capacity {W}
    50,                      !- Rated Inlet Water Temperature {C}
    17.5,                    !- Rated Inlet Air Temperature {C}
    45,                      !- Rated Outlet Water Temperature {C}
    36.1,                    !- Rated Outlet Air Temperature {C}
    0.50;                    !- Rated Ratio for Air and Water Convection

  EvaporativeCooler:Direct:ResearchSpecial,
    AHU1-1 AHU Evap Cooler, !- Name
    Evap Cooler Availability Schedule,          !- Availability Schedule Name
    0.15,                !- Cooler Design Effectiveness
    ,                   !- Effectiveness Flow Ratio Modifier Curve Name
    2.076700,           !- Primary Air Design Flow Rate {m3/s}
    30.0,               !- Recirculating Water Pump Design Power
    ,                   !- Water Pump Power Sizing Factor
    ,                   !- Water Pump Power Modifier Curve Name
    AHU1-1 AHU Cooling Coil Air Outlet Node, !- Air Inlet Node Name
    AHU1-1 AHU Evap Cooler Outlet Node, !- Air Outlet Node Name
    AHU1-1 AHU Evap Cooler Outlet Node, !- Sensor Node Name
    ,                   !- Water Supply Storage Tank Name
    0.0,                !- Drift Loss Fraction
    3,                  !- Blowdown Concentration Ratio
    22.0,               !- Evaporative Operation Minimum Drybulb Temperature
    18.0,               !- Evaporative Operation Maximum Limit Wetbulb Temperature
    ;                   !- Evaporative Operation Maximum Limit Drybulb Temperature
```

なぜか温水コイルは冷水コイルと若干入力条件が異なり、直接UA値 [W/k]を入力するようになっている。

EvaporativeCooler:Direct:ResearchSpecialのCooler design effectiveness（飽和効率に相当すると思われる）はS-VAV120-hにおいて室内湿度が指定条件（22℃、40％RH）に近づくように調整した。

なお、VAV暖房のテストシリーズでは給気温度リセット制御OFFの条件しかないため、暖房時の給気温度リセット制御については検証できていない。

==== 計算結果
「20220209空調機サブシステムテスト_計算結果入力ファイル.xlsx」を参照。

* CAVで負荷が不均一な場合、EnergyPlusでは低負荷の1ゾーンは22.4℃、高負荷の2ゾーンは25.8℃となり、全ゾーンで設定温度26℃を下回った。給気温度を求める際に用いる負荷がおそらく推定値であり、収束計算プロセスが入っていないためと思われる。ただし、コイル処理熱量に大きな差はない。
* VAV冷房運転については前回と大きな違いはなく、概ね他のツールと近い結果となっている。コイルスペックの変更により冷水流量が他のツールよりも小さい可能性がある。
* VAV暖房運転では、外気導入あり＆外気導入量50％のケース（S-VAV121-h）において加湿過多となり、全体的に湿度レベルが上昇している。link:https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-evaporative-coolers.html#evaporativecoolerdirectresearchspecial[マニュアル]によると気化式冷却器オブジェクトでも何らかの制御はできるようなので、もう少し調べる必要があるかもしれない。

==== 今後の課題
* 気化式冷却器オブジェクトの制御に関する勉強
* 2022年版熱源・冷却水サブシステムテストの実施

