// Case 600

基本となる建物モデルを作成します。

==== Building

Buildingクラスは、シミュレーション実行時に使用されるパラメータを記述します。 +
Buildingクラスの作成方法は https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-simulation-parameters.html#building[<bigladder>, role="external", window="_blank"] をご覧下さい。 +
このクラスの入力内容と、Site:WeatherStation や Site:HeightVariationのいくつかのエントリ（特にTerrainフィールド）の内容は整合が取れていなければいけません。

.Building
----
  Building,
    Case600,                 !- Name
    0.0,                     !- North Axis {deg}
    Country,                 !- Terrain
    3.9999999E-02,           !- Loads Convergence Tolerance Value {W}
    4.0000002E-03,           !- Temperature Convergence Tolerance Value {deltaC}
    FullInteriorAndExterior, !- Solar Distribution
    ,                        !- Maximum Number of Warmup Days
    6;                       !- Minimum Number of Warmup Days
----


==== Site:Location

Site:Locationクラスは、建物の位置に関するパラメータを記述します。位置は1つしか指定できません。 +
Site:Locationクラスの作成方法は https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-location-climate-weather-file-access.html[<bigladder>, role="external", window="_blank"] をご覧下さい。 +
気象データファイルに位置情報が存在する場合は、IDFに記された位置情報データよりも優先されます。
したがって、年間シミュレーションの場合、Locationを入力する必要はありません。

.Site:Location
----
  Site:Location,
    Denver-Stapleton,CO,USA,TMY--23062,  !- Name
    39.8,                    !- Latitude {deg}
    -104.9,                  !- Longitude {deg}
    -7.0,                    !- Time Zone {hr}
    1609.00;                 !- Elevation {m}
----

【作業メモ】 + 
気象データファイルと緯度・経度の桁が違う・・・。標高も違う。


==== RunPeriod

RunPeriodクラスでは、計算期間の設定を行います。 +
RunPeriodクラスの作成方法は https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-location-climate-weather-file-access.html#runperiod[<bigladder>, role="external", window="_blank"] をご覧下さい。 +

.RunPeriod
----
RunPeriod,
    RUNPERIOD 1,             !- Name
    1,                       !- Begin Month
    1,                       !- Begin Day of Month
    ,                        !- Begin Year
    12,                      !- End Month
    31,                      !- End Day of Month
    ,                        !- End Year
    ,                        !- Day of Week for Start Day
    Yes,                     !- Use Weather File Holidays and Special Days
    Yes,                     !- Use Weather File Daylight Saving Period
    No,                      !- Apply Weekend Holiday Rule
    Yes,                     !- Use Weather File Rain Indicators
    Yes,                     !- Use Weather File Snow Indicators
    No;                      !- Treat Weather as Actual
----


==== Site:GroundReflectance

Site:GroundReflectanceクラスは、地物反射率に関するパラメータを記述します。 +
Site:GroundReflectanceクラスの作成方法は https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-location-climate-weather-file-access.html#sitegroundreflectance[<bigladder>, role="external", window="_blank"] をご覧下さい。 +

.Site:GroundReflectance　
----
  Site:GroundReflectance,
    0.2,                     !- January Ground Reflectance {dimensionless}
    0.2,                     !- February Ground Reflectance {dimensionless}
    0.2,                     !- March Ground Reflectance {dimensionless}
    0.2,                     !- April Ground Reflectance {dimensionless}
    0.2,                     !- May Ground Reflectance {dimensionless}
    0.2,                     !- June Ground Reflectance {dimensionless}
    0.2,                     !- July Ground Reflectance {dimensionless}
    0.2,                     !- August Ground Reflectance {dimensionless}
    0.2,                     !- September Ground Reflectance {dimensionless}
    0.2,                     !- October Ground Reflectance {dimensionless}
    0.2,                     !- November Ground Reflectance {dimensionless}
    0.2;                     !- December Ground Reflectance {dimensionless}
----

==== Site:GroundTemperature:BuildingSurface

Site:GroundTemperature:BuildingSurfaceクラスでは、地中の温度を入力します。 +
Site:GroundTemperature:BuildingSurfaceクラスの作成方法は https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-location-climate-weather-file-access.html#sitegroundtemperaturebuildingsurface[<bigladder>, role="external", window="_blank"] をご覧下さい。 +

.Site:GroundTemperature:BuildingSurface　
----
  Site:GroundTemperature:BuildingSurface,
    10,                      !- January Ground Temperature {C}
    10,                      !- February Ground Temperature {C}
    10,                      !- March Ground Temperature {C}
    10,                      !- April Ground Temperature {C}
    10,                      !- May Ground Temperature {C}
    10,                      !- June Ground Temperature {C}
    10,                      !- July Ground Temperature {C}
    10,                      !- August Ground Temperature {C}
    10,                      !- September Ground Temperature {C}
    10,                      !- October Ground Temperature {C}
    10,                      !- November Ground Temperature {C}
    10;                      !- December Ground Temperature {C}
----



==== Zone

Zoneクラスは、ゾーンに関するパラメータを記述します。

.Zone　
----
Zone,
    Zone1,                   !- Name
    0.0,                     !- Direction of Relative North {deg}
    0.0,                     !- X Origin {m}
    0.0,                     !- Y Origin {m}
    0.0,                     !- Z Origin {m}
    ,                        !- Type
    1,                       !- Multiplier
    2.7000,                  !- Ceiling Height {m}
    129.6;                   !- Volume {m3}
----

==== BuildingSurface:Detailed

BuildingSurface:Detailedクラスは、外壁構成に関するパラメータを記述します。 +
BuildingSurface:Detailedクラスの作成方法は https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-thermal-zone-description-geometry.html#buildingsurfacedetailed[<bigladder>, role="external", window="_blank"] をご覧下さい。 +


.BuildingSurface:Detailed　床
----
  BuildingSurface:Detailed,
    Floor,                   !- Name
    Floor,                   !- Surface Type
    Floor_configure,         !- Construction Name
    Zone1,                   !- Zone Name
    Ground,                  !- Outside Boundary Condition
    ,                        !- Outside Boundary Condition Object
    NoSun,                   !- Sun Exposure
    NoWind,                  !- Wind Exposure
    0.000000000000,          !- View Factor to Ground
    4,                       !- Number of Vertices
    8.000000000000,          !- Vertex 1 X-coordinate {m}
    6.000000000000,          !- Vertex 1 Y-coordinate {m}
    0.000000000000,          !- Vertex 1 Z-coordinate {m}
    8.000000000000,          !- Vertex 2 X-coordinate {m}
    0.000000000000,          !- Vertex 2 Y-coordinate {m}
    0.000000000000,          !- Vertex 2 Z-coordinate {m}
    0.000000000000,          !- Vertex 3 X-coordinate {m}
    0.000000000000,          !- Vertex 3 Y-coordinate {m}
    0.000000000000,          !- Vertex 3 Z-coordinate {m}
    0.000000000000,          !- Vertex 4 X-coordinate {m}
    6.000000000000,          !- Vertex 4 Y-coordinate {m}
    0.000000000000;          !- Vertex 4 Z-coordinate {m}
----

.BuildingSurface:Detailed　屋根
----
  BuildingSurface:Detailed,
    Roof,                    !- Name
    Roof,                    !- Surface Type
    Roof_configure,          !- Construction Name
    Zone1,                   !- Zone Name
    Outdoors,                !- Outside Boundary Condition
    ,                        !- Outside Boundary Condition Object
    SunExposed,              !- Sun Exposure
    WindExposed,             !- Wind Exposure
    0.000000000000,          !- View Factor to Ground
    4,                       !- Number of Vertices
    0.000000000000,          !- Vertex 1 X-coordinate {m}
    6.000000000000,          !- Vertex 1 Y-coordinate {m}
    2.700000000000,          !- Vertex 1 Z-coordinate {m}
    0.000000000000,          !- Vertex 2 X-coordinate {m}
    0.000000000000,          !- Vertex 2 Y-coordinate {m}
    2.700000000000,          !- Vertex 2 Z-coordinate {m}
    8.000000000000,          !- Vertex 3 X-coordinate {m}
    0.000000000000,          !- Vertex 3 Y-coordinate {m}
    2.700000000000,          !- Vertex 3 Z-coordinate {m}
    8.000000000000,          !- Vertex 4 X-coordinate {m}
    6.000000000000,          !- Vertex 4 Y-coordinate {m}
    2.700000000000;          !- Vertex 4 Z-coordinate {m}
----

.BuildingSurface:Detailed　外壁（南）
----
  BuildingSurface:Detailed,
    Wall_S,                  !- Name
    Wall,                    !- Surface Type
    Wall-configure,          !- Construction Name
    Zone1,                   !- Zone Name
    Outdoors,                !- Outside Boundary Condition
    ,                        !- Outside Boundary Condition Object
    SunExposed,              !- Sun Exposure
    WindExposed,             !- Wind Exposure
    0.500000000000,          !- View Factor to Ground
    4,                       !- Number of Vertices
    0.000000000000,          !- Vertex 1 X-coordinate {m}
    0.000000000000,          !- Vertex 1 Y-coordinate {m}
    2.700000000000,          !- Vertex 1 Z-coordinate {m}
    0.000000000000,          !- Vertex 2 X-coordinate {m}
    0.000000000000,          !- Vertex 2 Y-coordinate {m}
    0.000000000000,          !- Vertex 2 Z-coordinate {m}
    8.000000000000,          !- Vertex 3 X-coordinate {m}
    0.000000000000,          !- Vertex 3 Y-coordinate {m}
    0.000000000000,          !- Vertex 3 Z-coordinate {m}
    8.000000000000,          !- Vertex 4 X-coordinate {m}
    0.000000000000,          !- Vertex 4 Y-coordinate {m}
    2.700000000000;          !- Vertex 4 Z-coordinate {m}
----

.BuildingSurface:Detailed　外壁（北）
----
  BuildingSurface:Detailed,
    Wall_N,                  !- Name
    Wall,                    !- Surface Type
    Wall-configure,          !- Construction Name
    Zone1,                   !- Zone Name
    Outdoors,                !- Outside Boundary Condition
    ,                        !- Outside Boundary Condition Object
    SunExposed,              !- Sun Exposure
    WindExposed,             !- Wind Exposure
    0.500000000000,          !- View Factor to Ground
    4,                       !- Number of Vertices
    0.000000000000,          !- Vertex 1 X-coordinate {m}
    6.000000000000,          !- Vertex 1 Y-coordinate {m}
    2.700000000000,          !- Vertex 1 Z-coordinate {m}
    0.000000000000,          !- Vertex 2 X-coordinate {m}
    6.000000000000,          !- Vertex 2 Y-coordinate {m}
    0.000000000000,          !- Vertex 2 Z-coordinate {m}
    8.000000000000,          !- Vertex 3 X-coordinate {m}
    6.000000000000,          !- Vertex 3 Y-coordinate {m}
    0.000000000000,          !- Vertex 3 Z-coordinate {m}
    8.000000000000,          !- Vertex 4 X-coordinate {m}
    6.000000000000,          !- Vertex 4 Y-coordinate {m}
    2.700000000000;          !- Vertex 4 Z-coordinate {m}
----

.BuildingSurface:Detailed　外壁（西）
----
  BuildingSurface:Detailed,
    Wall_W,                  !- Name
    Wall,                    !- Surface Type
    Wall-configure,          !- Construction Name
    Zone1,                   !- Zone Name
    Outdoors,                !- Outside Boundary Condition
    ,                        !- Outside Boundary Condition Object
    SunExposed,              !- Sun Exposure
    WindExposed,             !- Wind Exposure
    0.500000000000,          !- View Factor to Ground
    4,                       !- Number of Vertices
    0.000000000000,          !- Vertex 1 X-coordinate {m}
    6.000000000000,          !- Vertex 1 Y-coordinate {m}
    2.700000000000,          !- Vertex 1 Z-coordinate {m}
    0.000000000000,          !- Vertex 2 X-coordinate {m}
    6.000000000000,          !- Vertex 2 Y-coordinate {m}
    0.000000000000,          !- Vertex 2 Z-coordinate {m}
    0.000000000000,          !- Vertex 3 X-coordinate {m}
    0.000000000000,          !- Vertex 3 Y-coordinate {m}
    0.000000000000,          !- Vertex 3 Z-coordinate {m}
    0.000000000000,          !- Vertex 4 X-coordinate {m}
    0.000000000000,          !- Vertex 4 Y-coordinate {m}
    2.700000000000;          !- Vertex 4 Z-coordinate {m}
----

.BuildingSurface:Detailed　外壁（東）
----
  BuildingSurface:Detailed,
    Wall_E,                  !- Name
    Wall,                    !- Surface Type
    Wall-configure,          !- Construction Name
    Zone1,                   !- Zone Name
    Outdoors,                !- Outside Boundary Condition
    ,                        !- Outside Boundary Condition Object
    SunExposed,              !- Sun Exposure
    WindExposed,             !- Wind Exposure
    0.500000000000,          !- View Factor to Ground
    4,                       !- Number of Vertices
    8.000000000000,          !- Vertex 1 X-coordinate {m}
    6.000000000000,          !- Vertex 1 Y-coordinate {m}
    2.700000000000,          !- Vertex 1 Z-coordinate {m}
    8.000000000000,          !- Vertex 2 X-coordinate {m}
    6.000000000000,          !- Vertex 2 Y-coordinate {m}
    0.000000000000,          !- Vertex 2 Z-coordinate {m}
    8.000000000000,          !- Vertex 3 X-coordinate {m}
    0.000000000000,          !- Vertex 3 Y-coordinate {m}
    0.000000000000,          !- Vertex 3 Z-coordinate {m}
    8.000000000000,          !- Vertex 4 X-coordinate {m}
    0.000000000000,          !- Vertex 4 Y-coordinate {m}
    2.700000000000;          !- Vertex 4 Z-coordinate {m}
----


==== FenestrationSurface:Detailed

FenestrationSurface:Detailedクラスは、窓構成に関するパラメータを記述します。 +
FenestrationSurface:Detailedクラスの作成方法は https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-thermal-zone-description-geometry.html#fenestrationsurfacedetailed[<bigladder>, role="external", window="_blank"] をご覧下さい。 +

.BuildingSurface:Detailed　窓（南1）
----
  FenestrationSurface:Detailed,
    Window_S1,               !- Name
    Window,                  !- Surface Type
    Window_configure,        !- Construction Name
    Wall_S,                  !- Building Surface Name
    ,                        !- Outside Boundary Condition Object
    0.500000000000,          !- View Factor to Ground
    ,                        !- Frame and Divider Name
    1,                       !- Multiplier
    4,                       !- Number of Vertices
    0.500000000000,          !- Vertex 1 X-coordinate {m}
    0.000000000000,          !- Vertex 1 Y-coordinate {m}
    2.200000000000,          !- Vertex 1 Z-coordinate {m}
    0.500000000000,          !- Vertex 2 X-coordinate {m}
    0.000000000000,          !- Vertex 2 Y-coordinate {m}
    0.200000000000,          !- Vertex 2 Z-coordinate {m}
    3.500000000000,          !- Vertex 3 X-coordinate {m}
    0.000000000000,          !- Vertex 3 Y-coordinate {m}
    0.200000000000,          !- Vertex 3 Z-coordinate {m}
    3.500000000000,          !- Vertex 4 X-coordinate {m}
    0.000000000000,          !- Vertex 4 Y-coordinate {m}
    2.200000000000;          !- Vertex 4 Z-coordinate {m}
----

.BuildingSurface:Detailed　窓（南2）
----
  FenestrationSurface:Detailed,
    Window_S2,               !- Name
    Window,                  !- Surface Type
    Window_configure,        !- Construction Name
    Wall_S,                  !- Building Surface Name
    ,                        !- Outside Boundary Condition Object
    0.500000000000,          !- View Factor to Ground
    ,                        !- Frame and Divider Name
    1,                       !- Multiplier
    4,                       !- Number of Vertices
    4.500000000000,          !- Vertex 1 X-coordinate {m}
    0.000000000000,          !- Vertex 1 Y-coordinate {m}
    2.200000000000,          !- Vertex 1 Z-coordinate {m}
    4.500000000000,          !- Vertex 2 X-coordinate {m}
    0.000000000000,          !- Vertex 2 Y-coordinate {m}
    0.200000000000,          !- Vertex 2 Z-coordinate {m}
    7.500000000000,          !- Vertex 3 X-coordinate {m}
    0.000000000000,          !- Vertex 3 Y-coordinate {m}
    0.200000000000,          !- Vertex 3 Z-coordinate {m}
    7.500000000000,          !- Vertex 4 X-coordinate {m}
    0.000000000000,          !- Vertex 4 Y-coordinate {m}
    2.200000000000;          !- Vertex 4 Z-coordinate {m}
----

==== Material, Construction

Materialクラスで建材の熱物性値を定義し、Constructionクラスで建材構成を記述します。 +
Materialクラスの作成方法は https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-surface-construction-elements.html#material[<bigladder>, role="external", window="_blank"] をご覧下さい。 +
Constructionクラスの作成方法は https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-surface-construction-elements.html#construction-000[<bigladder>, role="external", window="_blank"] をご覧下さい。 +


.Material　外壁
----
  Material,
    PLASTERBOARD-12mm,       !- Name
    Rough,                   !- Roughness
    0.01200,                 !- Thickness {m}
    0.16000,                 !- Conductivity {W/m-K}
    950.000,                 !- Density {kg/m3}
    840.00,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance

  Material,
    FIBERGLASS-66mm,         !- Name
    Rough,                   !- Roughness
    0.066,                   !- Thickness {m}
    0.040,                   !- Conductivity {W/m-K}
    12.000,                  !- Density {kg/m3}
    840.00,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance

  Material,
    WOODSIDING-9mm,          !- Name
    Rough,                   !- Roughness
    0.00900,                 !- Thickness {m}
    0.14000,                 !- Conductivity {W/m-K}
    530.000,                 !- Density {kg/m3}
    900.00,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance
----

.Construction　外壁
----
  Construction,
    Wall-configure,          !- Name
    WOODSIDING-9mm,          !- Outside Layer
    FIBERGLASS-66mm,         !- Layer 2
    PLASTERBOARD-12mm;       !- Layer 3
----


.Material　床
----
  Material,
    TIMBERFLOORING-25mm,     !- Name
    Rough,                   !- Roughness
    0.02500,                 !- Thickness {m}
    0.14000,                 !- Conductivity {W/m-K}
    650.000,                 !- Density {kg/m3}
    1200.0,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance

  Material,
    FIBERGLASS-1003mm,       !- Name
    Rough,                   !- Roughness
    1.003,                   !- Thickness {m}
    0.040,                   !- Conductivity {W/m-K}
    1.000,                   !- Density {kg/m3}
    100.0,                   !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance
----

【作業メモ】 + 
断熱材（FIBERGLASS-1003mm）について、密度と比熱はプログラムが許容する最小値とすることとされている。
比熱の最小値は　100 J/kg-K　と記載があったが、密度については記載が見つからなかった。 + 
参考：　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-surface-construction-elements.html#field-specific-heat[比熱の最小値]


.Construction　床
----
  Construction,
    Floor_configure,         !- Name
    FIBERGLASS-1003mm,       !- Outside Layer
    TIMBERFLOORING-25mm;     !- Layer 2
----

.Material　屋根
----
  Material,
    PLASTERBOARD-10mm,       !- Name
    Rough,                   !- Roughness
    0.01000,                 !- Thickness {m}
    0.16000,                 !- Conductivity {W/m-K}
    950.000,                 !- Density {kg/m3}
    840.00,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance

  Material,
    FIBERGLASS-111mm,        !- Name
    Rough,                   !- Roughness
    0.1118,                  !- Thickness {m}
    0.040,                   !- Conductivity {W/m-K}
    12.000,                  !- Density {kg/m3}
    840.00,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance

  Material,
    ROOFDECK-19mm,           !- Name
    Rough,                   !- Roughness
    0.01900,                 !- Thickness {m}
    0.14000,                 !- Conductivity {W/m-K}
    530.000,                 !- Density {kg/m3}
    900.00,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance
----

.Construction　屋根
----
  Construction,
    Roof_configure,          !- Name
    ROOFDECK-19mm,           !- Outside Layer
    FIBERGLASS-111mm,        !- Layer 2
    PLASTERBOARD-10mm;       !- Layer 3
----


==== WindowMaterial:Glazing

WindowMaterial:Glazingクラスでガラスの熱物性値を定義し、Constructionクラスで窓構成を記述します。 +
WindowMaterial:Glazingクラスの作成方法は https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-surface-construction-elements.html#windowmaterialglazing[<bigladder>, role="external", window="_blank"] をご覧下さい。 +

.WindowMaterial:Glazing
----
  WindowMaterial:Glazing,
    GlassType1,              !- Name
    SpectralAverage,         !- Optical Data Type
    ,                        !- Window Glass Spectral Data Set Name
    0.003175,                !- Thickness {m}
    0.86156,                 !- Solar Transmittance at Normal Incidence
    0.07846,                 !- Front Side Solar Reflectance at Normal Incidence
    0.07846,                 !- Back Side Solar Reflectance at Normal Incidence
    0.91325,                 !- Visible Transmittance at Normal Incidence
    0.08200,                 !- Front Side Visible Reflectance at Normal Incidence
    0.08200,                 !- Back Side Visible Reflectance at Normal Incidence
    0.0,                     !- Infrared Transmittance at Normal Incidence
    0.84,                    !- Front Side Infrared Hemispherical Emissivity
    0.84,                    !- Back Side Infrared Hemispherical Emissivity
    1.06;                    !- Conductivity {W/m-K}

  WindowMaterial:Gas,
    AirSpaceResistance,      !- Name
    AIR,                     !- Gas Type
    0.013;                   !- Thickness {m}
----

.Construction　窓
----
  Construction,
    window_configure,        !- Name
    GlassType1,              !- Outside Layer
    AirSpaceResistance,      !- Layer 2
    GlassType1;              !- Layer 3
----


==== Schedule

===== Schedule:Day:Hourly

Schedule:Day:Hourlyクラスでは、時刻別のスケジュールの設定を行います。 +
Schedule:Day:Hourlyクラスの作成方法は https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-schedules.html#scheduledayhourly[<bigladder>, role="external", window="_blank"] をご覧下さい。 +

.Schedule:Day:Hourly　すきま風
----
Schedule:Day:Hourly,
    Day Sch 1,               !- Name
    Fraction,                !- Schedule Type Limits Name
    1,                       !- Hour 1
    1,                       !- Hour 2
    1,                       !- Hour 3
    1,                       !- Hour 4
    1,                       !- Hour 5
    1,                       !- Hour 6
    1,                       !- Hour 7
    1,                       !- Hour 8
    1,                       !- Hour 9
    1,                       !- Hour 10
    1,                       !- Hour 11
    1,                       !- Hour 12
    1,                       !- Hour 13
    1,                       !- Hour 14
    1,                       !- Hour 15
    1,                       !- Hour 16
    1,                       !- Hour 17
    1,                       !- Hour 18
    1,                       !- Hour 19
    1,                       !- Hour 20
    1,                       !- Hour 21
    1,                       !- Hour 22
    1,                       !- Hour 23
    1;                       !- Hour 24
----

.Schedule:Day:Hourly　暖房設定温度
----
Schedule:Day:Hourly,
    Zone Heating Setpoint All Days,  !- Name
    Temperature,             !- Schedule Type Limits Name
    20.,                     !- Hour 1
    20.,                     !- Hour 2
    20.,                     !- Hour 3
    20.,                     !- Hour 4
    20.,                     !- Hour 5
    20.,                     !- Hour 6
    20.,                     !- Hour 7
    20.,                     !- Hour 8
    20.,                     !- Hour 9
    20.,                     !- Hour 10
    20.,                     !- Hour 11
    20.,                     !- Hour 12
    20.,                     !- Hour 13
    20.,                     !- Hour 14
    20.,                     !- Hour 15
    20.,                     !- Hour 16
    20.,                     !- Hour 17
    20.,                     !- Hour 18
    20.,                     !- Hour 19
    20.,                     !- Hour 20
    20.,                     !- Hour 21
    20.,                     !- Hour 22
    20.,                     !- Hour 23
    20.;                     !- Hour 24
----

.Schedule:Day:Hourly　冷房設定温度
----
Schedule:Day:Hourly,
    Zone Cooling Setpoint All Days,  !- Name
    Temperature,             !- Schedule Type Limits Name
    27.,                     !- Hour 1
    27.,                     !- Hour 2
    27.,                     !- Hour 3
    27.,                     !- Hour 4
    27.,                     !- Hour 5
    27.,                     !- Hour 6
    27.,                     !- Hour 7
    27.,                     !- Hour 8
    27.,                     !- Hour 9
    27.,                     !- Hour 10
    27.,                     !- Hour 11
    27.,                     !- Hour 12
    27.,                     !- Hour 13
    27.,                     !- Hour 14
    27.,                     !- Hour 15
    27.,                     !- Hour 16
    27.,                     !- Hour 17
    27.,                     !- Hour 18
    27.,                     !- Hour 19
    27.,                     !- Hour 20
    27.,                     !- Hour 21
    27.,                     !- Hour 22
    27.,                     !- Hour 23
    27.;                     !- Hour 24
----

.Schedule:Day:Hourly　室温制御方法
----
Schedule:Day:Hourly,
    Control Type All Days,   !- Name
    Control Type,            !- Schedule Type Limits Name
    4,                       !- Hour 1
    4,                       !- Hour 2
    4,                       !- Hour 3
    4,                       !- Hour 4
    4,                       !- Hour 5
    4,                       !- Hour 6
    4,                       !- Hour 7
    4,                       !- Hour 8
    4,                       !- Hour 9
    4,                       !- Hour 10
    4,                       !- Hour 11
    4,                       !- Hour 12
    4,                       !- Hour 13
    4,                       !- Hour 14
    4,                       !- Hour 15
    4,                       !- Hour 16
    4,                       !- Hour 17
    4,                       !- Hour 18
    4,                       !- Hour 19
    4,                       !- Hour 20
    4,                       !- Hour 21
    4,                       !- Hour 22
    4,                       !- Hour 23
    4;                       !- Hour 24
----

===== Schedule:Week:Daily

Schedule:Week:Dailyクラスでは、曜日別のスケジュールの設定を行います。 +
Schedule:Week:Dailyクラスの作成方法は https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-schedules.html#scheduleweekdaily[<bigladder>, role="external", window="_blank"] をご覧下さい。 +

.Schedule:Week:Daily　すきま風　
----
Schedule:Week:Daily,
    Week Sch 1,              !- Name
    Day Sch 1,               !- Sunday Schedule:Day Name
    Day Sch 1,               !- Monday Schedule:Day Name
    Day Sch 1,               !- Tuesday Schedule:Day Name
    Day Sch 1,               !- Wednesday Schedule:Day Name
    Day Sch 1,               !- Thursday Schedule:Day Name
    Day Sch 1,               !- Friday Schedule:Day Name
    Day Sch 1,               !- Saturday Schedule:Day Name
    Day Sch 1,               !- Holiday Schedule:Day Name
    Day Sch 1,               !- SummerDesignDay Schedule:Day Name
    Day Sch 1,               !- WinterDesignDay Schedule:Day Name
    Day Sch 1,               !- CustomDay1 Schedule:Day Name
    Day Sch 1;               !- CustomDay2 Schedule:Day Name
----

.Schedule:Week:Daily　暖房設定温度
----
Schedule:Week:Daily,
    Zone Heating Setpoint All Weeks,  !- Name
    Zone Heating Setpoint All Days,  !- Sunday Schedule:Day Name
    Zone Heating Setpoint All Days,  !- Monday Schedule:Day Name
    Zone Heating Setpoint All Days,  !- Tuesday Schedule:Day Name
    Zone Heating Setpoint All Days,  !- Wednesday Schedule:Day Name
    Zone Heating Setpoint All Days,  !- Thursday Schedule:Day Name
    Zone Heating Setpoint All Days,  !- Friday Schedule:Day Name
    Zone Heating Setpoint All Days,  !- Saturday Schedule:Day Name
    Zone Heating Setpoint All Days,  !- Holiday Schedule:Day Name
    Zone Heating Setpoint All Days,  !- SummerDesignDay Schedule:Day Name
    Zone Heating Setpoint All Days,  !- WinterDesignDay Schedule:Day Name
    Zone Heating Setpoint All Days,  !- CustomDay1 Schedule:Day Name
    Zone Heating Setpoint All Days;  !- CustomDay2 Schedule:Day Name
----

.Schedule:Week:Daily　冷房設定温度
----
Schedule:Week:Daily,
    Zone Cooling Setpoint All Weeks,  !- Name
    Zone Cooling Setpoint All Days,  !- Sunday Schedule:Day Name
    Zone Cooling Setpoint All Days,  !- Monday Schedule:Day Name
    Zone Cooling Setpoint All Days,  !- Tuesday Schedule:Day Name
    Zone Cooling Setpoint All Days,  !- Wednesday Schedule:Day Name
    Zone Cooling Setpoint All Days,  !- Thursday Schedule:Day Name
    Zone Cooling Setpoint All Days,  !- Friday Schedule:Day Name
    Zone Cooling Setpoint All Days,  !- Saturday Schedule:Day Name
    Zone Cooling Setpoint All Days,  !- Holiday Schedule:Day Name
    Zone Cooling Setpoint All Days,  !- SummerDesignDay Schedule:Day Name
    Zone Cooling Setpoint All Days,  !- WinterDesignDay Schedule:Day Name
    Zone Cooling Setpoint All Days,  !- CustomDay1 Schedule:Day Name
    Zone Cooling Setpoint All Days;  !- CustomDay2 Schedule:Day Name
----

.Schedule:Week:Daily　室温制御方法
----
Schedule:Week:Daily,
    Control Type All Weeks,  !- Name
    Control Type All Days,   !- Sunday Schedule:Day Name
    Control Type All Days,   !- Monday Schedule:Day Name
    Control Type All Days,   !- Tuesday Schedule:Day Name
    Control Type All Days,   !- Wednesday Schedule:Day Name
    Control Type All Days,   !- Thursday Schedule:Day Name
    Control Type All Days,   !- Friday Schedule:Day Name
    Control Type All Days,   !- Saturday Schedule:Day Name
    Control Type All Days,   !- Holiday Schedule:Day Name
    Control Type All Days,   !- SummerDesignDay Schedule:Day Name
    Control Type All Days,   !- WinterDesignDay Schedule:Day Name
    Control Type All Days,   !- CustomDay1 Schedule:Day Name
    Control Type All Days;   !- CustomDay2 Schedule:Day Name
----


===== Schedule:Year

Schedule:Yearクラスでは、年間スケジュールの設定を行います。 +
Schedule:Yearクラスの作成方法は https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-schedules.html#scheduleyear[<bigladder>, role="external", window="_blank"] をご覧下さい。 +

.Schedule:Year　すきま風　
----
Schedule:Year,
    Sch 1,                   !- Name
    Fraction,                !- Schedule Type Limits Name
    Week Sch 1,              !- Schedule:Week Name 1
    1,                       !- Start Month 1
    1,                       !- Start Day 1
    12,                      !- End Month 1
    31;                      !- End Day 1
----

.Schedule:Year　暖房設定温度
----
Schedule:Year,
    Heating Setpoints,       !- Name
    Temperature,             !- Schedule Type Limits Name
    Zone Heating Setpoint All Weeks,  !- Schedule:Week Name 1
    1,                       !- Start Month 1
    1,                       !- Start Day 1
    12,                      !- End Month 1
    31;                      !- End Day 1
----

.Schedule:Year　冷房設定温度
----
Schedule:Year,
    Cooling Setpoints,       !- Name
    Temperature,             !- Schedule Type Limits Name
    Zone Cooling Setpoint All Weeks,  !- Schedule:Week Name 1
    1,                       !- Start Month 1
    1,                       !- Start Day 1
    12,                      !- End Month 1
    31;                      !- End Day 1
----

.Schedule:Year　室温制御方法
----
Schedule:Year,
    Zone Control Type Sched, !- Name
    Control Type,            !- Schedule Type Limits Name
    Control Type All Weeks,  !- Schedule:Week Name 1
    1,                       !- Start Month 1
    1,                       !- Start Day 1
    12,                      !- End Month 1
    31;                      !- End Day 1
----


==== ZoneInfiltration:DesignFlowRate

ZoneInfiltration:DesignFlowRateクラスでは、すきま風の設定を行います。 +
ZoneInfiltration:DesignFlowRateクラスの作成方法は https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-airflow.html#zoneinfiltrationdesignflowrate[<bigladder>, role="external", window="_blank"] をご覧下さい。 +

.すきま風　
----
ZoneInfiltration:DesignFlowRate,
    Infil_1,                 !- Name
    Zone1,                   !- Zone or ZoneList Name
    Sch 1,                   !- Schedule Name
    Flow/Zone,               !- Design Flow Rate Calculation Method
    0.018,                   !- Design Flow Rate {m3/s}
    ,                        !- Flow per Zone Floor Area {m3/s-m2}
    ,                        !- Flow per Exterior Surface Area {m3/s-m2}
    ,                        !- Air Changes per Hour {1/hr}
    1,                       !- Constant Term Coefficient
    0,                       !- Temperature Term Coefficient
    0,                       !- Velocity Term Coefficient
    0;                       !- Velocity Squared Term Coefficient
----

==== OtherEquipment

OtherEquipmentクラスでは、内部発熱の設定を行います。 +
OtherEquipmentクラスの作成方法は https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-internal-gains-people-lights-other.html#otherequipment[<bigladder>, role="external", window="_blank"] をご覧下さい。 +

.OtherEquipment
----
OtherEquipment,
    Euip 1,                  !- Name
    None,                    !- Fuel Type
    Zone1,                   !- Zone or ZoneList Name
    Sch 1,                   !- Schedule Name
    EquipmentLevel,          !- Design Level Calculation Method
    200,                     !- Design Level {W}
    ,                        !- Power per Zone Floor Area {W/m2}
    ,                        !- Power per Person {W/person}
    0,                       !- Fraction Latent
    0.6,                     !- Fraction Radiant
    0,                       !- Fraction Lost
    ,                        !- Carbon Dioxide Generation Rate {m3/s-W}
    General;                 !- End-Use Subcategory
----


==== HVAC system


===== ZoneControl:Thermostat

ZoneControl:Thermostatクラスは、ゾーンを指定された温度に制御するために使用されます。 +
ZoneControl:Thermostatは、制御スケジュールと1つ以上の制御オブジェクトを参照し、これらは1つ以上の設定値スケジュールを参照します。

.ZoneControl:Thermostat　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-controls-thermostats.html#zonecontrolthermostat[<bigladder>, role="external", window="_blank"]
----
ZoneControl:Thermostat,
    Zone 1 Thermostat,                !- Name
    Zone1,                            !- Zone or ZoneList Name
    Zone Control Type Sched,          !- Control Type Schedule Name
    ThermostatSetpoint:DualSetpoint,  !- Control 1 Object Type
    Heating Cooling Setpoints;        !- Control 1 Name
----

====== Name
* 任意の名称を入力します。

====== Zone or ZoneList Name
* 対象とするゾーンもしくはゾーンリストの名称を入力します。

====== Control Type Schedule Name

* 別途定義した制御スケジュール名を入力します。 制御スケジュールには、シミュレーション中に使用される制御タイプ番号を指定します。有効な制御タイプ番号は次のとおりです。
** 0 - 無制御（指定なし、またはデフォルト）
** 1 - 単一の加熱セットポイント
** 2 - 単一の冷房設定値
** 3 - 暖房/冷房の単一設定値
** 4 - 不感帯のある室温設定値（暖房と冷房）

* 例えば、ZoneControl:Thermostatから参照されるスケジュールが、特定の時間帯に制御タイプが4である場合、その時間帯に「不感帯のある室温設定値（暖房と冷房）」制御が使用されることを示しています。

====== Control 1 Object Type

* コントロールタイプの種類を次の4つの選択肢から選択します。
** ThermostatSetpoint:SingleHeating　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-controls-thermostats.html#thermostatsetpointsingleheating[<bigladder>, role="external", window="_blank"]
** ThermostatSetpoint:SingleCooling　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-controls-thermostats.html#thermostatsetpointsinglecooling[<bigladder>, role="external", window="_blank"]
** ThermostatSetpoint:SingleHeatingOrCooling　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-controls-thermostats.html#thermostatsetpointsingleheatingorcooling[<bigladder>, role="external", window="_blank"]
** ThermostatSetpoint:DualSetpoint　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-controls-thermostats.html#thermostatsetpointdualsetpoint[<bigladder>, role="external", window="_blank"]

====== Control 1 Name

* 別途定義したコントロールタイプの名称を入力します。



===== ThermostatSetpoint:DualSetpoint

.ThermostatSetpoint:DualSetpoint　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-controls-thermostats.html#thermostatsetpointdualsetpoint[<bigladder>, role="external", window="_blank"]
----
ThermostatSetpoint:DualSetpoint,
    Heating Cooling Setpoints,  !- Name
    Heating Setpoints,          !- Heating Setpoint Temperature Schedule Name
    Cooling Setpoints;          !- Cooling Setpoint Temperature Schedule Name
----

====== Name
* 任意の名称を入力します。

====== Heating Setpoint Temperature Schedule Name
* 暖房運転時設定温度のスケジュール名称を入力します。

====== Cooling Setpoint Temperature Schedule Name
* 冷房運転時設定温度のスケジュール名称を入力します。


===== ZoneHVAC:IdealLoadsAirSystem

ZoneHVAC:IdealLoadsAirSystemコンポーネントを使えば、最もシンプルにHVACシステムを設定することができます。
ユーザーは完全なHVACシステムをモデル化することなく、建物の性能を検討したい場合に使用されます。
設定が必要なのは、ゾーン制御、ゾーン機器構成、および理想的な負荷システムコンポーネントだけです。

.ZoneHVAC:IdealLoadsAirSystem　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-forced-air-units.html#zonehvacidealloadsairsystem[<bigladder>, role="external", window="_blank"]
----
ZoneHVAC:IdealLoadsAirSystem,
    Zone1Air,                !- Name
    ,                        !- Availability Schedule Name
    NODE_1,                  !- Zone Supply Air Node Name
    ,                        !- Zone Exhaust Air Node Name
    ,                        !- System Inlet Air Node Name
    50,                      !- Maximum Heating Supply Air Temperature {C}
    13,                      !- Minimum Cooling Supply Air Temperature {C}
    0.010,                   !- Maximum Heating Supply Air Humidity Ratio {kgWater/kgDryAir}
    0.010,                   !- Minimum Cooling Supply Air Humidity Ratio {kgWater/kgDryAir}
    ,                        !- Heating Limit
    ,                        !- Maximum Heating Air Flow Rate {m3/s}
    ,                        !- Maximum Sensible Heating Capacity {W}
    ,                        !- Cooling Limit
    ,                        !- Maximum Cooling Air Flow Rate {m3/s}
    ,                        !- Maximum Total Cooling Capacity {W}
    ,                        !- Heating Availability Schedule Name
    ,                        !- Cooling Availability Schedule Name
    ConstantSupplyHumidityRatio,  !- Dehumidification Control Type
    ,                        !- Cooling Sensible Heat Ratio {dimensionless}
    ConstantSupplyHumidityRatio,  !- Humidification Control Type
    ,                        !- Design Specification Outdoor Air Object Name
    ,                        !- Outdoor Air Inlet Node Name
    ,                        !- Demand Controlled Ventilation Type
    ,                        !- Outdoor Air Economizer Type
    ,                        !- Heat Recovery Type
    ,                        !- Sensible Heat Recovery Effectiveness {dimensionless}
    ;                        !- Latent Heat Recovery Effectiveness {dimensionless}
----

====== Name
* 任意の名称を入力します。
* この名称は　ZoneHVAC:EquipmentList から参照されます。

====== Zone Supply Air Node Name
* 給気ノードの名称を入力します。これは、本コンポーネントがサービスを提供するゾーンのゾーン給気ノードの1つと同じでなければなりません。

====== Maximum Heating Supply Air Temperature {C}
* 給気温度の最大値を入力します。

====== Minimum Cooling Supply Air Temperature {C}
* 給気温度の最小値を入力します。

====== Maximum Heating Supply Air Humidity Ratio {kgWater/kgDryAir}
* 給気湿度の最大値を入力します。

====== Minimum Cooling Supply Air Humidity Ratio {kgWater/kgDryAir}
* 給気湿度の最小値を入力します。選択肢は以下の4つです。

====== Dehumidification Control Type
* 除湿の制御方式を選択します。選択肢は以下の4つです。
** ConstantSensibleHeatRatio
** Humidistat
** None
** ConstantSupplyHumidityRatio

====== Humidification Control Type
* 加湿の制御方式を選択します。選択肢は以下の3つです。
** None
** Humidistat
** ConstantSupplyHumidityRatio


===== ZoneHVAC:EquipmentList

このクラスには、ゾーンにサービスを提供するすべてのHVAC機器を登録し、それぞれの起動の優先順位を定義します。
リストの各項目には、4つのフィールドが関連付けられています。
Object TypeとNameは、特定の機器オブジェクトを識別します。
Cooling SequenceとHeat or No-Load Sequenceは、複数のタイプのHVAC機器があるゾーンのシミュレーションの順番を指定します。

.ZoneHVAC:EquipmentList　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-equipment.html#zonehvacequipmentlist[<bigladder>, role="external", window="_blank"]
----
ZoneHVAC:EquipmentList,
    Zone1Equipment,          !- Name
    SequentialLoad,          !- Load Distribution Scheme
    ZoneHVAC:IdealLoadsAirSystem,  !- Zone Equipment 1 Object Type
    Zone1Air,                !- Zone Equipment 1 Name
    1,                       !- Zone Equipment 1 Cooling Sequence
    1,                       !- Zone Equipment 1 Heating or No-Load Sequence
    ,                        !- Zone Equipment 1 Sequential Cooling Fraction Schedule Name
    ;                        !- Zone Equipment 1 Sequential Heating Fraction Schedule Name
----

====== Zone Equipment 1 Object Type
* ゾーンに設置されたHVAC機器の名称（ZoneHVAC:IdealLoadsAirSystem）を指定します。

====== Zone Equipment 1 Cooling Sequence
* ゾーンサーモスタットが冷房を要求する際の、ゾーン機器のシミュレーション順序を指定します。

====== Zone Equipment 1 Heating or No-Load Sequence
* ゾーンサーモスタットが暖房を要求した場合、もしくは負荷がない場合のゾーン機器のシミュレーション順序を指定します。


===== NodeList

.NodeList　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-node-branch-management.html#nodelist[<bigladder>, role="external", window="_blank"]
----
NodeList,
    Zone1Inlets,             !- Name
    NODE_1;                  !- Node 1 Name
----


===== ZoneHVAC:EquipmentConnections

ZoneHVAC:EquipmentConnectionsステートメントは、HVACの観点から各サーマルゾーンの詳細を定義する。
他のステートメントと同様に、このクラスの最初の2つの項目は、キーワードと識別名で、ゾーンをその幾何学的入力、内部利得など、入力のHVACセクションの他のステートメントにリンクします。
次の3つの項目は、以下に詳述するリスト（機器、吸気ノード、排気ノード）の名前である。
ゾーンからの排気ノードがない場合、このフィールドは空白になることに注意してください。
また、エアインレットノードがない場合、このフィールドは空白になります。
最後に、ゾーン-HVACの記述を完成させるために、2つのノード名が必要です。
1つ目のノードは、空気のヒートバランスを実行するゾーンのメイン空気ノードである。
もう1つのノードは、ゾーンからの戻り空気の経路である。

.ZoneHVAC:EquipmentConnections　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-equipment.html#zonehvacequipmentconnections[<bigladder>, role="external", window="_blank"]
----
ZoneHVAC:EquipmentConnections,
    Zone1,                   !- Zone Name
    Zone1Equipment,          !- Zone Conditioning Equipment List Name
    Zone1Inlets,             !- Zone Air Inlet Node or NodeList Name
    ,                        !- Zone Air Exhaust Node or NodeList Name
    NODE_2,                  !- Zone Air Node Name
    NODE_3;                  !- Zone Return Air Node or NodeList Name
----

====== Zone Name（required）
* ゾーン名称を入力します。

====== Zone Conditioning Equipment List Name（required）
* 「ZoneHVAC:EquipmentList」で定義した名称を入力します。

====== Zone Air Inlet Node or NodeList Name
* 給気に関するノード名称を入力します。

====== Zone Air Exhaust Node or NodeList Name
* 排気に関するノード名称を入力します。

====== Zone Air Node Name（required）
* ゾーン空気に関するノード名称を入力します。

====== Zone Return Air Node or NodeList Name
* 還気に関するノード名称を入力します。