== 熱源サブシステムテストに関する作業メモ

=== 2021.08.25

==== EnergyPlusにおける2ポンプシステムのモデリング	
* 1次ポンプを各チラーに与えることは不可（常にポンプが運転してしまう）。
* 1次ポンプの台数制御はチラーの容量が同じ場合にしか使えない。
* 設計通りに組もうとするとHEXを挟んで2つのループを作る必要がある？link:https://unmethours.com/question/25108/how-can-we-model-ashrae-901-2004-compliant-chilledcondensing-water-loop-pumps/[link]
* EnergyPlusでは冷却水の変流量制御はできない。link:https://unmethours.com/question/54977/how-to-simulate-a-variable-speed-condenser-water-pump-in-energyplus/[link]


==== 現状のモデルの課題	
* 1ポンプシステム（チラー冷水も変流量）になっている。
* 各機器についてガイドライン指定の仕様を反映できていない。
* 蒸気/温水吸収冷凍機を使っているが、定格効率を指定できない。link:https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-plant-equipment.html#chillerabsorption[link]
* ガス焚を用いる場合、温水側も作成する必要がある？link:https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-plant-equipment.html#chillerheaterabsorptiondirectfired[link]
* 冷却水の変流量制御ができない。
* 熱源台数制御設定値の変更がうまく機能していないため要確認。


=== 2021.09.22
==== 今回取り組んだ課題
* link:https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-plant-equipment.html#chillerheaterabsorptiondirectfired[ChillerHeater:Absorption:DirectFired]を用いてガス焚をモデル化しようとしたが、以下のエラーを解消できなかった。link:https://unmethours.com/question/27397/solve-error-relating-chillerheater-in-e/[Unmet Hours]によると、このオブジェクトを使う場合にオートサイズ機能が悪さをするようであるが、すべての仕様を入力してオートサイズを行わない場合でもエラーは無くならなかった。とりあえず、以下の検討ではlink:https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-plant-equipment.html#chillerabsorptionindirect[Chiller:Absorption:Indirect]を使用している（入力は蒸気）。

```
** Severe  ** CalcGasAbsorberChillerModel: Condenser flow = 0, for Gas Absorber Chiller=AR
**   ~~~   **  During Warmup, Environment=JSBC2O18 (O1-O1:31-12), at Simulation time=01/01 00:00 - 00:15
```

* EnergyPlusにおけるサブシステムの計算方法についてlink:https://unmethours.com/question/61452/how-to-simulate-a-subsystem-by-energyplus/[Unmet Hours]で質問したが、まだ回答なし。

* ガイドラインの機器仕様の反映（以下にて説明）

==== 機器仕様の入力

===== link:https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-plant-equipment.html#chillerelectriceir[AHP (Chiller:Electric:EIR)]

以下の3つの特性を入力できる。

* Field: Cooling Capacity Function of Temperature Curve Name
定格条件時の能力に対する最大能力比を冷水出口温度と冷却水入口温度の2次式（Biquadratic）で指定する。このカーブのアウトプットは定格条件時に1になる必要がある。

* Field: Electric Input to Cooling Output Ratio Function of Temperature Curve Name
定格条件時のEIR（COPの逆数）に対する比を冷水出口温度と冷却水入口温度の2次式（Biquadratic）で指定する。このカーブのアウトプットは定格条件時に1になる必要がある。

* Field: Electric Input to Cooling Output Ratio Function of Part Load Ratio Curve Name
EIRの部分負荷特性を2次式で指定する。ある条件下の消費電力をその時の最大能力で除した値に対して、最大能力比基準の比を計算し、それを負荷率で近似したカーブを与える。日本のプログラムと比べるとやや特殊と思われる。

===== link:https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-plant-equipment.html#chillerabsorptionindirect[AR (Chiller:Absorption:Indirect)]

以下の7つの特性を入力できる。

* Field: Generator Heat Input Function of Part Load Ratio Curve Name
負荷率の3次式でEIRを近似したカーブを指定する。定格点で1に合わせる必要がないため、この特性によって実質的に定格COPを指定できる。

* Field: Pump Electric Input Function of Part Load Ratio Curve Name
負荷率の2次式または3次式で補機電力比を近似したカーブを指定する。

* Field: Capacity Correction Function of Condenser Temperature Curve Name
冷却水温度の2次式または3次式で最大能力比を近似したカーブを指定する。

* Field: Capacity Correction Function of Chilled Water Temperature Curve Name
冷水温度の2次式または3次式で最大能力比を近似したカーブを指定する。

* Field: Capacity Correction Function of Generator Temperature Curve Name
再生温度の2次式または3次式で最大能力比を近似したカーブを指定する。

* Field: Generator Heat Input Correction Function of Condenser Temperature Curve Name
冷却水温度の2次式または3次式で入力比を近似したカーブを指定する。

* Field: Generator Heat Input Correction Function of Chilled Water Temperature Curve Name
冷却水温度の2次式または3次式で入力比を近似したカーブを指定する。

==== 計算結果
* AHPの特性は他のツールとほぼ一致するようになった。上記の部分負荷特性の与え方は何度か試行錯誤を要した。
* ARの特性については、定格点は一致したものの、冷却水温度に対する変化特性が反映されていない。今のところ原因は不明。部分負荷特性についても未確認。
* 以下の通りまだ大きな課題がいくつかあるが、システム全体としてのエネルギー特性は他のツールとほぼ一致するようになってきた。

==== 課題
* ARの冷却水温度特性の反映
* ポンプ特性の反映
* 1ポンプシステム（チラー冷水も変流量）になっている
* 冷却水の変流量制御ができない
* 熱源台数制御設定値の変更がうまく機能していないため要確認


=== 2021.10.18
==== 今回取り組んだ課題
* ARの冷却水温度特性の反映
* 熱源台数制御設定値の変更がうまく機能していないため要確認
* ポンプ特性の反映

==== 入力ファイルの修正点

===== ARの冷却水温度特性の反映
link:https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-plant-equipment.html#chillerabsorptionindirect[Chiller:Absorption:Indirect]は以下の通り冷却水温度に対する再生器への入力熱量の変化特性を2〜3次式で指定できるようになっているはずであるが、前回の計算結果では冷却水温度が変化しても入力熱量に変化が見られなかった。その後、試しにこのカーブの係数を極端な値に変更してみても入力熱量の計算結果はまったく変化しなかった。

_Field: Generator Heat Input Correction Function of Condenser Temperature Curve Name_
_This alpha field specifies the name of a quadratic or cubic curve which correlates the chiller’s heat input as a function of condenser entering water temperature. This curve is used to correct generator heat input at off-design condensing temperatures._

link:https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ChillerIndirectAbsorption.cc[Source code]（おそらくこれで合っていると思われる）を見てみると、冷却水温度特性のカーブの計算コードの中で再生器の入口ノードの温度を参照しているように見えるため、これはプログラムのバグではないかと思われる。このバグ疑惑についてはUnmetHours等で問い合わせても良い。
```
! Line 1984
 Real64 HeatInputfCondTemp = 1.0; // performance curve output
    if (this->GeneratorInletNodeNum > 0) {
        if (this->HeatInputFCondTempPtr > 0) {
            HeatInputfCondTemp =
                CurveManager::CurveValue(state, this->HeatInputFCondTempPtr, state.dataLoopNodes->Node(this->GeneratorInletNodeNum).Temp);
        } else {
            HeatInputfCondTemp = 1.0;
        }
    }
```

===== 熱源台数制御設定値の変更
E+では以下のように、熱源のリストを複数作成し、各リストが運転する負荷熱量帯を指定することで台数制御の設定が可能である。増段と減段の閾値を別々に指定することはできない。
```
  PlantEquipmentOperation:CoolingLoad,
    CHW Loop Scheme 1,       !- Name
    0,                      !- Load Range 1 Lower Limit {W}
    270000,                 !- Load Range 1 Upper Limit {W}
    CHW Loop Scheme 1 Range 1 Equipment List,  !- Range 1 Equipment List Name
    270000,                    !- Load Range 1 Lower Limit {W}
    540000,                 !- Load Range 1 Upper Limit {W}
    CHW Loop Scheme 1 Range 2 Equipment List,  !- Range 1 Equipment List Name
    540000,                    !- Load Range 1 Lower Limit {W}
    1500000,                !- Load Range 1 Upper Limit {W}
    CHW Loop Scheme 1 Range 3 Equipment List;  !- Range 1 Equipment List Name

  PlantEquipmentList,
    CHW Loop Scheme 1 Range 1 Equipment List,  !- Name
    Chiller:Electric:EIR,    !- Equipment 1 Object Type
    AHP1;                    !- Equipment 1 Name
  
  PlantEquipmentList,
    CHW Loop Scheme 1 Range 2 Equipment List,  !- Name
    Chiller:Electric:EIR,    !- Equipment 1 Object Type
    AHP1,                    !- Equipment 1 Name
    Chiller:Electric:EIR,    !- Equipment 2 Object Type
    AHP2;                    !- Equipment 2 Name
  
  PlantEquipmentList,
    CHW Loop Scheme 1 Range 3 Equipment List,  !- Name
    Chiller:Electric:EIR,    !- Equipment 1 Object Type
    AHP1,                    !- Equipment 1 Name
    Chiller:Electric:EIR,    !- Equipment 2 Object Type
    AHP2,                    !- Equipment 2 Name
    Chiller:Absorption:Indirect,      !- Equipment 3 Object Type
    AR;                      !- Equipment 3 Name
```

上記は90％で増減段の設定であるが、HSS230用に40％で増減段するように変更したところ、3台の熱源がすべて運転するようになった。前回計算では同様の設定で3台起動しなかったと思うが、何か間違いがあったのかもしれない。また、HSS230においてARが部分負荷で運転した結果、部分負荷特性の入力方法に誤りがあったことが分かった。マニュアルに、

_The curve output is multiplied by the chiller’s nominal capacity and operating part-load ratio or minimum part-load ratio, whichever is greater, to determine the amount of heat input required for the given operating conditons._

という記述があったため、このカーブの出力＝蒸気入力/（定格能力*負荷率）と理解していたが、計算値から推測すると実際には、カーブの出力＝蒸気入力/定格能力、だったようである。


===== ポンプ特性の反映
これまで調べた限りでは、E+においては日本では一般的な2ポンプシステムを構築することはできないようである。よって、link:https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-pumps.html#headeredpumpsvariablespeed[HeaderedPumps:VariableSpeed]を用いて台数制御を行う1系統のポンプ群のみを定義し、その入力値によって可能な範囲で両ポンプの特性を反映する。

* 定格電力：2次ポンプ3台＋1次ポンプ3台の合計電力を入力する。ただし、2次ポンプは揚程170kPa相当の電力を入力する。
* 揚程：2次ポンプ170kPa＋1次ポンプ147kPa＝317kPaを入力する。
* モータ効率：6台のポンプのモータ効率×インバータ効率をもとに、定格電力による加重平均値を入力する。
* 部分負荷特性：link:https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-pumps.html#pumpvariablespeed[Pump:VariableSpeed]やlink:https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-pumps.html#headeredpumpsvariablespeed[HeaderedPumps:VariableSpeed]では、定格電力に対する電力消費率を負荷率PLR（＝流量比）の4次式で与えることができる。2次ポンプは前後圧一定制御であり理論的には電力は流量に比例するため1次式で与えることになる。ただし、定回転の1次ポンプの影響を考慮するため、1台目に起動するAHPの1次ポンプ電力相当分（3.53kW）が切片となるように1次式の係数を入力する。

ちなみに、基本的に揚程とモータ効率の入力は電力計算には影響せず、ポンプ効率等の出力にのみ影響するようである。ただし、圧力計算を行う計算モードの場合には何らか反映されると思われる（link:https://bigladdersoftware.com/epx/docs/9-4/engineering-reference/pumps.html#variable-speed-pump[Engineering Reference]）。

==== 計算結果
* ポンプ電力（1次＋2次）は他のツールとほぼ一致するようになった。閾値を変更するHSS230だけは想定している1次ポンプの運転台数が異なるため、E+の電力が他のツールよりも小さい。
* ARの冷却水温度特性が反映されていないという問題（HSS110）は残っているものの、それ以外は他のツールと遜色ない結果になったと考えられる。

==== 課題
残った熱源サブシステムテストに関する課題は以下である。

* 1ポンプシステム（チラー冷水も変流量）になっている。
* 冷却水の変流量制御ができない。　→熱源サブシステムテストではHSS200以降は冷却水流量が50％の条件になっているが、全体システムテストでは定流量のため、全ケース100％で統一するよう矢島委員に提案済。
* link:https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-plant-equipment.html#chillerheaterabsorptiondirectfired[ChillerHeater:Absorption:DirectFired]のエラーを未解決。

WGメンバーに異存がなければ、上記は今後の課題として残しておき、次回から冷却水サブシステムテストに取り組むつもりである。


