Building objectの入力についての解説

https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-simulation-parameters.html#building[リンク]

=== Field: Building Name
建物名称は出力の利便性のために定義します。

=== Field: North Axis
建物の方位が真北から時計回りに何度回転しているかを指定できます。ただし、link:https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-thermal-zone-description-geometry.html#globalgeometryrules[GlobalGeometryRules]で「Relative」以外の座標系が使用されている場合、この入力値は無視されます。

=== Field: Terrain
サイトの地形は、建物の高さと同様に、風がどのように建物に当たるかに影響を与えます。このフィールドの有効な値を次の表に示します。

.Values for “Terrain”
[options="header"]
|====================================================
|Terrain Type Value|	Terrain Description
|Country|	Flat, Open Country
|Suburbs|	Rough, Wooded Country, Suburbs
|City|	Towns, city outskirts, center of large cities
|Ocean|	Ocean, Bayou flat country
|Urban|	Urban, Industrial, Forest
|====================================================

建物近傍の風速の計算方法についてはlink:https://bigladdersoftware.com/epx/docs/9-4/engineering-reference/outside-surface-heat-balance.html#local-wind-speed-calculation[Local Wind Speed Calculation]を参照してください。つまり、この入力によって外表面の対流熱伝達率の計算に用いる風速の計算式のパラメータが変化することになります。 

=== Warmup Convergence
次の2つのフィールドは、ウォームアップの最小日数と最大日数とともに、EnergyPlusが各ステップで収束する条件を定義します 。計算開始時に、室温は23^o^Cに、相対湿度は屋外相対湿度に初期化されます。 EnergyPlusは計算初日を最大ウォームアップ日数に達するか、収束条件が満たされるまで、繰り返し実行します。

=== Field: Loads Convergence Tolerance Value
この負荷許容値 [W]は収束条件の1つであり、ピークゾーンの冷暖房負荷の前のウォームアップ日からの変化に対して適用されます。

=== Field: Temperature Convergence Tolerance Value
この温度許容値 [^o^C]は収束条件の1つであり、ゾーン温度の前回Iterationからの変化に対して適用されます。

負荷または温度許容値のいずれかが満たされると、Simultaneous heat balance/HVAC solutionの収束に達します。

=== Field: Solar Distribution
この入力はEnergyPlusが直達日射と外表面からの反射をどのように扱うかを定義します。以下の5つの選択肢があります。

* MinimalShadowing
* FullExterior
* FullInteriorAndExterior
* FullExteriorWithReflections
* FullInteriorAndExteriorWithReflections

==== MinimalShadowing
この場合、窓とドアを除いて、外部の影はありません。ゾーンに入るすべての直達日射は床に当たると想定され、床の日射吸収率に応じて吸収されます。床で反射されたものはすべて、反射拡散日射に追加されます。これは、すべての内表面に均一に分布していると仮定されます。 ゾーンに床が存在しない場合、直達日射は、吸収率に応じてすべての内表面で吸収されます。次に、表面熱流として扱われる吸収された日射を考慮して、各表面とゾーン空気の熱収支が計算されます。

==== FullExterior, FullExteriorWithReflections
この場合、すべてのゾーンのDetached shading, wings, overhangs, and exterior surfacesによって引き起こされる外表面のShadow patternsが計算されます。MinimalShadowingと同様に、窓やドアによる影も計算されます。ゾーンに入る直達日射は、MinimalShadowingの場合と同様に扱われます。

==== FullInteriorAndExterior, FullInteriorAndExteriorWithReflections
これはFullExteriorと同じですが、すべての透過直達日射が床に当たると仮定する代わりに、プログラムは、太陽の光線を外部から投影することにより、床、壁、窓など、ゾーンの各表面に当たる直達日射量を計算します。外部の日陰面や窓のShading devicesも考慮します。 +
このオプションを用いる場合、そのゾーンが完全に面によって閉じられており、かつConvex（つまり内側に凹んだような形状はNG）である必要があります。 +
FullInteriorAndExteriorを使用する場合、プログラムは、（ゾーン内の他のウィンドウから）窓の内側に当たる直達日射が窓によって吸収される量、ゾーンに反射する量、および外側に透過する量も計算します。

==== Diffuse Radiation
外部および内部の窓を透過する拡散日射は、透過する窓とゾーン内の他のすべての熱伝達面との間の近似的な形態係数に従って分配されます。ゾーン内のすべての表面によって反射されるこの拡散日射は、室内で反射される直達日射と照明からの短波とともに、ゾーン内のすべての熱伝達面に均一に（面積および吸収率に基づいて）再分配されます。

==== Reflection calculations
注：反射計算の使用には、非常に時間がかかる場合があります。また、エラーが発生しやすいです。
 
このオプションを使用する場合、プログラムは、外表面から反射されて建物に当たる直達・拡散日射を計算します。これらの反射面は、次の3つのカテゴリーに分類されます。

. Shadowing surfaces +
これらはオブジェクトで定義するShading devicesです。

. Exterior building surfaces +
この場合、建物の1つのセクションが日射を別のセクションに反射します。

. The ground surface +
反射オプションが使用されていない場合でも、地面からの反射は計算されますが、その場合は地面は遮られていないと見なされます。つまり、建物自体または隣接する建物などの障害物による地面の影は無視されます。 反射オプションが使用されている場合、建物自体または隣接する建物による影が考慮されますが、その代わりに"View factor to ground"の入力は使用されません。

=== Field: Maximum Number of Warmup Days
このフィールドは、収束するまでにシミュレーションで使用される可能性のあるウォームアップ日数を指定します。通常、このタスクにはデフォルトの数である25で十分です。ただし、一部の複雑な建物（複雑な構造）では、さらに日数がかかる場合があります

=== Field: Minimum Number of Warmup Days
このフィールドは、EnergyPlusが収束したかどうかをチェックし、シミュレーションを開始できるようになるまでのウォームアップの最小日数を指定します。

=== AS140の入力方法に関する考察
特に判断が難しいと思われるTerrainとSolar distributionの選択について考察する。

==== Terrainの選択
AS140の本文中にサイトの場所的特徴に関する記載はないが、Normative Annex A1: Weather dataのTable A1-1に、使用する気象データを測定した気象ステーションの場所として「Flat, unobstructed」という記述がある。唯一の情報であるこの記述を正とすれば、Terrainの入力は「Country（Flat, Open Country）」が適当と考えられる。

==== Solar distributionの選択
AS140の本文中に日射計算方法についての指定はないため、Shading devicesを考慮できるFullExterior以下のオプションであれば問題ないと考えられる。 +
上記のマニュアルの説明からすると、ほとんどの場合はFullExteriorを使用することが推奨されているように読み取れる。 +
FullInteriorAndExteriorは、ゾーンが面で完全に閉じられていることと、Convexであることという大きな形状の制約がある。物理的な壁を定義せずにゾーンを区切りたいケースは現実には多くあるが、その場合はこのオプションを使用できないと思われる。 +
Reflectionの使用については計算時間やエラーについての注意書きがあることから、特別な利用目的の場合を除いて推奨していないように見える。また、AS140ではShading devices自体の特性（反射率等）を指定していないため、おそらくこのような反射計算を行うことは想定していない。 +
以上より、実際に近い精緻な計算を行うという観点に立てば、FullInteriorAndExteriorを用いることが適当と考えられるが、現実の多くのシチュエーションでFullExteriorを用いるとすれば、FullExteriorで計算することも適当ではないかと思われる。



