// Case MZN

=== Case MZA

Case MZA のモデルを作成する。Case MZNのモデルをベースとする。

==== ZoneCrossMixing

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-airflow.html#zonecrossmixing[ZoneCrossMixingクラスの作成方法, role="external", window="_blank"]


ZoneCrossMixingは、2つのゾーンがお互いに同じ量の空気を交換する場合に理想的である。
ZoneMixingと同様、EnergyPlusでは簡略化されたゾーン間の空気の流れとなる。
ZoneMixingとZoneCrossMixingの主な違いは、クロスミキシングはソースゾーンとレシーブゾーンの両方にエネルギー効果があるため、
2つのゾーンの空気質量とエネルギーバランスの両方が維持されることである。
冷蔵ゾーンについては、「ZoneRefrigerationDoorMixing」を参照のこと。
より高度な混合計算は、EnergyPlus AirflowNetworkモデルを使用すれば、HVACシステム動作の有無にかかわらず、マルチゾーンエアフローに対応できる。

ZoneCrossMixingは、1回（混合ゾーンの1つで）、2回（各ゾーンで1回）、または複数回（複数のゾーンと交換）入力できる。
各オブジェクトには、それぞれの制御条件がモデル化される。
温度差＞0.0で、ソースゾーンがレシーブゾーンよりも暖かい場合にのみ混合を行うことが望ましい場合、オブジェクトは1回入力されることがある。
これは、暖かいゾーンが冷たいゾーンの下にあり、混合が浮力によって行われる場合に当てはまる。
もし、ゾーンが隣り合っていて、開いたドアで仕切られている場合は、各ゾーンにクロスミキシングオブジェクトを入力する方が適している。
そうすれば、どちらのゾーンが暖かいかに関わらず、ゾーンの温度が温度差以上の差があれば、混合が起こる。

.ZoneCrossMixing
----
ZoneCrossMixing,
    Zone-A-B,                !- Name
    Block1:ZoneA,            !- Zone Name
    Always On,               !- Schedule Name
    Flow/Zone,               !- Design Flow Rate Calculation Method
    0.33333,                 !- Design Flow Rate {m3/s}
    ,                        !- Flow Rate per Zone Floor Area {m3/s-m2}
    ,                        !- Flow Rate per Person {m3/s-person}
    ,                        !- Air Changes per Hour {1/hr}
    Block1:ZoneB;            !- Source Zone Name


ZoneCrossMixing,
    Zone-B-C,                !- Name
    Block1:ZoneB,            !- Zone Name
    Always On,               !- Schedule Name
    Flow/Zone,               !- Design Flow Rate Calculation Method
    0.33333,                 !- Design Flow Rate {m3/s}
    ,                        !- Flow Rate per Zone Floor Area {m3/s-m2}
    ,                        !- Flow Rate per Person {m3/s-person}
    ,                        !- Air Changes per Hour {1/hr}
    Block1:ZoneC;            !- Source Zone Name
----


===== Name

ZoneCrossMixingオブジェクトの名称です。

===== Zone Name

このフィールドは空気の交換量を受け取るゾーン（ref：Zone）の名前であり、
建物内のサーマルゾーンに特定のクロスミキシング・ステートメントを割り当てます。

===== Schedule Name

このフィールドは、最大設計体積流量パラメータ（次のフィールドを参照）を修正するスケジュール（参照：スケジュール）の名前である。
0.0から1.0の間のこの分数は、設計レベルのパラメータを修正する。

===== Design Flow Rate Calculation Method

このフィールドは、次の4つのフィールドのどれが満たされるかを示すキー／選択肢フィールドであり、設計体積流量の計算方法を記述する。
キー／選択肢は以下の通り。

* Flow/Zone +
この選択では、使用される方法は、設計体積流量をそのまま挿入することになる。(Design Flow Rate に記入されなければならない）。

* Flow/Area
この選択では、使用される方法はゾーンの床面積あたりの係数となる。(Flow Rate per Zone Floor Areaフィールドが入力される必要があります)。

* Flow/Person
この選択では、使用される方法は、ゾーン内の公称人数ごとの係数となる。(一人あたりのフローフィールドが入力されている必要があります）。

* AirChanges/Hour
この選択肢では、浸透量に対する1時間あたりの空気の入れ替え回数を使用する。この係数は、ゾーン容積とともに、設計流量の決定に使用されます。(AirChanges/Hour」フィールドは必ず入力してください）。)


===== Design Flow Rate
このフィールドは、完全な設計体積流量を示す（m3/s). 
前のフィールドでは、選択肢として「flow/zone」を選択する必要がある。設計体積流量は予想される混合空気の最大量である。
設計値は、スケジュール名とユーザーが指定した係数（以下の4つの「係数」フィールド参照）によって変更される。

===== Flow Rate per Zone Floor Area
この係数（m3/s-m2)は、ゾーン面積とともに使用され、「設計体積流量」欄に記載された最大設計体積流量を決定します。
方法欄の選択は「Flow/Area」とすべきである。

===== Flow Rate per Person
この係数（m3/s-person）は、ゾーン内の名目上の（最大）居住者（人）の数とともに使用され、「設計体積流量」フィールドに記載された最大設計体積流量を決定する。
方法欄の選択は「Flow/Person」とする。

===== Air Changes per Hour
この選択により、使用される方法は、混合量に対する1時間あたりの空気の変化の数となる。この係数とゾーンボリュームを用いて設計流量を決定する。
方法の欄には "AirChanges/Hour "を選択すること。

===== Source Zone Name
このフィールドは、設計レベルおよびスケジュールフィールドで指定された量の空気を、
ゾーン名フィールドで指定されたゾーンに排気するソースゾーンの名前である。
実際には、クロスミックスされた空気が両方のゾーンに影響を与えるため、"ソース ゾーンと "レシーブゾーンは入れ替え可能である。

===== Delta Temperature
この数値は、ソースゾーンからの混合空気をレシービングゾーンに送るタイミングを制御する。
このパラメーターは温度で、単位は摂氏である。
このフィールドが正の値の場合、空気が送られてくるゾーン（「ソースゾーン」）の温度がゾーンの空気よりも「デルタ温度」が高くなければ混合は起こらない。
このフィールドがゼロの場合、空気の相対的な温度に関係なく混合が起こる。デルタ温度の負の値は許されない。

===== Delta Temperature Schedule Name
このフィールドには、ソースゾーンとレシーブゾーンの空気の乾球温度の温度差（摂氏）を時間の関数として含むスケジュール（参照：Schedule objects）の名前が含まれる。このフィールドはオプション・フィールドであり、Delta Temperatureフィールドと同じ機能を持つ。
ユーザーが有効なスケジュール名を入力した場合、このスケジュールで指定されたデルタ温度値は、デルタ温度フィールドで指定された定数値よりも優先される。

===== Minimum Zone Temperature Schedule Name
このフィールドには、時間の関数として交差混合が遮断される最低受信ゾーン温度（摂氏）を含むスケジュール（参照：Schedule objects）の名前が含まれる。
スケジュールの最小温度値は-100℃、最大値は100℃とすることができます。
このフィールドはオプションのフィールドです。このフィールドが入力されていない場合、最小ゾーン温度制御は適用されない。

===== Maximum Zone Temperature Schedule Name
このフィールドには、時間の関数として交差混合が遮断される上限の受信ゾーン温度（摂氏）を含むスケジュール（参照：Schedule objects）の名前が含まれる。
スケジュールの最大温度の値は-100℃で、最大値は100℃とすることができる。
このフィールドはオプションのフィールドです。このフィールドが入力されていない場合、最大ゾーン温度制御は適用されない。

注：クロスミキシングが遮断されたときの最大ゾーン温度は、最小ゾーン温度以上でなければならない

