// Case 650

基準ケース Case600 から暖房運転をなしとし、以下のように夜間換気を行う条件で熱負荷シミュレーションを行う。 

冷房 18:00～07:00 停止 +
    07:00～18:00 温度が 27℃より高ければ運転  +
暖房 常時停止 換気 18:00～07:00 +
換気ファン運転 07:00～18:00  +
換気ファン停止 +

換気ファン風量は、Case600 で規定したすきま風とは別に、1703.16 m3 /h を与える。 +
ファン発熱による影響は考慮しない。 +


==== ZoneControl:Thermostat

解説は https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-controls-thermostats.html#zonecontrolthermostat[<bigladder>, role="external", window="_blank"]。

.ZoneControl:Thermostat　
----
ZoneControl:Thermostat,
    Zone 1 Thermostat,                !- Name
    Zone1,                            !- Zone or ZoneList Name
    Zone Control Type Sched,          !- Control Type Schedule Name
    ThermostatSetpoint:SingleCooling, !- Control 1 Object Type
    Cooling Setpoints;                !- Control 1 Name
----

===== Control 1 Object Type

* コントロールタイプの種類を次の4つの選択肢から選択します。

** ThermostatSetpoint:SingleHeating　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-controls-thermostats.html#thermostatsetpointsingleheating[<bigladder>, role="external", window="_blank"]
** ThermostatSetpoint:SingleCooling　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-controls-thermostats.html#thermostatsetpointsinglecooling[<bigladder>, role="external", window="_blank"]
** ThermostatSetpoint:SingleHeatingOrCooling　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-controls-thermostats.html#thermostatsetpointsingleheatingorcooling[<bigladder>, role="external", window="_blank"]
** ThermostatSetpoint:DualSetpoint　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-controls-thermostats.html#thermostatsetpointdualsetpoint[<bigladder>, role="external", window="_blank"]

今回は、ThermostatSetpoint:SingleCooling　を選択します。


==== ThermostatSetpoint:SingleCooling

解説は https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-controls-thermostats.html#thermostatsetpointsinglecooling[<bigladder>, role="external", window="_blank"]。

.ThermostatSetpoint:SingleCooling
----
ThermostatSetpoint:SingleCooling,
    Cooling Setpoints,       !- Name
    Cooling Setpoints;       !- Setpoint Temperature Schedule Name
----


==== Schedule:Day:Hourly

室温制御方法について、Case 600は 4 であったが、Case650では 2 に変更する。
そして、冷房設定温度について、夜間に空調が動かないように設定温度を 99度　に変更する。

.Schedule:Day:Hourly　室温制御方法
----
Schedule:Day:Hourly,
    Control Type All Days,   !- Name
    Control Type,            !- Schedule Type Limits Name
    2,                       !- Hour 1
    2,                       !- Hour 2
    2,                       !- Hour 3
    2,                       !- Hour 4
    2,                       !- Hour 5
    2,                       !- Hour 6
    2,                       !- Hour 7
    2,                       !- Hour 8
    2,                       !- Hour 9
    2,                       !- Hour 10
    2,                       !- Hour 11
    2,                       !- Hour 12
    2,                       !- Hour 13
    2,                       !- Hour 14
    2,                       !- Hour 15
    2,                       !- Hour 16
    2,                       !- Hour 17
    2,                       !- Hour 18
    2,                       !- Hour 19
    2,                       !- Hour 20
    2,                       !- Hour 21
    2,                       !- Hour 22
    2,                       !- Hour 23
    2;                       !- Hour 24
----

.Schedule:Day:Hourly　冷房設定温度
----
Schedule:Day:Hourly,
    Zone Cooling Setpoint All Days,  !- Name
    Temperature,             !- Schedule Type Limits Name
    99.,                     !- Hour 1
    99.,                     !- Hour 2
    99.,                     !- Hour 3
    99.,                     !- Hour 4
    99.,                     !- Hour 5
    99.,                     !- Hour 6
    99.,                     !- Hour 7
    27.,                     !- Hour 8
    27.,                     !- Hour 9
    27.,                     !- Hour 10
    27.,                     !- Hour 11
    27.,                     !- Hour 12
    27.,                     !- Hour 13
    27.,                     !- Hour 14
    27.,                     !- Hour 15
    27.,                     !- Hour 16
    27.,                     !- Hour 17
    27.,                     !- Hour 18
    99.,                     !- Hour 19
    99.,                     !- Hour 20
    99.,                     !- Hour 21
    99.,                     !- Hour 22
    99.,                     !- Hour 23
    99.;                     !- Hour 24
----

もしくは、以下のように 制御スケジュールを 0 とすれば、無制御（非空調）となる。
この場合は、室温設定値を変更する必要はない。

.Schedule:Day:Hourly　室温制御方法
----
Schedule:Day:Hourly,
    Control Type All Days,   !- Name
    0,                       !- Hour 1
    0,                       !- Hour 2
    0,                       !- Hour 3
    0,                       !- Hour 4
    0,                       !- Hour 5
    0,                       !- Hour 6
    0,                       !- Hour 7
    2,                       !- Hour 8
    2,                       !- Hour 9
    2,                       !- Hour 10
    2,                       !- Hour 11
    2,                       !- Hour 12
    2,                       !- Hour 13
    2,                       !- Hour 14
    2,                       !- Hour 15
    2,                       !- Hour 16
    2,                       !- Hour 17
    2,                       !- Hour 18
    0,                       !- Hour 19
    0,                       !- Hour 20
    0,                       !- Hour 21
    0,                       !- Hour 22
    0,                       !- Hour 23
    0;                       !- Hour 24
----


==== ZoneInfiltration:DesignFlowRate

Design Flow Rateを、すきま風（ 0.018 m3/s ）と換気風量（ 0.4731 m3/s ）の合計値 0.4911 に変更する。
Schedule Name を Sch 2 に変更する。

.すきま風　
----
ZoneInfiltration:DesignFlowRate,
    Infil_1,                 !- Name
    Zone1,                   !- Zone or ZoneList Name
    Sch 2,                   !- Schedule Name
    Flow/Zone,               !- Design Flow Rate Calculation Method
    0.4911,                   !- Design Flow Rate {m3/s}
    ,                        !- Flow per Zone Floor Area {m3/s-m2}
    ,                        !- Flow per Exterior Surface Area {m3/s-m2}
    ,                        !- Air Changes per Hour {1/hr}
    1,                       !- Constant Term Coefficient
    0,                       !- Temperature Term Coefficient
    0,                       !- Velocity Term Coefficient
    0;                       !- Velocity Squared Term Coefficient
----

以下のスケジュールを設定する。

.Schedule:Year
----
Schedule:Year,
    Sch 2,                   !- Name
    Fraction,                !- Schedule Type Limits Name
    Week Sch 2,              !- Schedule:Week Name 1
    1,                       !- Start Month 1
    1,                       !- Start Day 1
    12,                      !- End Month 1
    31;                      !- End Day 1
----

.Schedule:Week:Daily
----
Schedule:Week:Daily,
    Week Sch 2,              !- Name
    Day Sch 2,               !- Sunday Schedule:Day Name
    Day Sch 2,               !- Monday Schedule:Day Name
    Day Sch 2,               !- Tuesday Schedule:Day Name
    Day Sch 2,               !- Wednesday Schedule:Day Name
    Day Sch 2,               !- Thursday Schedule:Day Name
    Day Sch 2,               !- Friday Schedule:Day Name
    Day Sch 2,               !- Saturday Schedule:Day Name
    Day Sch 2,               !- Holiday Schedule:Day Name
    Day Sch 2,               !- SummerDesignDay Schedule:Day Name
    Day Sch 2,               !- WinterDesignDay Schedule:Day Name
    Day Sch 2,               !- CustomDay1 Schedule:Day Name
    Day Sch 2;               !- CustomDay2 Schedule:Day Name
----

7時から18時までは、すきま風分（0.018 / 0.4911 = 0.03665241）の比率とする。

.Schedule:Day:Hourly
----
Schedule:Day:Hourly,
    Day Sch 2,               !- Name
    Fraction,                !- Schedule Type Limits Name
    1,                       !- Hour 1
    1,                       !- Hour 2
    1,                       !- Hour 3
    1,                       !- Hour 4
    1,                       !- Hour 5
    1,                       !- Hour 6
    1,                       !- Hour 7
    0.03665241,              !- Hour 8
    0.03665241,              !- Hour 9
    0.03665241,              !- Hour 10
    0.03665241,              !- Hour 11
    0.03665241,              !- Hour 12
    0.03665241,              !- Hour 13
    0.03665241,              !- Hour 14
    0.03665241,              !- Hour 15
    0.03665241,              !- Hour 16
    0.03665241,              !- Hour 17
    0.03665241,              !- Hour 18
    1,                       !- Hour 19
    1,                       !- Hour 20
    1,                       !- Hour 21
    1,                       !- Hour 22
    1,                       !- Hour 23
    1;                       !- Hour 24
----