// Case 900J シリーズ

=== Case900-J1-1

==== Material, Construction

.Material 外壁
----
Construction,
    Wall-configure,          !- Name
    WOODSIDING-9mm,          !- Outside Layer
    CONCRATE-100mm,          !- Layer 2
    FIBERGLASS-61.5mm;       !- Layer 3
----

=== Case900-J1-2

==== Material, Construction

空気層の指定方法は https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-surface-construction-elements.html#materialairgap[<bigladder>, role="external", window="_blank"] をご覧下さい。

.Material:AirGap　外壁
----
Material:AirGap,
    AirGap,                  !- Name
    0.07;                    !- Thermal Resistance {m2-K/W}
----

.Material, Construction 外壁
----
Material,
    TILE-10mm,               !- Name
    Rough,                   !- Roughness
    0.010,                   !- Thickness {m}
    1.300,                   !- Conductivity {W/m-K}
    2400.0,                  !- Density {kg/m3}
    833.00,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance

Material,
    CEMENT-25mm,             !- Name
    Rough,                   !- Roughness
    0.025,                   !- Thickness {m}
    1.500,                   !- Conductivity {W/m-K}
    2000.0,                  !- Density {kg/m3}
    800.00,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance

Material,
    CONCRATE-150mm,          !- Name
    Rough,                   !- Roughness
    0.1500,                  !- Thickness {m}
    1.600,                   !- Conductivity {W/m-K}
    2300.00,                 !- Density {kg/m3}
    870.00,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance

Material,
    INSULATIONBOARD-25mm,    !- Name
    Rough,                   !- Roughness
    0.025,                   !- Thickness {m}
    0.040,                   !- Conductivity {W/m-K}
    25.00,                   !- Density {kg/m3}
    1320.0,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance

Material:AirGap,
    AirGap,                  !- Name
    0.07;                    !- Thermal Resistance {m2-K/W}

Material,
    GYPSUMBOARD-8mm,         !- Name
    Rough,                   !- Roughness
    0.008,                   !- Thickness {m}
    0.220,                   !- Conductivity {W/m-K}
    750.0,                   !- Density {kg/m3}
    1107.0,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance


!- 外壁
Construction,
    Wall-configure,         !- Name
    TILE-10mm,              !- Outside Layer
    CEMENT-25mm,            !- Layer 2
    CONCRATE-150mm,         !- Layer 3
    INSULATIONBOARD-25mm,   !- Layer 4
    AirGap,                 !- Layer 5
    GYPSUMBOARD-8mm;        !- Layer 6
----

.Material, Construction 屋根
----
Material,
    CONCRATE-60mm,           !- Name
    Rough,                   !- Roughness
    0.6000,                  !- Thickness {m}
    1.600,                   !- Conductivity {W/m-K}
    2300.00,                 !- Density {kg/m3}
    870.00,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance

Material,
    INSULATIONBOARD-50mm,    !- Name
    Rough,                   !- Roughness
    0.050,                   !- Thickness {m}
    0.040,                   !- Conductivity {W/m-K}
    25.00,                   !- Density {kg/m3}
    1320.0,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance

Material,
    CEMENT-15mm,             !- Name
    Rough,                   !- Roughness
    0.015,                   !- Thickness {m}
    1.500,                   !- Conductivity {W/m-K}
    2000.0,                  !- Density {kg/m3}
    800.00,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance

Material,
    ASPHALT-5mm,             !- Name
    Rough,                   !- Roughness
    0.005,                   !- Thickness {m}
    0.110,                   !- Conductivity {W/m-K}
    1000.0,                  !- Density {kg/m3}
    920.00,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance

Material,
    GYPSUMBOARD-10mm,        !- Name
    Rough,                   !- Roughness
    0.010,                   !- Thickness {m}
    0.220,                   !- Conductivity {W/m-K}
    750.0,                   !- Density {kg/m3}
    1107.0,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance

Material,
    ASBESTOS-12mm,           !- Name
    Rough,                   !- Roughness
    0.012,                   !- Thickness {m}
    0.064,                   !- Conductivity {W/m-K}
    350.0,                   !- Density {kg/m3}
    829.0,                   !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance

!- 屋根
Construction,
    Roof_configure,          !- Name
    CONCRATE-60mm,           !- Outside Layer
    INSULATIONBOARD-50mm,    !- Layer 2
    CEMENT-15mm,             !- Layer 3
    ASPHALT-5mm,             !- Layer 4
    CEMENT-15mm,             !- Layer 5
    CONCRATE-150mm,          !- Layer 6
    AirGap,                  !- Layer 7
    GYPSUMBOARD-10mm,        !- Layer 8
    ASBESTOS-12mm;           !- Layer 9
----

=== Case900-J2

==== Schedule

Case 900-J1-2 をベースに　夜間18~8時　の空調を停止する。

.Schedule:Day:Hourly
----
Schedule:Day:Hourly,
    Control Type All Days,   !- Name
    Control Type,            !- Schedule Type Limits Name
    0,                       !- Hour 1  0:00:01〜1:00:00
    0,                       !- Hour 2
    0,                       !- Hour 3
    0,                       !- Hour 4
    0,                       !- Hour 5
    0,                       !- Hour 6
    0,                       !- Hour 7
    0,                       !- Hour 8
    4,                       !- Hour 9
    4,                       !- Hour 10
    4,                       !- Hour 11
    4,                       !- Hour 12
    4,                       !- Hour 13
    4,                       !- Hour 14
    4,                       !- Hour 15
    4,                       !- Hour 16
    4,                       !- Hour 17
    4,                       !- Hour 18  17:00:01〜18:00:00
    0,                       !- Hour 19
    0,                       !- Hour 20
    0,                       !- Hour 21
    0,                       !- Hour 22
    0,                       !- Hour 23
    0;                       !- Hour 24
----


=== Case900-J3

==== WindowMaterial:Blind

ブラインドの追加を行います。 +
ブラインドの入力方法は　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-surface-construction-elements.html#windowmaterialblind[<bigladder>, role="external", window="_blank"] をご覧下さい。

このオブジェクトは、平らで等間隔のスラットからなる窓用ブラインドの特性を指定します。完全な拡散板としてモデル化されているウィンドウシェードとは異なり、ウィンドウブラインドには、スラットの角度と日射の入射角に強く依存する日射および可視光線の透過・反射特性があります。一般的な窓用ブラインドの特性を含むWindowMaterial:BlindのEnergyPlusリファレンスデータセットがあります。

ブラインドは、窓の内側（「室内ブラインド」）、窓の外側（「室外ブラインド」）、または2枚のガラスの間（「ガラス間ブラインド」）に設置することができます。ブラインドが設置されているとき、ブラインドは仕切りを含めて窓のガラス部分をすべて覆うと仮定しますが、窓枠がある場合はそれは覆いません。ブラインドの平面はグレージングと平行であると仮定します。ブラインドが格納されているときは、窓を一切覆わないものとします。ブラインドのサポートストリング、テープ、ロッドによる太陽熱の影響は無視します。スラットの曲率は無視されます。

.WindowMaterial:Blind
----
WindowMaterial:Blind,
    Blind,                   !- Name
    Horizontal,              !- Slat Orientation
    0.025,                   !- Slat Width {m}
    0.0225,                  !- Slat Separation {m}
    0.00013,                 !- Slat Thickness {m}
    3,                       !- Slat Angle {deg}
    200,                     !- Slat Conductivity {W/m-K}
    0,                       !- Slat Beam Solar Transmittance
    0.66,                    !- Front Side Slat Beam Solar Reflectance
    0.66,                    !- Back Side Slat Beam Solar Reflectance
    0,                       !- Slat Diffuse Solar Transmittance
    0.66,                    !- Front Side Slat Diffuse Solar Reflectance
    0.66,                    !- Back Side Slat Diffuse Solar Reflectance
    0,                       !- Slat Beam Visible Transmittance
    0.873,                   !- Front Side Slat Beam Visible Reflectance
    0.873,                   !- Back Side Slat Beam Visible Reflectance
    0,                       !- Slat Diffuse Visible Transmittance
    0.873,                   !- Front Side Slat Diffuse Visible Reflectance
    0.873,                   !- Back Side Slat Diffuse Visible Reflectance
    0,                       !- Slat Infrared Hemispherical Transmittance
    0.9,                     !- Front Side Slat Infrared Hemispherical Emissivity
    0.9,                     !- Back Side Slat Infrared Hemispherical Emissivity
    0.15,                    !- Blind to Glass Distance {m}
    0.033,                   !- Blind Top Opening Multiplier
    0.033,                   !- Blind Bottom Opening Multiplier
    0.033,                   !- Blind Left Side Opening Multiplier
    0.033,                   !- Blind Right Side Opening Multiplier
    3,                       !- Minimum Slat Angle {deg}
    165;                     !- Maximum Slat Angle {deg}
----

===== Slat Angle

グレージングの外側の法線とスラットの外側の法線の間の角度（度）で、外側の法線がスラットの前面から離れたところを指している。図 6 を参照してください。

ブラインドの WindowShadingControl に Type of Slat Angle Control for Blinds = FixedSlatAngle がある場合、スラットの角度は "Slat Angle" に固定されます。

Type of Slat Angle Control for Blinds = BlockBeamSolarの場合は、プログラムが自動的にスラットの角度を調整し、太陽光線を遮断します。この場合、「スラット角度」の値は、ブラインドが設置されていて、ブラインドに日射が入射していない場合にのみ使用されます。

ブラインドのスラット角制御のタイプ＝ScheduledSlatAngleの場合、スラット角は可変である。この場合、「スラットアングル」は適用されず、フィールドは空白にしてください。

Type of Slat Angle Control for Blinds = FixedSlatAngleで、「スラット角度」がスラット幅、スラット間隔、スラット厚みで許容される最小値よりも小さいか、最大値よりも大きい場合、スラット角度は対応する最小値または最大値にリセットされ、警告が発行されます。


==== WindowShadingControl

ブラインド制御方法を入力します。 +
入力方法は　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-thermal-zone-description-geometry.html#windowpropertyshadingcontrol[<bigladder>, role="external", window="_blank"] をご覧下さい。

.WindowShadingControl
----
WindowShadingControl,
    Shading Control 1,         !- Name
    Zone1,                   !- Zone Name
    1,                       !- Shading Control Sequence Number
    InteriorBlind,           !- Shading Type
    ,                        !- Construction with Shading Name
    AlwaysOn,                !- Shading Control Type
    ,                        !- Schedule Name
    ,                        !- Setpoint {W/m2, W or deg C}
    No,                      !- Shading Control Is Scheduled
    No,                      !- Glare Control Is Active
    Blind,                   !- Shading Device Material Name
    FixedSlatAngle,          !- Type of Slat Angle Control for Blinds
    ,                        !- Slat Angle Schedule Name
    ,                        !- Setpoint 2 {W/m2 or deg C}
    ,                        !- Daylighting Control Object Name
    Group,                   !- Multiple Surface Control Type
    Window_S1;               !- Fenestration Surface 1 Name
----

.WindowShadingControl
----
WindowShadingControl,
    Shading Control 2,         !- Name
    Zone1,                   !- Zone Name
    1,                       !- Shading Control Sequence Number
    InteriorBlind,           !- Shading Type
    ,                        !- Construction with Shading Name
    AlwaysOn,                !- Shading Control Type
    ,                        !- Schedule Name
    ,                        !- Setpoint {W/m2, W or deg C}
    No,                      !- Shading Control Is Scheduled
    No,                      !- Glare Control Is Active
    Blind,                   !- Shading Device Material Name
    FixedSlatAngle,          !- Type of Slat Angle Control for Blinds
    ,                        !- Slat Angle Schedule Name
    ,                        !- Setpoint 2 {W/m2 or deg C}
    ,                        !- Daylighting Control Object Name
    Group,                   !- Multiple Surface Control Type
    Window_S2;               !- Fenestration Surface 1 Name
----

===== Shading Control Sequence Number

複数の WindowShadingControl オブジェクトが同じゾーンで使用されている場合、ウィンドウ シェードを展開する順序をこのフィールドで設定することができます。最初の WindowShadingControl は 1 とし、後続の WindowShadingControl は 2、3 などとします。これは通常、Multiple Surface Control TypeフィールドがGroupに設定されている場合に、ウィンドウのグループを特定の順序で制御するために使用されます。


===== Shading Type

遮光装置の種類です。選択肢は以下の通りです。

* InteriorShade: 拡散するシェードがウィンドウの内側にあります。(シェーディングされたConstructionでは、シェーディング レイヤーがWindowMaterial:Shadeである必要があります)。

* ExteriorShade: 拡散するシェードがウィンドウの外側にあります。(シェーディングされたコンストラクションでは、シェーディングレイヤーはWindowMaterial:Shadeである必要があります。)

* BetweenGlassShade: 拡散シェードは2つのガラス層の間にあります。(シェーディングされたコンストラクションでは、シェーディング層はWindowMaterial:Shadeでなければならない) このシェードタイプは、二重ガラスと三重ガラスにのみ許可されています。トリプルガラスの場合、シェードは2つの内側のガラス層の間になければなりません。

* ExteriorScreen: 窓の外側に設置された防虫スクリーン。(Shaded Constructionでは、遮光層はWindowMaterial:Screenでなければなりません。)

* InteriorBlind: ベネチアンブラインドのようなスラットタイプの遮光装置が窓の内側にある。(遮光構造では、遮光層はWindowMaterial:Blindでなければならない)

* ExteriorBlind: スラットタイプの遮光装置が窓の外側にあります。(遮光構造の場合、遮光層はWindowMaterial:Blindでなければならない)

* BetweenGlassBlind: スラットタイプの遮光装置が2つのガラス層の間にある場合。(遮光構造では、遮光層はWindowMaterial:Blindでなければならない) この遮光タイプは、ペアガラスとトリプルガラスにのみ使用できます。トリプルガラスの場合、ブラインドは2つの内側のガラス層の間になければなりません。

* SwitchableGlazing: 窓ガラスを暗くするなど、ガラスの特性を変えることで遮光を行います。


===== Construction with Shading Name

シェーディングが行われているウィンドウのコンストラクションの名前です。シェーディングデバイスのプロパティは、そのコンストラクションで参照されるシェーディングマテリアルによって与えられます（参照：Construction, WindowMaterial:Shade, WindowMaterial:Screen and WindowMaterial:Blind）。Shading Type = SwitchableGlazingの場合、これは完全にスイッチされた（最も暗い）状態のウィンドウに対応するコンストラクションの名前です。

シェーディングタイプ＝BetweenGlassShade、BetweenGlassBlind、またはSwitchableGlazingの場合は、「シェーディングを持つコンストラクションの名前」を指定することが必要です。その他の遮光タイプの場合は、代わりに「遮光装置の材料名」を指定することができます（以下参照）。


===== Shading Control Type

遮光装置の制御方法を指定するもので、遮光装置を「オン」にするか「オフ」にするかを決定するものである。ブラインド、スクリーン、シェードの場合、装置が「オン」のときは、窓の枠を除くすべての部分を覆うものとし、装置が「オフ」のときは、窓を一切覆わないものとする（「オン」でも「オフ」でも、遮光装置は窓がある壁を一切覆わないものとする）。

スイッチ可能なグレージングの場合、「オン」はグレージングが完全にスイッチされた状態であることを意味し、「オフ」はスイッチされていない状態であることを意味します。例えば、エレクトロクロミックグレージングの場合、「オン」はグレージングが最も暗い状態であることを意味し、「オフ」は最も明るい状態であることを意味します。

シェーディングコントロールタイプの選択肢は以下の通りです。SetPointが適用される場合、その単位は括弧内に示されています。

* AlwaysOn: シェーディングは常にオンです。

* AlwaysOff: シェーディングは常にオフです。


===== Type of Slat Angle Control for Blinds

Shading Type = InteriorBlind、ExteriorBlind、BetweenGlassBlindにのみ適用されます。スラットの角度をどのように制御するかを指定します。選択肢は、FixedSlatAngle、ScheduledSlatAngle、BlockBeamSolarです。

FixedSlatAngle（デフォルト）の場合、スラットの角度は、Name of Construction with Shadingで指定されたコンストラクションに含まれる、またはMaterial Name of Shading Deviceで指定されたWindowMaterial:Blindに入力された値に固定されます。

ScheduledSlatAngleの場合、スラットの角度は、後述の「スラット角度のスケジュール名」で指定されたスケジュールに従って変化する。

BlockBeamSolarの場合、タイムステップごとにスラットの角度が設定され、ビームソーラーの放射が遮断されます。窓にビームソーラーがない場合、スラット角度は、Name of Construction with Shadingで指定されたコンストラクションに含まれる、またはMaterial Name of Shading Deviceで指定されたWindowMaterial:Blindに入力された値に設定されます。BlockBeamSolarオプションは、ビームソーラーが窓に入射するのを防ぎ、ビームが作業面に当たると不要なグレアが発生する可能性があるが、同時に昼光のための最適に近い間接放射を可能にする。

===== Multiple Surface Control Type

フィールドには2つのオプションがあります。

* Sequential: 次のリストに記載されている窓ガラスを、指定された順序で個別に制御する。

* Group: フェネトレーションサーフェスのリスト全体を同時に制御し、グレアコントロールが必要な場合は、ウィンドウシェードのグループ全体を同時に展開します。

