// Error

=== EnergyPlusにおけるErrorの取り扱い

==== Errorの重大さによる分類
link:https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/errors.html#errors[bigladder:Input Output Reference]

EnergyPlusを実行した結果、出力ファイルの1つである「***.err」に3段階のエラー（Warning, Severe, Fatal）が出力される。エラーのレベルと求められるアクションについて下表に示す。

.EnergyPlusにおけるErrorの分類
[options="header"]
|======================================
| Error Level | Action
| Warning | Take note
| Severe | Should fix
| Fatal | Program will abort
|======================================

==== Errorの実行プロセスによる分類
link:https://bigladdersoftware.com/epx/docs/9-4/tips-and-tricks-using-energyplus/error-messages-details.html#error-messages-details[bigladder:Tips and Tricks]

エラーメッセージは、EnergyPlusの以下の5段階のプロセスから生成される。

* Input Processing (comparing IDF fields/values to IDD requirements)

* GetInput for each module (further checking for correct values from the IDF)

* Sizing operations

* Warmup operations

* Simulation of the environments


以下の例のように、errファイルではプロセスに応じてエラーが集計される。
```
************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
************* EnergyPlus Completed Successfully-- 1 Warning; 0 Severe Errors; Elapsed Time = 00hr 00min  6.58sec
```

==== Preprocessorからのエラーメッセージ
link:https://bigladdersoftware.com/epx/docs/9-4/tips-and-tricks-using-energyplus/example-error-messages-for-preprocessors.html#example-error-messages-for-preprocessors[bigladder:Tips and Tricks]

すべてのPreprocessorプログラムは、検出したエラーに対してOutput：PreprocessorMessageオブジェクトを生成する。これらのエラーを理解するには、実際のPreprocessorプログラムのドキュメントを参照する必要がある場合がある。 Preprocessorからのエラーメッセージは、errファイルの最初に表示される。メッセージの形式は、<objectname>（つまり、Output：Preprocessormessage）、引用符で囲まれたプログラム名（たとえば、EPMacro）、そしてメッセージの文字列（Warning、Severe、Fatal）である。 Fatalの場合、EnergyPlusはすべてのエラーメッセージを生成した後に実行を中止する。

===== Warningの例
```
Output:PreprocessorMessage = "EPXMLPreProc2" has the following Warning conditions:
   **   ~~~   ** Problem with the width for requested floor area and
   **   ~~~   ** perimeter depth.  Reduced perimeter depth from 4.57
   **   ~~~   ** to 3.656 to accommodate perimeter and core layout
```

===== Severeの例
```
Output:PreprocessorMessage = "EPMacro" has the following Severe conditions:
   **   ~~~   ** at approximately input line number = 200: column = 11
   **   ~~~   ** cannot find/read include file
   **   ~~~   ** symbol = HVAC3ZoneMat-Const.imf
   **   ~~~   ** refer to <file>.epmdet for details.
```

==== Input Pocessorからのエラーメッセージ
link:https://bigladdersoftware.com/epx/docs/9-4/tips-and-tricks-using-energyplus/example-error-messages-for-the-input.html#example-error-messages-for-the-input-processor[bigladder:Tips and Tricks]

InputProcessorはEnergyPlusプログラムの一部であり、入力ファイルをスキャンし、IDD（Input Data Dictionary）の要件と照合する。InputProcessorのエラーはIPから始まる文字列で表示される。

===== Warningの例

* 必須項目のうち入力されていないものがある場合（デフォルト値が入力される）
```
IP: Note -- Some missing fields have been filled with defaults. See the audit output file for details.
```

===== Severeの例

* オブジェクトの入力フィールドの途中でコンマではなくセミコロン（そのオブジェクトの最終ライン）が入力されている場合
```
IP: IDF line~345 Did not find "UNTIL: 22:00" in list of Objects
```

* 必須オブジェクトである「BUILDING」が定義されていない場合
```
IP: No items found for Required Object = BUILDING
IP: Required Object = "BUILDING" not found in IDF.
```

* IDDのバージョンが一致していない場合
```
IP: Possible incorrect IDD File
IDD Version:"IDD\_Version xxx"
Possible Invalid Numerics or other problems
```

===== Fatalの例

Fatalエラーのメッセージは上記のSevereエラーの結果として表示されるようである。
```
IP: Errors occurred on processing IDF file. Preceding condition(s) cause termination.
```

==== Module GetInputからのエラーメッセージ
link:https://bigladdersoftware.com/epx/docs/9-4/tips-and-tricks-using-energyplus/example-error-messages-from-module-getinput.html#example-error-messages-from-module-getinput-routines[bigladder:Tips and Tricks]

シミュレーションが開始されると、各モジュールが呼び出され、入力ファイルから値を取得する。これらは通常、GetInputルーチンと呼ばれる。IDDの制限では完全に記述できないエラーチェックを入力に対して追加で行い、さらに、オブジェクトが別のオブジェクトに対して与える可能性のある影響も考慮する。

===== Warningの例

* 地盤温度の入力が推奨範囲を超えている場合
```
Site:GroundTemperature:BuildingSurface: Some values fall outside the range of 15-25C.
These values may be inappropriate.  Please consult the Input Output Reference for more details.
```

* IDF（入力ファイル）で指定した立地情報とEPW（気象データファイル）に含まれる立地情報に齟齬がある場合
```
Weather file location will be used rather than entered Location object.
..Location object = ATLANTA
..Weather File Location = Tampa International Ap FL USA TMY3 WMO# = 722110
..due to location differences, Latitude difference = [5.68] degrees, Longitude difference = [1.89] degrees.
..Time Zone difference = [0.0] hour(s), Elevation difference = [98.10] percent, [309.00] meters.
```

* 求めている出力に対して必要な入力が足りていない場合
```
GetPollutionFactorInput: Requested reporting for Carbon Equivalent Pollution, but insufficient information is entered.
```

* 外壁ではないSurfaceにSunExposedが指定されている場合
```
BuildingSurface:Detailed = "SURF:xyz", Sun Exposure = "SUNEXPOSED".
 ..This surface is not exposed to External Environment.  Sun exposure has no effect.
```

* 内壁の両側（両ゾーンから定義する）で面積が一致していない場合
```
GetSurfaceData: InterZone Surface Areas do not match as expected and might not satisfy conservation of energy:
   Area = 1.4E-002 in Surface = 319767, Zone = 2PAV_CONDIC_LOJA_D
   Area = 67.0 in Surface = 6C0708, Zone = 3PAV_CONDIC_TEATRO_G
```

* 内壁の両側で角度が一致していない場合
```
GetSurfaceData: InterZone Surface Azimuths do not match as expected.
   Azimuth = 270.0, Tilt = 90.0, in Surface = 319767, Zone = 2PAV_CONDIC_LOJA_D
   Azimuth = 180.0, Tilt = 90.0, in Surface = 6C0708, Zone = 3PAV_CONDIC_TEATRO_G
..surface class of base surface = Wall
```

* 床や屋根の傾斜角がおかしい場合
```
GetVertices: Floor is upside down! Tilt angle = [0.0], should be near 180, Surface = "ROOM302-FLOOR", in Zone = "ROOM302".
Automatic fix is attempted.

GetVertices: Roof is upside down! Tilt angle = [180.0], should be near 0, Surface = "ROOM302-CEILING", in Zone = "ROOM302".
Automatic fix is attempted.
```

* 極めて大きい内部発熱が指定されている場合
```
GetInternalHeatGains: Zone = "02AO_FCU04_AN" occupant density is extremely high.
Occupant Density = [14] person/m2.
Occupant Density = [7.000E-002] m2/person. Problems in Temperature Out of Bounds may result.
```

* Surfaceを構成する2点間の距離が極めて小さい場合（2つのうち1つが除外される）
```
GetVertices: Distance between two vertices < .01, possibly coincident. for Surface = 1%PIANOINTERRATO:UFFICI_WALL_3_0_1, in Zone = 1%PIANOINTERRATO:UFFICI
Vertex [2] = (-53.99,5.86,0.50)
Vertex [1] = (-53.99,5.86,0.51)
Dropping Vertex [2].
```

* ゾーンの形状がConvexでない場合
```
CheckConvexity: Surface = "ZN001:ROOF001" is non-convex.
```

===== Severeの例

* Subsurfaceの構成点がBase surfaceと逆の順番（時計回りか反時計周りか）で指定されている場合
```
GetSurfaceData: Some Outward Facing angles of subsurfaces differ significantly from base surface.
...use Output:Diagnostics,DisplayExtraWarnings; to show more details on individual surfaces.

GetSurfaceData: Outward facing angle [95.5] of subsurface = "WL2-1" significantly different than
..facing angle [275.5] of base surface = WEST WALL 2 Tilt = 90.0
..surface class of base surface = Wall
```

* No massの材料のみで建物が構成されている場合
```
This building has no thermal mass which can cause an unstable solution.
Use Material object for all opaque material definitions except very light insulation layers.
```

* Surfaceを構成する2点間の距離が極めて小さい場合（頂点の数が3点未満になるためその頂点を除外できない）
```
GetVertices: Distance between two vertices < .01, possibly coincident. for Surface = 1%PIANOINTERRATO:UFFICI_WALL_3_0_1, in Zone = 1%PIANOINTERRATO:UFFICI
Vertex [3] = (-44.82,-12.14,0.51)
Vertex [2] = (-44.82,-12.14,0.50)
Cannot Drop Vertex [3].
Number of Surface Sides at minimum.
```

* 日陰面となるSurfaceがConvexでない場合
```
DetermineShadowingCombinations: Surface = "0%VESPAIO:ZONA1\_ROOF\_1\_6\_0" is a receiving surface and is non-convex.
...Shadowing values may be inaccurate. Check .shd report file for more surface shading details
```

===== Fatalの例

このカテゴリーのSevereエラーはたいていFatalエラーにつながり、シミュレーションは途中で終了する。

==== SizingとSimulationからのエラーメッセージ
link:https://bigladdersoftware.com/epx/docs/9-4/tips-and-tricks-using-energyplus/example-error-messages-during-sizing.html#example-error-messages-during-sizing-and-simulation[bigladder:Tips and Tricks]

===== Warningの例

* 熱負荷がゼロのゾーンがある場合
```
Calculated design cooling load for zone = B1AE_FCU02_AN is zero.
Check Sizing:Zone and ZoneControl:Thermostat inputs.

Calculated design heating load for zone = B1AE\_FCU02\_AN is zero.
Check Sizing:Zone and ZoneControl:Thermostat inputs.
```

===== Severeの例

* 温度があるレンジを超えている場合
```
Temperature (high) out of bounds (206.82] for zone = "ZONE 1", for surface = "SOUTH WALL"
During Warmup & Sizing, Environment = ALEXANDRIA ESLER REGIONAL AP ANN HTG 99.6% CONDNS DB, at Simulation time = 12/21 01:00 - 01:04
Zone = "ZONE 1", Diagnostic Details:
...Internal Heat Gain [155.557] W/m2
...Infiltration/Ventilation [3.500E-002] m3/s
...Mixing/Cross Mixing [0.000] m3/s
...Zone is part of HVAC controlled system.
```

===== Fatalの例

Severeエラーの数などが表示される。

```
EnergyPlus has exited due to the reason stated above
...Summary of Errors that led to program termination:
..... Reference severe error count = 11
..... Last severe error = Temperature (high) out of bounds (210.11] for zone = "ZONE 1", for surface = "ROOF1"
```

==== EnergyPlusのErrorに対する考え方についての考察
上記より、建物側（負荷計算）に関するエラーは多く定義されている印象を受ける。しかし、システム側については参照できるドキュメント類からエラーの定義について十分確認できなかった。オブジェクトによってはユーザー自ら温度や流量などの上下限値を指定するものある。

link:https://bigladdersoftware.com/epx/docs/9-4/module-developer/input-services.html#rangecheck[Guide for Module Developers]によればRangeCheckというルーチンがあるようだが、具体的にどこで使われているのか、レンジをどのように決めているかについては記載が見当たらない。

例えば冷却塔では、UA値（伝熱係数×伝熱面積）は0〜3000,000W/Kの範囲で入力することとlink:https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-condenser-equipment.html#group----condenser-equipment[マニュアル]に記載されているが、多くの入力項目に対してこのような範囲が明示されているわけではない。

冷却塔のソースコード（CoolTower.cc）を見てみると、以下のような上下限値が直接記述されていたが、これがすべてかどうかは不明である。一方で、電動チラーのソースコード（ChillerElectricEIR.cc）には冷却塔のような上下限値の記述はなかった。

```
Real64 const MaximumWaterFlowRate(0.016667); // Maximum limit of water flow rate in m3/s (1000 l/min)
Real64 const MinimumWaterFlowRate(0.0);      // Minimum limit of water flow rate
Real64 const MaxHeight(30.0);                // Maximum effective tower height in m
Real64 const MinHeight(1.0);                 // Minimum effective tower height in m
Real64 const MaxValue(100.0);                // Maximum limit of outlet area, airflow, and temperature
Real64 const MinValue(0.0);                  // Minimum limit of outlet area, airflow, and temperature
Real64 const MaxFrac(1.0);                   // Maximum fraction
Real64 const MinFrac(0.0);                   // Minimum fraction
```

