:lang: ja
:doctype: book
:toc: left
:toclevels: 2
:toc-title: EnergyPlus SHASE-G1008:2016
:sectnums:
:sectnumlevels: 4
:sectlinks:
:example-caption: 例
:table-caption: 表
:figure-caption: 図
:docname: EnergyPlus SHASE-G1008:2016
:stem: latexmath
:xrefstyle: short
:icons: font
:xrefstyle: short

= SHASE-G 1008:2016 + EnergyPlus
建物エネルギーシミュレーションツールの評価手法に関するガイドラインの適用事例（EnergyPlus Ver.9.4）

== はじめに

SHASE-G1008:2016「建物エネルギーシミュレーションツールの評価手法に関するガイドライン」をEnergyPlusに対して適用する方法を解説する。 +
EnergyPlusはVer.9.4を使用する。EnergyPlusのインストール方法や使用方法については省略する。

NOTE: SHASE-G1008:2016は http://www.shasej.org/tosho/report.html[空気調和・衛生工学会] にて購入できます。

TIP: EnergyPlusの入力ファイル（IDFファイル）の作成方法の詳細は https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/index.html[bigladder, role="external", window="_blank"] を参照してください。 +
Design Builderの使い方は link:./DesignBuilder.html[こちら]を参照してください。

<<<
== 熱負荷(単室)基本テストのモデル作成

SHASE-G1008:2016 第5章「熱負荷シミュレーションツールのテスト」で使用する基本建物モデルを作成する。

include::model_for_loadcalc.adoc[]

<<<
== 熱負荷(単室)基本テスト

// Case 600
include::case600.adoc[]

<<<
// Case 610
include::case610.adoc[]

<<<
// Case650
include::case650.adoc[]

<<<
// Case900, 900FF
include::case900.adoc[]

<<<
// Case960
include::case960.adoc[]

<<<
// Case 900J シリーズ
include::case900J.adoc[]

// 900Jの比較
include::case900J_detail.adoc[]

<<<
== 熱負荷（単室）詳細テストA

include::case220.adoc[]

include::case210.adoc[]

include::case200.adoc[]

include::case195.adoc[]

include::case215.adoc[]

include::case230.adoc[]

include::case240.adoc[]

include::case250.adoc[]

include::case270.adoc[]

<<<
== 熱負荷（単室）詳細テストB

include::case400.adoc[]
include::case395.adoc[]
include::case410.adoc[]
include::case420.adoc[]
include::case430.adoc[]
include::case800.adoc[]

<<<
== 熱負荷（複数室）テスト

// Case MZN 
include::caseMZN.adoc[]

// Case MZA
include::caseMZA.adoc[]

<<<
== 熱負荷（建物全体）テスト

include::caseWBT.adoc[]

<<<
== 空調システムテストのモデル作成

<<<
== 計算結果の出力
include::output.adoc[]

<<<
== 参考

// エラーの扱い
include::error.adoc[]

=== EnergyPlusのAuto-sizing機能における予熱/予冷時間の取り扱い
日本では、容量設計を行う際、立ち上がり時の蓄熱負荷の影響を緩和するため、予熱/予冷時間の概念を取り入れることが一般的である。この時間は、空調システムを起動してから設定温度に達するまでの時間を表している。例えば、予熱時間を2時間として朝6時にシステムが起動する場合、7時の時点では設定温度に達しないが、8時には達することになる。この場合、7時の時点で設定温度に達するようにする場合よりも設計容量を小さくすることができる。特に蓄熱負荷の影響が大きい冬季暖房運転においては予熱時間を2〜3時間とする方が実際的な容量とすることができる。なお、予熱時間をゼロとした場合、理論上必要な装置容量は無限大となる。

EnergyPlusにおいては予熱時間そのものの概念はないが、最大負荷を求める際の平均時間を設定することで、類似の処理を行えるようになっている。オブジェクトSizing:ParametersのTimesteps in Averaging Windowに平均処理を行うタイムステップ数を指定することができる。以下はlink:https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-design-objects.html#sizingparameters[bigladder:Input Output Reference:Sizing:Parameters:Timesteps in Averaging Window]の和訳である。以下ではゾーン設計風量にのみ言及しているが、ゾーン設計風量の計算はAuto-sizingの計算フロー上、最も上流側で行われるようであるため、空調システムや熱源システムの容量設計においてもここで指定したステップ数が反映されると思われる。

=== Timesteps in Averaging Window
ゾーン設計風量の平均化処理を行う際のタイムステップ数を入力する。デフォルトは1であり、この場合、計算されたゾーン設計風量は、タイムステップにわたって平均化された値である。

ゾーン設計風量計算は、一定の温度で加熱または冷却空気が無限に供給されると想定して実行される。したがって、計算された設計風量は、どれほど大きく急激な負荷であっても、常にあらゆる負荷変動に対応できる。実際には、風量はダクトのサイズとファンの容量によって制限される。理想的なゾーン設計風量計算では、特にユーザーが夜間のセットアップまたはセットバックを伴うサーモスタットスケジュールを使用してサイジング計算を実行している場合、非現実的に大きな風量が発生する可能性がある。計算されたゾーン設計風量は、常にタイムステップにわたって平均化される。ユーザーは、サーモスタットのセットアップとセットバックの影響を軽減し、ウォームアップまたはクールダウン時の風量が設計風量の計算において支配的になるのを防ぐために、より平均時間を長く指定することができる。

たとえば、負荷計算のタイムステップが15分で、ユーザーがこの平均化タイムステップ数を4に指定した場合、ゾーン設計風量は1時間にわたって平均化される。8を指定すると、2時間の平均となる。


=== DesignBuilderの使い方

link:https://masatomiyata.github.io/EnergyPlus_SHASEG1008/DesignBuilder.html[DesignBuilder＋Rを用いたAS140単室テスト]


