//  Case 600

=== Building

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-simulation-parameters.html#building[Buildingクラスの作成方法, role="external", window="_blank"]

Buildingクラスは、シミュレーション実行時に使用されるパラメータを記述する。 +
このクラスの入力内容と、Site:WeatherStation や Site:HeightVariation のいくつかのエントリ（特にTerrainフィールド）の内容は整合が取れている必要がある。

.Building
----
  Building,
    Case600,                 !- Name
    0.0,                     !- North Axis {deg}
    Country,                 !- Terrain
    3.9999999E-02,           !- Loads Convergence Tolerance Value {W}
    4.0000002E-03,           !- Temperature Convergence Tolerance Value {deltaC}
    FullInteriorAndExterior, !- Solar Distribution
    ,                        !- Maximum Number of Warmup Days
    6;                       !- Minimum Number of Warmup Days
----

==== Name
建物名称を任意に入力する。

==== North Axis
建物の方位が真北から時計回りに何度回転しているかを指定する。
ただし、link:https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-thermal-zone-description-geometry.html#globalgeometryrules[GlobalGeometryRules]で
「Relative」以外の座標系が使用されている場合、この入力値は無視される。

==== Terrain
この地形（Terrain）の入力は、建物の高さと同様に、風がどのように建物に当たるかに影響を与える。 +
このフィールドの有効な値を次の表に示す。

.Values for “Terrain”
[options="header"]
|====================================================
|Terrain Type Value|	Terrain Description
|Country|	Flat, Open Country
|Suburbs|	Rough, Wooded Country, Suburbs
|City|	Towns, city outskirts, center of large cities
|Ocean|	Ocean, Bayou flat country
|Urban|	Urban, Industrial, Forest
|====================================================

この入力によって外表面の対流熱伝達率の計算に用いる風速の計算式のパラメータが変化する。 +
建物近傍の風速の計算方法は link:https://bigladdersoftware.com/epx/docs/9-4/engineering-reference/outside-surface-heat-balance.html#local-wind-speed-calculation[Local Wind Speed Calculation] を参照。

===== （補足）Terrainの選択について
ASHRAE Standard 140 の本文中にサイトの場所的特徴に関する記載はないが、Normative Annex A1: Weather dataのTable A1-1に、使用する気象データを測定した気象ステーションの場所として「Flat, unobstructed」という記述がある。唯一の情報であるこの記述を正とすれば、Terrainの入力は「Country（Flat, Open Country）」が適当と考えられる。

==== Warmup Convergence
次の2つのフィールドは、助走運転の最小日数と最大日数とともに、EnergyPlusが各ステップで収束する条件を定義する 。
計算開始時に室温は23^o^Cに、相対湿度は屋外相対湿度に初期化される。
EnergyPlusでは、計算開始日の計算を、助走運転の最大日数に達するか収束条件が満たされるまで、繰り返し実行する。

==== Loads Convergence Tolerance Value
この負荷許容値[W]は助走運転における収束条件の1つであり、ピークゾーンの冷暖房負荷の前回計算からの変化量に対して適用される。

==== Temperature Convergence Tolerance Value
この温度許容値[^o^C]は助走運転における収束条件の1つであり、ゾーン温度の冷暖房負荷の前回計算からの変化量に対して適用される。 +
負荷または温度許容値のいずれかが満たされると、Simultaneous heat balance/HVAC solution の収束に達する。

==== Solar Distribution
EnergyPlusが直達日射と外表面からの反射をどのように扱うかを定義する。次の5つの選択肢がある。

* MinimalShadowing
** 窓とドアを除いて、外部の影は考慮しない。ゾーンに入る全ての直達日射は床に当たると想定され、床の日射吸収率に応じて吸収される。床で反射されたものはすべて、反射拡散日射に追加される。これは、全ての内表面に均一に分布していると仮定される。 ゾーンに床が存在しない場合、直達日射は吸収率に応じて全ての内表面で吸収される。次に、表面熱流として扱われる吸収された日射を考慮して、各表面とゾーン空気の熱収支が計算される。

* FullExterior, FullExteriorWithReflections
** 全てのゾーンのDetached shading, wings, overhangs, and exterior surfacesによって引き起こされる外表面のShadow patternsが計算される。MinimalShadowingと同様に、窓やドアによる影も計算される。ゾーンに入る直達日射は、MinimalShadowing の場合と同様に扱われる。

* FullInteriorAndExterior, FullInteriorAndExteriorWithReflections
** FullExteriorと同じだが、全ての透過直達日射が床に当たると仮定する代わりに、太陽の光線を外部から投影することにより、床、壁、窓などゾーンの各表面に当たる直達日射量を計算する。外部の日陰面や窓のShading devicesも考慮する。 +
このオプションを用いる場合、そのゾーンが完全に面によって閉じられており、かつConvex（つまり内側に凹んだような形状はNG）である必要がある。 +
FullInteriorAndExteriorを使用する場合、プログラムは（ゾーン内の他のウィンドウから）窓の内側に当たる直達日射が窓によって吸収される量、ゾーンに反射する量及び外側に透過する量も計算する。

===== （補足）Solar distributionの選択について
ASHRAE Standard 140 に日射計算方法についての指定はないため、Shading devicesを考慮できるFullExterior以下のオプションであれば問題ないと考えられる。 +
上記の説明からすると、ほとんどの場合は FullExterior を使用することが推奨されているように読み取れる。 +
FullInteriorAndExteriorは、ゾーンが面で完全に閉じられていることと、Convexであることという大きな形状の制約がある。
物理的な壁を定義せずにゾーンを区切りたいケースは現実には多くあるが、その場合はこのオプションを使用できないと思われる。 +
Reflectionの使用については計算時間やエラーについての注意書きがあることから、特別な利用目的の場合を除いて推奨していないように見える。
また、ASHRAE Standard 140ではShading devices自体の特性（反射率等）を指定していないため、おそらくこのような反射計算を行うことは想定していない。 +
以上より、実際に近い精緻な計算を行うという観点に立てば、FullInteriorAndExteriorを用いることが適当と考えられるが、
現実の多くのシチュエーションでFullExteriorを用いるとすれば、FullExteriorで計算することも適当ではないかと思われる。

以下にFullExteriorとFullInteriorAndExteriorで計算した結果を示す。Case600については大きな差はないことが分かる。

.Difference in heating/cooling load between solar distribution options
[options="header"]
|===============================================================
|窓モデル|暖房積算 [MWh]|冷房積算 [MWh]|暖房ピーク [kW]|冷房ピーク [kW]
|FullExterior|4.2329| 7.2764| 3.7777| 6.9069
|FullInteriorAndExterior|4.2356|7.2554|3.7778|6.8969
|===============================================================

===== Diffuse Radiation
外部及び内部の窓を透過する拡散日射は、透過する窓とゾーン内の他の全ての熱伝達面との間の近似的な形態係数に従って分配される。
ゾーン内の全ての表面で反射されるこの拡散日射は、室内で反射される直達日射と照明からの短波とともに、ゾーン内の全ての熱伝達面に均一に（面積及び吸収率に基づいて）再分配される。

===== Reflection calculations
注：反射計算の使用には、非常に時間がかかる場合がある。またエラーが発生しやすい。

このオプションを使用すると、外表面から反射されて建物に当たる直達・拡散日射を計算する。これらの反射面は、次の3つのカテゴリーに分類される。

* Shadowing surfaces
** これはオブジェクトで定義するShading devicesである。

* Exterior building surfaces 
** 建物の1つのセクションが日射を別のセクションに反射する。

* The ground surface
** 反射オプションが使用されていない場合でも、地面からの反射は計算されるが、その場合は地面は遮られていないと見なされる。つまり、建物自体または隣接する建物などの障害物による地面の影は無視される。+
反射オプションが使用されている場合、建物自体または隣接する建物による影が考慮されるが、その代わりに"View factor to ground"の入力は使用されない。


==== Maximum Number of Warmup Days
収束するまでにシミュレーションで使用される可能性のある助走日数を最大値を入力する。通常、デフォルトである25で十分である。ただし、一部の複雑な建物（複雑な構造）ではさらに日数がかかる場合がある。

==== Minimum Number of Warmup Days
EnergyPlusが収束したかどうかをチェックし、シミュレーションを開始できるようになるまでの助走日数の最小値を入力する。


=== Site:Location
Site:Locationクラスは、建物の位置に関するパラメータを記述する。位置は1つしか指定できない。

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-location-climate-weather-file-access.html[Site:Locationクラスの作成方法, role="external", window="_blank"]

気象データファイルに位置情報が存在する場合は、IDFに記された位置情報データよりも優先される。
したがって、年間シミュレーションの場合、Locationを入力する必要はない。

.Site:Location
----
  Site:Location,
    Denver-Stapleton,CO,USA,TMY--23062,  !- Name
    39.8,                    !- Latitude {deg}
    -104.9,                  !- Longitude {deg}
    -7.0,                    !- Time Zone {hr}
    1609.00;                 !- Elevation {m}
----

【補足】
気象データファイルと緯度・経度の桁が異なる。標高も違う。

=== Timestep
計算時間間隔を設定する。

60を入力した数値で除した値が計算時間間隔（分）になる。今回は4を入力したため、60/4=15分間隔の計算を行う。

.Timestep
----
Timestep,
    4;                       !- Number of Timesteps per Hour
----

=== RunPeriod
RunPeriodクラスでは、計算期間の設定を行う。

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-location-climate-weather-file-access.html#runperiod[RunPeriodクラスの作成方法, role="external", window="_blank"]

.RunPeriod
----
RunPeriod,
    RUNPERIOD 1,             !- Name
    1,                       !- Begin Month
    1,                       !- Begin Day of Month
    ,                        !- Begin Year
    12,                      !- End Month
    31,                      !- End Day of Month
    ,                        !- End Year
    ,                        !- Day of Week for Start Day
    Yes,                     !- Use Weather File Holidays and Special Days
    Yes,                     !- Use Weather File Daylight Saving Period
    No,                      !- Apply Weekend Holiday Rule
    Yes,                     !- Use Weather File Rain Indicators
    Yes,                     !- Use Weather File Snow Indicators
    No;                      !- Treat Weather as Actual
----

==== Day of Week for Start Day

このフィールドでは、週の開始日を指定することができます。有効な曜日（日、月、火、水、木、金、土）をこのフィールドに入力できます。
明確にするために、この値はこの実行期間の開始日（タイプ）として使用され、それ以降の日は実装されます。
このフィールドが空白の場合、開始日のタイプはデフォルトで日曜日になります。


=== ShadowCalculation
ShadowCalculationでは、日陰の計算方法に関する設定を行う。

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-simulation-parameters.html#shadowcalculation[ShadowCalculationクラスの作成方法, role="external", window="_blank"]

.ShadowCalculation
----
ShadowCalculation,
    PolygonClipping,         !- Shading Calculation Method
    Periodic,                !- Shading Calculation Update Frequency Method
    1;                       !- Shading Calculation Update Frequency
----

==== Shading Calculation Update Frequency Method
このフィールドは、シミュレーション中の計算時間に関して、ソーラーモデル、シェーディングモデル、デイライトモデルの計算方法を制御するために使用する。
キーワードPeriodicを使用すると、デフォルトで最速の方法が選択される。
より詳細で遅い方法は、キーワードTimestepを使って選択できる。
動的なフェネストレーションやシェーディングサーフェスのモデリングには必ず Timestep 方式を使用する。

==== Shading Calculation Update Frequency
このフィールドに入力された日数毎に、日陰の計算が実行される。
このフィールドは、前のフィールドでデフォルトの「Periodic」が使用されている場合にのみ使用される。
このフィールドを使用すると、シェーディングデバイスの変更に合わせてシャドーイング計算を同期させることができる。
デフォルトは20日であり、これは太陽位置角の著しく変化しない平均的な日数である。
これらの日陰計算には、太陽の角度、位置、時間の方程式の（期間中の）「平均」も使用される。

【補足】 +
Shading Calculation Update Frequencyは計算結果に与える影響が大きい。
デフォルトは20日であるが、より細かい1日とする。


=== Site:GroundReflectance
Site:GroundReflectanceクラスでは、地物反射率に関するパラメータを記述する。

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-location-climate-weather-file-access.html#sitegroundreflectance[Site:GroundReflectanceクラスの作成方法, role="external", window="_blank"]

.Site:GroundReflectance　
----
  Site:GroundReflectance,
    0.2,                     !- January Ground Reflectance {dimensionless}
    0.2,                     !- February Ground Reflectance {dimensionless}
    0.2,                     !- March Ground Reflectance {dimensionless}
    0.2,                     !- April Ground Reflectance {dimensionless}
    0.2,                     !- May Ground Reflectance {dimensionless}
    0.2,                     !- June Ground Reflectance {dimensionless}
    0.2,                     !- July Ground Reflectance {dimensionless}
    0.2,                     !- August Ground Reflectance {dimensionless}
    0.2,                     !- September Ground Reflectance {dimensionless}
    0.2,                     !- October Ground Reflectance {dimensionless}
    0.2,                     !- November Ground Reflectance {dimensionless}
    0.2;                     !- December Ground Reflectance {dimensionless}
----

=== Site:GroundTemperature:BuildingSurface
Site:GroundTemperature:BuildingSurfaceクラスでは、地中の温度を入力する。

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-location-climate-weather-file-access.html#sitegroundtemperaturebuildingsurface[Site:GroundTemperature:BuildingSurfaceクラスの作成方法, role="external", window="_blank"]

.Site:GroundTemperature:BuildingSurface　
----
  Site:GroundTemperature:BuildingSurface,
    10,                      !- January Ground Temperature {C}
    10,                      !- February Ground Temperature {C}
    10,                      !- March Ground Temperature {C}
    10,                      !- April Ground Temperature {C}
    10,                      !- May Ground Temperature {C}
    10,                      !- June Ground Temperature {C}
    10,                      !- July Ground Temperature {C}
    10,                      !- August Ground Temperature {C}
    10,                      !- September Ground Temperature {C}
    10,                      !- October Ground Temperature {C}
    10,                      !- November Ground Temperature {C}
    10;                      !- December Ground Temperature {C}
----

地面の温度は、地面の熱伝導モデルに使用される。
地面温度オブジェクトは1つだけ指定することができ、Outside Boundary Condition = Ground とされたサーフェスにおける外側の温度として使用される。
地面と接触するサーフェスがない場合は、このオブジェクトはオプションとなる。

個々のサーフェスの外側温度を個別に指定する場合は、OtherSideCoefficients オブジェクトを使用する。
このオブジェクトを使用すれば、いくつもの異なる温度を指定することができる。

注意：気象データコンバータによって計算された「乱されていない（undisturbed）」地面温度は、建物の熱損失計算（building losses）には使用すべきではない。
Site:GroundTemperature:Shallow　及び　Site:GroundTemperature:Deepオブジェクトを使用するのが適切である。
この理由は（建物の熱損失に対して）、これらの値は空調された建物の下にある地盤に対しては極端すぎるからである。
最良の結果を得るためには、スラブまたは地下室プログラムを使用して、月平均地中温度を計算すること（「Ground Heat Transfer」のセクションを参照）。
これは、住宅や非常に小さな建物では特に重要である。

これらの地中温度プリプロセッサを使用しない場合、米国の一般的な商業ビルでは、平均的な室内空間温度よりも2℃低い値が妥当なデフォルト値となる。
適切な地中温度の決定に関する詳細は、EnergyPlusの解説書「Auxiliary Programs」に記載されている。

==== （補足）その他の地盤温度の設定方法

EnergyPlusでは複数の地盤温度設定方法が用意されている。
ここでは、今回使用する　Site:GroundTemperature:BuildingSurface　以外の設定方法について概説する。

===== Site:GroundTemperature:Shallow

参考：　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-location-climate-weather-file-access.html#sitegroundtemperatureshallow[bigladder解説]

Site:GroundTemperature:Shallowは、Surface Ground Heat Exchanger（例：GroundHeatExchanger:Surface　オブジェクト）で使用される。
浅い地中温度は1つだけ指定することができる。

通年の気象データファイルに含まれている地中温度は、「典型的な」条件の「乱されていない」土壌に対して計算された0.5mの深さの温度であり、このフィールドの値に使用するのに適している可能性がある。
このオブジェクトは、「乱されていない」地面の温度を必要とするオブジェクトに使用できる。このような場合、「名前」の入力フィールドは必要ない。

===== Site:GroundTemperature:Deep

参考：　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-location-climate-weather-file-access.html#sitegroundtemperaturedeep[bigladder解説]

Site:GroundTemperature:Deepは、Pond Ground Heat Exchangerオブジェクト（例：GroundHeatExchanger:Pond オブジェクト）で使用される。
深い地中温度は1つだけ指定することができる。

通年の気象データファイルに含まれる地中温度は、「典型的な」条件の「乱されていない」土壌に対して計算される4mの深さの温度であり、このフィールドの値に使用するのに適している可能性がある。
このオブジェクトは、「乱されていない」地面の温度を必要とするオブジェクトに使用できる。このような場合、「名前」の入力フィールドは必要ない。

===== Site:GroundTemperature:Undisturbed:FiniteDifference

参考：　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-location-climate-weather-file-access.html#sitegroundtemperatureundisturbedfinitedifference[bigladder解説]

Site:GroundTemperature:Undisturbed:FiniteDifferenceは、「乱されていない」地中温度を必要とする全てのオブジェクトで使用できる。
このオブジェクトは、気象データファイルを使用して表面の境界条件を取得する1次元有限差分熱伝達モデルを使用する。
このモデルは、初期化時に、年間の地中温度プロファイルが定常的な周期性に達するまで、年間シミュレーションが実行される。
安定した周期的な挙動に達すると、残りのシミュレーション期間中に地中温度を取得するために計算結果が格納される。

===== Site:GroundTemperature:FCfactorMethod

参考：　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-location-climate-weather-file-access.html#sitegroundtemperaturefcfactormethod[bigladder解説]

Site:GroundTemperature:FCfactorMethodは、詳細な建材構成が不明な場合の基準適合計算をする際に、
C-factor法（Construction:CfactorUndergroundWall）及びF-factor法（Construction:FfactorGroundFloor）で定義された地下の壁またはスラブまたは地下の床で使用される。
この地表温度オブジェクトは1つだけ含めることができる。
このオブジェクトの月別地中温度は、月別外気温度を3ヶ月遅らせたものに近い。
ユーザーがIDFファイルにこのオブジェクトを入力しない場合、気象データファイルから0.5mの月別地中温度が利用可能であれば、それがデフォルトになる。
このオブジェクトを入力すると、F-factor及びC-factorの使用において、気象データファイルから地上温度が上書きされる。
どちらも利用できない場合は、エラーとなる。

===== Site:GroundTemperature:Undisturbed:KusudaAchenbach
Kusuda, T. と P.R. Achenbach　による回帰式

===== Site:GroundTemperature:Undisturbed:Xing
Xing　による回帰式

===== GroundHeatExchanger:Surface

参考：　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-condenser-equipment.html#groundheatexchangersurface[bigladder解説]

表面熱交換器モデルは、水式の表面地中熱交換器をシミュレーションするためのものである。
これには、融雪用のパイプを埋め込んだ舗装面や、ハイブリッド地中熱源ヒートポンプシステムからの排熱が含まれる。

熱交換器は地面と連動している場合とそうでない場合がある。後者の場合、底面は風にさらされるがソーラーゲインは得られない。
このタイプの熱交換器は、凝縮器ループの供給側に接続することを目的としているが、あらゆるタイプのプラントループに使用することができる。
表面熱交換器は、凝縮器ループの唯一の熱交換器として指定することができ、他の凝縮器ループ熱交換器（冷却塔、地表熱交換器など）と並列に接続することもできる。


=== Zone

Zoneクラスは、ゾーンに関するパラメータを記述する。

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-thermal-zone-description-geometry.html[Zoneクラスの作成方法, role="external", window="_blank"]

.Zone　
----
Zone,
    Zone1,                   !- Name
    0.0,                     !- Direction of Relative North {deg}
    0.0,                     !- X Origin {m}
    0.0,                     !- Y Origin {m}
    0.0,                     !- Z Origin {m}
    ,                        !- Type
    1,                       !- Multiplier
    2.7000,                  !- Ceiling Height {m}
    129.6;                   !- Volume {m3}
----

=== GlobalGeometryRules

GlobalGeometryRulesクラスでは、座標に関する設定を入力する。

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-thermal-zone-description-geometry.html#globalgeometryrules[GlobalGeometryRulesクラスの作成方法, role="external", window="_blank"]

.GlobalGeometryRules
----
GlobalGeometryRules,
    UpperLeftCorner,         !- Starting Vertex Position
    Counterclockwise,        !- Vertex Entry Direction
    World;                   !- Coordinate System
----

上のように設定すると、座標は「左上」から始まり「反時計回り」に指定することになる。 


=== BuildingSurface:Detailed

BuildingSurface:Detailedクラスでは、外壁構成に関するパラメータを記述する。

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-thermal-zone-description-geometry.html#buildingsurfacedetailed[BuildingSurface:Detailedクラスの作成方法, role="external", window="_blank"]

.BuildingSurface:Detailed　床
----
  BuildingSurface:Detailed,
    Floor,                   !- Name
    Floor,                   !- Surface Type
    Floor_configure,         !- Construction Name
    Zone1,                   !- Zone Name
    Ground,                  !- Outside Boundary Condition
    ,                        !- Outside Boundary Condition Object
    NoSun,                   !- Sun Exposure
    NoWind,                  !- Wind Exposure
    0.000000000000,          !- View Factor to Ground
    4,                       !- Number of Vertices
    0.000000000000,          !- Vertex 1 X-coordinate {m}
    0.000000000000,          !- Vertex 1 Y-coordinate {m}
    0.000000000000,          !- Vertex 1 Z-coordinate {m}
    0.000000000000,          !- Vertex 2 X-coordinate {m}
    6.000000000000,          !- Vertex 2 Y-coordinate {m}
    0.000000000000,          !- Vertex 2 Z-coordinate {m}
    8.000000000000,          !- Vertex 3 X-coordinate {m}
    6.000000000000,          !- Vertex 3 Y-coordinate {m}
    0.000000000000,          !- Vertex 3 Z-coordinate {m}
    8.000000000000,          !- Vertex 4 X-coordinate {m}
    0.000000000000,          !- Vertex 4 Y-coordinate {m}
    0.000000000000;          !- Vertex 4 Z-coordinate {m}
----

.BuildingSurface:Detailed　屋根
----
  BuildingSurface:Detailed,
    Roof,                    !- Name
    Roof,                    !- Surface Type
    Roof_configure,          !- Construction Name
    Zone1,                   !- Zone Name
    Outdoors,                !- Outside Boundary Condition
    ,                        !- Outside Boundary Condition Object
    SunExposed,              !- Sun Exposure
    WindExposed,             !- Wind Exposure
    0.000000000000,          !- View Factor to Ground
    4,                       !- Number of Vertices
    0.000000000000,          !- Vertex 1 X-coordinate {m}
    6.000000000000,          !- Vertex 1 Y-coordinate {m}
    2.700000000000,          !- Vertex 1 Z-coordinate {m}
    0.000000000000,          !- Vertex 2 X-coordinate {m}
    0.000000000000,          !- Vertex 2 Y-coordinate {m}
    2.700000000000,          !- Vertex 2 Z-coordinate {m}
    8.000000000000,          !- Vertex 3 X-coordinate {m}
    0.000000000000,          !- Vertex 3 Y-coordinate {m}
    2.700000000000,          !- Vertex 3 Z-coordinate {m}
    8.000000000000,          !- Vertex 4 X-coordinate {m}
    6.000000000000,          !- Vertex 4 Y-coordinate {m}
    2.700000000000;          !- Vertex 4 Z-coordinate {m}
----

.BuildingSurface:Detailed　外壁（南）
----
  BuildingSurface:Detailed,
    Wall_S,                  !- Name
    Wall,                    !- Surface Type
    Wall-configure,          !- Construction Name
    Zone1,                   !- Zone Name
    Outdoors,                !- Outside Boundary Condition
    ,                        !- Outside Boundary Condition Object
    SunExposed,              !- Sun Exposure
    WindExposed,             !- Wind Exposure
    0.500000000000,          !- View Factor to Ground
    4,                       !- Number of Vertices
    0.000000000000,          !- Vertex 1 X-coordinate {m}
    0.000000000000,          !- Vertex 1 Y-coordinate {m}
    2.700000000000,          !- Vertex 1 Z-coordinate {m}
    0.000000000000,          !- Vertex 2 X-coordinate {m}
    0.000000000000,          !- Vertex 2 Y-coordinate {m}
    0.000000000000,          !- Vertex 2 Z-coordinate {m}
    8.000000000000,          !- Vertex 3 X-coordinate {m}
    0.000000000000,          !- Vertex 3 Y-coordinate {m}
    0.000000000000,          !- Vertex 3 Z-coordinate {m}
    8.000000000000,          !- Vertex 4 X-coordinate {m}
    0.000000000000,          !- Vertex 4 Y-coordinate {m}
    2.700000000000;          !- Vertex 4 Z-coordinate {m}
----

.BuildingSurface:Detailed　外壁（北）
----
  BuildingSurface:Detailed,
    Wall_N,                  !- Name
    Wall,                    !- Surface Type
    Wall-configure,          !- Construction Name
    Zone1,                   !- Zone Name
    Outdoors,                !- Outside Boundary Condition
    ,                        !- Outside Boundary Condition Object
    SunExposed,              !- Sun Exposure
    WindExposed,             !- Wind Exposure
    0.500000000000,          !- View Factor to Ground
    4,                       !- Number of Vertices
    8.000000000000,          !- Vertex 1 X-coordinate {m}
    6.000000000000,          !- Vertex 1 Y-coordinate {m}
    2.700000000000,          !- Vertex 1 Z-coordinate {m}
    8.000000000000,          !- Vertex 2 X-coordinate {m}
    6.000000000000,          !- Vertex 2 Y-coordinate {m}
    0.000000000000,          !- Vertex 2 Z-coordinate {m}
    0.000000000000,          !- Vertex 3 X-coordinate {m}
    6.000000000000,          !- Vertex 3 Y-coordinate {m}
    0.000000000000,          !- Vertex 3 Z-coordinate {m}
    0.000000000000,          !- Vertex 4 X-coordinate {m}
    6.000000000000,          !- Vertex 4 Y-coordinate {m}
    2.700000000000;          !- Vertex 4 Z-coordinate {m}
----

.BuildingSurface:Detailed　外壁（西）
----
  BuildingSurface:Detailed,
    Wall_W,                  !- Name
    Wall,                    !- Surface Type
    Wall-configure,          !- Construction Name
    Zone1,                   !- Zone Name
    Outdoors,                !- Outside Boundary Condition
    ,                        !- Outside Boundary Condition Object
    SunExposed,              !- Sun Exposure
    WindExposed,             !- Wind Exposure
    0.500000000000,          !- View Factor to Ground
    4,                       !- Number of Vertices
    0.000000000000,          !- Vertex 1 X-coordinate {m}
    6.000000000000,          !- Vertex 1 Y-coordinate {m}
    2.700000000000,          !- Vertex 1 Z-coordinate {m}
    0.000000000000,          !- Vertex 2 X-coordinate {m}
    6.000000000000,          !- Vertex 2 Y-coordinate {m}
    0.000000000000,          !- Vertex 2 Z-coordinate {m}
    0.000000000000,          !- Vertex 3 X-coordinate {m}
    0.000000000000,          !- Vertex 3 Y-coordinate {m}
    0.000000000000,          !- Vertex 3 Z-coordinate {m}
    0.000000000000,          !- Vertex 4 X-coordinate {m}
    0.000000000000,          !- Vertex 4 Y-coordinate {m}
    2.700000000000;          !- Vertex 4 Z-coordinate {m}
----

.BuildingSurface:Detailed　外壁（東）
----
  BuildingSurface:Detailed,
    Wall_E,                  !- Name
    Wall,                    !- Surface Type
    Wall-configure,          !- Construction Name
    Zone1,                   !- Zone Name
    Outdoors,                !- Outside Boundary Condition
    ,                        !- Outside Boundary Condition Object
    SunExposed,              !- Sun Exposure
    WindExposed,             !- Wind Exposure
    0.500000000000,          !- View Factor to Ground
    4,                       !- Number of Vertices
    8.000000000000,          !- Vertex 1 X-coordinate {m}
    0.000000000000,          !- Vertex 1 Y-coordinate {m}
    2.700000000000,          !- Vertex 1 Z-coordinate {m}
    8.000000000000,          !- Vertex 2 X-coordinate {m}
    0.000000000000,          !- Vertex 2 Y-coordinate {m}
    0.000000000000,          !- Vertex 2 Z-coordinate {m}
    8.000000000000,          !- Vertex 3 X-coordinate {m}
    6.000000000000,          !- Vertex 3 Y-coordinate {m}
    0.000000000000,          !- Vertex 3 Z-coordinate {m}
    8.000000000000,          !- Vertex 4 X-coordinate {m}
    6.000000000000,          !- Vertex 4 Y-coordinate {m}
    2.700000000000;          !- Vertex 4 Z-coordinate {m}
----


=== FenestrationSurface:Detailed

FenestrationSurface:Detailedクラスでは、窓構成に関するパラメータを入力する。

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-thermal-zone-description-geometry.html#fenestrationsurfacedetailed[FenestrationSurface:Detailedクラスの作成方法, role="external", window="_blank"]

.BuildingSurface:Detailed　窓（南1）
----
  FenestrationSurface:Detailed,
    Window_S1,               !- Name
    Window,                  !- Surface Type
    Window_configure,        !- Construction Name
    Wall_S,                  !- Building Surface Name
    ,                        !- Outside Boundary Condition Object
    0.500000000000,          !- View Factor to Ground
    ,                        !- Frame and Divider Name
    1,                       !- Multiplier
    4,                       !- Number of Vertices
    0.500000000000,          !- Vertex 1 X-coordinate {m}
    0.000000000000,          !- Vertex 1 Y-coordinate {m}
    2.200000000000,          !- Vertex 1 Z-coordinate {m}
    0.500000000000,          !- Vertex 2 X-coordinate {m}
    0.000000000000,          !- Vertex 2 Y-coordinate {m}
    0.200000000000,          !- Vertex 2 Z-coordinate {m}
    3.500000000000,          !- Vertex 3 X-coordinate {m}
    0.000000000000,          !- Vertex 3 Y-coordinate {m}
    0.200000000000,          !- Vertex 3 Z-coordinate {m}
    3.500000000000,          !- Vertex 4 X-coordinate {m}
    0.000000000000,          !- Vertex 4 Y-coordinate {m}
    2.200000000000;          !- Vertex 4 Z-coordinate {m}
----

.BuildingSurface:Detailed　窓（南2）
----
  FenestrationSurface:Detailed,
    Window_S2,               !- Name
    Window,                  !- Surface Type
    Window_configure,        !- Construction Name
    Wall_S,                  !- Building Surface Name
    ,                        !- Outside Boundary Condition Object
    0.500000000000,          !- View Factor to Ground
    ,                        !- Frame and Divider Name
    1,                       !- Multiplier
    4,                       !- Number of Vertices
    4.500000000000,          !- Vertex 1 X-coordinate {m}
    0.000000000000,          !- Vertex 1 Y-coordinate {m}
    2.200000000000,          !- Vertex 1 Z-coordinate {m}
    4.500000000000,          !- Vertex 2 X-coordinate {m}
    0.000000000000,          !- Vertex 2 Y-coordinate {m}
    0.200000000000,          !- Vertex 2 Z-coordinate {m}
    7.500000000000,          !- Vertex 3 X-coordinate {m}
    0.000000000000,          !- Vertex 3 Y-coordinate {m}
    0.200000000000,          !- Vertex 3 Z-coordinate {m}
    7.500000000000,          !- Vertex 4 X-coordinate {m}
    0.000000000000,          !- Vertex 4 Y-coordinate {m}
    2.200000000000;          !- Vertex 4 Z-coordinate {m}
----

=== Material, Construction

Materialクラスでは建材の熱物性値を定義し、Constructionクラスで建材構成を入力する。

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-surface-construction-elements.html#material[Materialクラスの作成方法, role="external", window="_blank"]

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-surface-construction-elements.html#construction-000[Constructionクラスの作成方法, role="external", window="_blank"]


.Material　外壁
----
  Material,
    PLASTERBOARD-12mm,       !- Name
    Rough,                   !- Roughness
    0.01200,                 !- Thickness {m}
    0.16000,                 !- Conductivity {W/m-K}
    950.000,                 !- Density {kg/m3}
    840.00,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance

  Material,
    FIBERGLASS-66mm,         !- Name
    Rough,                   !- Roughness
    0.066,                   !- Thickness {m}
    0.040,                   !- Conductivity {W/m-K}
    12.000,                  !- Density {kg/m3}
    840.00,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance

  Material,
    WOODSIDING-9mm,          !- Name
    Rough,                   !- Roughness
    0.00900,                 !- Thickness {m}
    0.14000,                 !- Conductivity {W/m-K}
    530.000,                 !- Density {kg/m3}
    900.00,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance
----

.Construction　外壁
----
  Construction,
    Wall-configure,          !- Name
    WOODSIDING-9mm,          !- Outside Layer
    FIBERGLASS-66mm,         !- Layer 2
    PLASTERBOARD-12mm;       !- Layer 3
----


.Material　床
----
  Material,
    TIMBERFLOORING-25mm,     !- Name
    Rough,                   !- Roughness
    0.02500,                 !- Thickness {m}
    0.14000,                 !- Conductivity {W/m-K}
    650.000,                 !- Density {kg/m3}
    1200.0,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance

  Material,
    FIBERGLASS-1003mm,       !- Name
    Rough,                   !- Roughness
    1.003,                   !- Thickness {m}
    0.040,                   !- Conductivity {W/m-K}
    1.000,                   !- Density {kg/m3}
    100.0,                   !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance
----

【補足】 + 
断熱材（FIBERGLASS-1003mm）について、密度と比熱はプログラムが許容する最小値とすることとされている。
比熱の最小値は　100 J/kg-K　と記載があったが、密度については記載が見つからなかった。 +
参考：　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-surface-construction-elements.html#field-specific-heat[比熱の最小値]


.Construction　床
----
  Construction,
    Floor_configure,         !- Name
    FIBERGLASS-1003mm,       !- Outside Layer
    TIMBERFLOORING-25mm;     !- Layer 2
----

.Material　屋根
----
  Material,
    PLASTERBOARD-10mm,       !- Name
    Rough,                   !- Roughness
    0.01000,                 !- Thickness {m}
    0.16000,                 !- Conductivity {W/m-K}
    950.000,                 !- Density {kg/m3}
    840.00,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance

  Material,
    FIBERGLASS-111mm,        !- Name
    Rough,                   !- Roughness
    0.1118,                  !- Thickness {m}
    0.040,                   !- Conductivity {W/m-K}
    12.000,                  !- Density {kg/m3}
    840.00,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance

  Material,
    ROOFDECK-19mm,           !- Name
    Rough,                   !- Roughness
    0.01900,                 !- Thickness {m}
    0.14000,                 !- Conductivity {W/m-K}
    530.000,                 !- Density {kg/m3}
    900.00,                  !- Specific Heat {J/kg-K}
    0.9000000,               !- Thermal Absorptance
    0.600000,                !- Solar Absorptance
    0.600000;                !- Visible Absorptance
----

.Construction　屋根
----
  Construction,
    Roof_configure,          !- Name
    ROOFDECK-19mm,           !- Outside Layer
    FIBERGLASS-111mm,        !- Layer 2
    PLASTERBOARD-10mm;       !- Layer 3
----


=== WindowMaterial:Glazing
WindowMaterial:Glazingクラスでは、ガラスの熱物性値を定義して、Constructionクラスで窓構成を入力する。

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-surface-construction-elements.html#windowmaterialglazing[WindowMaterial:Glazingクラスの作成方法, role="external", window="_blank"]

.WindowMaterial:Glazing
----
  WindowMaterial:Glazing,
    GlassType1,              !- Name
    SpectralAverage,         !- Optical Data Type
    ,                        !- Window Glass Spectral Data Set Name
    0.003175,                !- Thickness {m}
    0.86156,                 !- Solar Transmittance at Normal Incidence
    0.07846,                 !- Front Side Solar Reflectance at Normal Incidence
    0.07846,                 !- Back Side Solar Reflectance at Normal Incidence
    0.91325,                 !- Visible Transmittance at Normal Incidence
    0.08200,                 !- Front Side Visible Reflectance at Normal Incidence
    0.08200,                 !- Back Side Visible Reflectance at Normal Incidence
    0.0,                     !- Infrared Transmittance at Normal Incidence
    0.84,                    !- Front Side Infrared Hemispherical Emissivity
    0.84,                    !- Back Side Infrared Hemispherical Emissivity
    1.06;                    !- Conductivity {W/m-K}

  WindowMaterial:Gas,
    AirSpaceResistance,      !- Name
    AIR,                     !- Gas Type
    0.013;                   !- Thickness {m}
----

.Construction　窓
----
  Construction,
    window_configure,        !- Name
    GlassType1,              !- Outside Layer
    AirSpaceResistance,      !- Layer 2
    GlassType1;              !- Layer 3
----

==== Name
ガラスレイヤーの名称である。Window construtionのレイヤー入力時に使用される。

==== Optical Data Type
このフィールドの有効な値は、SpectralAverage、Spectral、SpectralAndAngle、及び、BSDF である。

* SpectralAverage
** 太陽光の透過率と反射率に入力した値は太陽光スペクトル全体で平均化されていると見なされ、可視透過率と反射率に入力した値は太陽光スペクトル全体で平均化され、人間の目の反応によって重み付けされていると見なされる。
さまざまな種類のガラスのスペクトル平均特性を含むEnergyPlusのリファレンスデータセットがある。

* Spectral
** 次のフィールドに、WindowGlassSpectralDataオブジェクトで定義されたスペクトルデータセットの名前を入力する必要がある。
この場合、以下のフィールドの太陽光と可視光の透過率と反射率の値は空白にする必要がある。

* SpectralAndAngle
** 最後の3つのフィールドに、2つの独立変数を持つ曲線またはテーブルオブジェクトで定義されたスペクトル及び角度データセットの名前を入力する必要がある。
この場合、Window Glassスペクトルデータセット名は空白である必要があり、以下のフィールドの太陽光及び可視光の透過率と反射率の値は空白である必要がある。

* BSDF
** Construction：ComplexFenestrationStateオブジェクトを使用してWindow constructioのレイヤーを定義する必要がある。
Construction：ComplexFenestrationStateオブジェクトには、ComplexFenestrationレイヤーの光学プロパティを含むBSDFファイルへの参照が含まれている。

==== Window Glass Spectral Data Set Name
Optical Data Type = Spectralの場合、WindowGlassSpectralDataオブジェクトで定義されたスペクトルデータセットの名前を入力する。

==== Thickness
ガラスの厚さ [m]を入力する。

==== Solar Transmittance at Normal Incidence
太陽スペクトル全体で平均化された法線面での透過率を入力する。Optical Data Type = SpectralAverageの場合にのみ使用される。

==== Front Side Solar Reflectance at Normal Incidence
太陽スペクトル全体で平均化された法線面・前面の反射率を入力する。Optical Data Type = SpectralAverageの場合にのみ使用される。

==== Back Side Solar Reflectance at Normal Incidence
太陽スペクトル全体で平均化された法線面・背面の反射率を入力する。Optical Data Type = SpectralAverageの場合にのみ使用される。

==== Visible Transmittance at Normal Incidence
太陽スペクトル全体で平均化され、人間の目の反応によって重み付けされた法線面での可視光透過率を入力する。Optical Data Type = SpectralAverageの場合にのみ使用される。

==== Front Side Visible Reflectance at Normal Incidence
太陽スペクトル全体で平均化され、人間の目の反応によって重み付けされた法線面・前面の可視光反射率を入力する。Optical Data Type = SpectralAverageの場合にのみ使用される。

==== Back Side Visible Reflectance at Normal Incidence
太陽スペクトル全体で平均化され、人間の目の反応によって重み付けされた法線面・背面の可視光反射率を入力する。Optical Data Type = SpectralAverageの場合にのみ使用される。

==== Infrared Transmittance at Normal Incidence
法線面での長波長透過率を入力する。

==== Front Side Infrared Hemispherical Emissivity
前面の放射率を入力する。

==== Back Side Infrared Hemispherical Emissivity
背面の放射率を入力する。

==== Conductivity
熱伝導率 [W/mK]を入力する。

==== Dirt Correction Factor for Solar and Visible Transmittance
ガラスの汚れの影響を補正する係数を入力する。材料が外部の窓またはガラスドアの外側のガラス層として使用されている場合、プログラムは「法線面での太陽透過率」及び「法線面での可視光透過率」のフィールドにこの係数を掛ける。
材料が内側のガラス層として使用されている場合（二層ガラスなど）では、内側のガラス層はきれいであると想定されているため、汚れ補正係数は適用されない。

==== Solar Diffusing
No（デフォルト）及びYesの値を取る。
Noの場合、ガラスは透明であり、ガラスに入射する直達日射は拡散成分のない直達放射として透過する。
Yesの場合、ガラスは半透明で、ガラスに入射する直達日射は直達成分のない半球拡散放射として透過する。
このオプションは、外部窓の最も内側のレイヤーでのみ使用する必要がある。

Buildingオブジェクトで、Solar Distribution = FullInteriorAndExteriorの場合、外部窓のガラスにSolar Diffusing = Yesを使用すると、その窓からの室内における日射分配が変化する。
その結果、透明な窓を透過して特定の内表面に吸収される直達日射は、半透明の窓によって拡散され、より多くの内表面に拡散される。これにより、ゾーン内の冷暖房負荷の時間依存性が変わる可能性がある。


=== WindowMaterial:SimpleGlazingSystem
この入力オブジェクトは、個々のレイヤーではなく窓システム全体を記述するという点で、他のWindowMaterialオブジェクトとは異なる。

このオブジェクトは、窓の各層に関する情報が非常に限られている場合、または特定のパフォーマンスレベルを対象としている場合に使用される。
このオブジェクトは、単純な性能指標を、より完全な窓システムモデルに変換する。
性能指標は、UファクターとSHGC、及びオプションで可視光透過率を入力する。これらの値は、グレージングのみの窓（フレームなし）、または、フレームを含む平均窓性能のいずれかを表すためにユーザーが選択できる。
プログラム内で、モデルはフレームのない同等の窓ガラス層を生成する。

参考：　https://bigladdersoftware.com/epx/docs/9-4/engineering-reference/window-calculation-module.html#simple-window-model[Simple Window Model]

ユーザーが定義した法線面の透過率、反射率に基づいてガラスの入射角特性を計算するモデルを用いている。

参考：　https://bigladdersoftware.com/epx/docs/9-4/engineering-reference/window-calculation-module.html#calculation-of-angular-properties[Engineering Manual]


==== （補足）窓の入力方法について

窓システムの入力方法には、次の2つがある。

. レイヤー1つ1つの特性を定義していく方法（WindowMaterial:Glazing）
. 窓システム全体の特性を一括して定義する方法（WindowMaterial:SimpleGlazingSystem）

参考：　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-surface-construction-elements.html#materials-for-glass-windows-and-doors[Input Output Reference] +
参考：　https://bigladdersoftware.com/epx/docs/9-4/engineering-reference/window-calculation-module.html#window-calculation-module[Engineering Reference]

後者は近似的な方法のため基本的には前者が推奨されているが、通常はガラス1枚ずつの特性までメーカから取り寄せることはしないため、実務上は後者の方が用いやすいと言える。

前者を用いる場合、細かな入力を行えるというメリットがあるが、ASHRAE Standard 140では法線入射時の反射率が指定されておらず（link:https://www.shimadzu.co.jp/products/opt/guide4/02.html[フレネルの式]を用いると0.04336）、
また単板ガラスとしての入射角特性も指定されていない。
後者を用いる場合、U値とSHGCという窓システムを代表する特性のみを指定すれば良いというメリットがある一方、細かな入射角特性等は指定できない。

ASHRAE Standard 140:2017のTable 5-7で指定されている入射角特性は２枚のガラスを合わせた窓システムとしての特性であることから、
本Standardでは、WindowMaterial:Glazingで使用するようなガラス１枚の入射角特性を指定することは想定していないと考えられる。

よって、法線入射時の特性値のみを用いて、それぞれで計算した結果を比較する（サンプルコードを末尾に記載）。参考として、Design Builderで選択可能なAGC特性を用いた結果も併記する。

.Difference in heating/cooling load between window models
[options="header"]
|===============================================================
|窓モデル|暖房積算 [MWh]|冷房積算 [MWh]|暖房ピーク [kW]|冷房ピーク [kW]
|WindowMaterial:SimpleGlazingSystem|4.2887|7.1843|3.8261|6.8529
|WindowMaterial:Glazing|4.2329| 7.2764| 3.7777| 6.9069
|WindowMaterial:Glazing with AGC|4.2563| 6.9803 |3.7777 |6.7026 
|===============================================================

表に示すように無視できない程度の差があることが分かる。

.WindowMaterial:SimpleGlazingSystem
```

!-   ===========  ALL OBJECTS IN CLASS: WINDOWMATERIAL:SIMPLEGLAZINGSYSTEM ===========

WindowMaterial:SimpleGlazingSystem,
    10002,                   !- Name
    3,                       !- U-Factor {W/m2-K}
    0.789;                   !- Solar Heat Gain Coefficient

!-   ===========  ALL OBJECTS IN CLASS: CONSTRUCTION ===========

Construction,
    1003,                    !- Name
    10002;                   !- Outside Layer

```

.WindowMaterial:Glazing
```
!-   ===========  ALL OBJECTS IN CLASS: WINDOWMATERIAL:GLAZING ===========

WindowMaterial:Glazing,
    10001,                   !- Name
    SpectralAverage,         !- Optical Data Type
    ,                        !- Window Glass Spectral Data Set Name
    0.003175,                !- Thickness {m}
    0.86156,                 !- Solar Transmittance at Normal Incidence
    0.04336,                 !- Front Side Solar Reflectance at Normal Incidence
    0.04336,                 !- Back Side Solar Reflectance at Normal Incidence
    0.86156,                 !- Visible Transmittance at Normal Incidence
    0.04336,                 !- Front Side Visible Reflectance at Normal Incidence
    0.04336,                 !- Back Side Visible Reflectance at Normal Incidence
    0,                       !- Infrared Transmittance at Normal Incidence
    0.84,                    !- Front Side Infrared Hemispherical Emissivity
    0.84,                    !- Back Side Infrared Hemispherical Emissivity
    1.06,                    !- Conductivity {W/m-K}
    1;                       !- Dirt Correction Factor for Solar and Visible Transmittance

!-   ===========  ALL OBJECTS IN CLASS: WINDOWMATERIAL:GAS ===========

WindowMaterial:Gas,
    1002,                    !- Name
    Air,                     !- Gas Type
    0.013;                   !- Thickness {m}

!-   ===========  ALL OBJECTS IN CLASS: CONSTRUCTION ===========

Construction,
    1002,                    !- Name
    10001,                   !- Outside Layer
    1002,                    !- Layer 2
    10001;                   !- Layer 3
```


=== Schedule:Day:Hourly
Schedule:Day:Hourlyクラスでは、時刻別のスケジュールを入力する。

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-schedules.html#scheduledayhourly[Schedule:Day:Hourlyクラスの作成方法, role="external", window="_blank"]

これらのフィールドには、1日24時間の各時間帯の値が格納される。 +
（時間フィールド1は 00:00:01 AM から 1:00:00 AM、時間フィールド2は 1:00:01 AM から 2:00:00 AM）

.Schedule:Day:Hourly　すきま風
----
Schedule:Day:Hourly,
    Day Sch 1,               !- Name
    Fraction,                !- Schedule Type Limits Name
    1,                       !- Hour 1
    1,                       !- Hour 2
    1,                       !- Hour 3
    1,                       !- Hour 4
    1,                       !- Hour 5
    1,                       !- Hour 6
    1,                       !- Hour 7
    1,                       !- Hour 8
    1,                       !- Hour 9
    1,                       !- Hour 10
    1,                       !- Hour 11
    1,                       !- Hour 12
    1,                       !- Hour 13
    1,                       !- Hour 14
    1,                       !- Hour 15
    1,                       !- Hour 16
    1,                       !- Hour 17
    1,                       !- Hour 18
    1,                       !- Hour 19
    1,                       !- Hour 20
    1,                       !- Hour 21
    1,                       !- Hour 22
    1,                       !- Hour 23
    1;                       !- Hour 24
----

.Schedule:Day:Hourly　暖房設定温度
----
Schedule:Day:Hourly,
    Zone Heating Setpoint All Days,  !- Name
    Temperature,             !- Schedule Type Limits Name
    20.,                     !- Hour 1
    20.,                     !- Hour 2
    20.,                     !- Hour 3
    20.,                     !- Hour 4
    20.,                     !- Hour 5
    20.,                     !- Hour 6
    20.,                     !- Hour 7
    20.,                     !- Hour 8
    20.,                     !- Hour 9
    20.,                     !- Hour 10
    20.,                     !- Hour 11
    20.,                     !- Hour 12
    20.,                     !- Hour 13
    20.,                     !- Hour 14
    20.,                     !- Hour 15
    20.,                     !- Hour 16
    20.,                     !- Hour 17
    20.,                     !- Hour 18
    20.,                     !- Hour 19
    20.,                     !- Hour 20
    20.,                     !- Hour 21
    20.,                     !- Hour 22
    20.,                     !- Hour 23
    20.;                     !- Hour 24
----

.Schedule:Day:Hourly　冷房設定温度
----
Schedule:Day:Hourly,
    Zone Cooling Setpoint All Days,  !- Name
    Temperature,             !- Schedule Type Limits Name
    27.,                     !- Hour 1
    27.,                     !- Hour 2
    27.,                     !- Hour 3
    27.,                     !- Hour 4
    27.,                     !- Hour 5
    27.,                     !- Hour 6
    27.,                     !- Hour 7
    27.,                     !- Hour 8
    27.,                     !- Hour 9
    27.,                     !- Hour 10
    27.,                     !- Hour 11
    27.,                     !- Hour 12
    27.,                     !- Hour 13
    27.,                     !- Hour 14
    27.,                     !- Hour 15
    27.,                     !- Hour 16
    27.,                     !- Hour 17
    27.,                     !- Hour 18
    27.,                     !- Hour 19
    27.,                     !- Hour 20
    27.,                     !- Hour 21
    27.,                     !- Hour 22
    27.,                     !- Hour 23
    27.;                     !- Hour 24
----

.Schedule:Day:Hourly　室温制御方法
----
Schedule:Day:Hourly,
    Control Type All Days,   !- Name
    Control Type,            !- Schedule Type Limits Name
    4,                       !- Hour 1
    4,                       !- Hour 2
    4,                       !- Hour 3
    4,                       !- Hour 4
    4,                       !- Hour 5
    4,                       !- Hour 6
    4,                       !- Hour 7
    4,                       !- Hour 8
    4,                       !- Hour 9
    4,                       !- Hour 10
    4,                       !- Hour 11
    4,                       !- Hour 12
    4,                       !- Hour 13
    4,                       !- Hour 14
    4,                       !- Hour 15
    4,                       !- Hour 16
    4,                       !- Hour 17
    4,                       !- Hour 18
    4,                       !- Hour 19
    4,                       !- Hour 20
    4,                       !- Hour 21
    4,                       !- Hour 22
    4,                       !- Hour 23
    4;                       !- Hour 24
----

=== Schedule:Week:Daily
Schedule:Week:Dailyクラスでは、曜日別のスケジュールを入力する。

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-schedules.html#scheduleweekdaily[Schedule:Week:Dailyクラスの作成方法, role="external", window="_blank"]

.Schedule:Week:Daily　すきま風　
----
Schedule:Week:Daily,
    Week Sch 1,              !- Name
    Day Sch 1,               !- Sunday Schedule:Day Name
    Day Sch 1,               !- Monday Schedule:Day Name
    Day Sch 1,               !- Tuesday Schedule:Day Name
    Day Sch 1,               !- Wednesday Schedule:Day Name
    Day Sch 1,               !- Thursday Schedule:Day Name
    Day Sch 1,               !- Friday Schedule:Day Name
    Day Sch 1,               !- Saturday Schedule:Day Name
    Day Sch 1,               !- Holiday Schedule:Day Name
    Day Sch 1,               !- SummerDesignDay Schedule:Day Name
    Day Sch 1,               !- WinterDesignDay Schedule:Day Name
    Day Sch 1,               !- CustomDay1 Schedule:Day Name
    Day Sch 1;               !- CustomDay2 Schedule:Day Name
----

.Schedule:Week:Daily　暖房設定温度
----
Schedule:Week:Daily,
    Zone Heating Setpoint All Weeks,  !- Name
    Zone Heating Setpoint All Days,  !- Sunday Schedule:Day Name
    Zone Heating Setpoint All Days,  !- Monday Schedule:Day Name
    Zone Heating Setpoint All Days,  !- Tuesday Schedule:Day Name
    Zone Heating Setpoint All Days,  !- Wednesday Schedule:Day Name
    Zone Heating Setpoint All Days,  !- Thursday Schedule:Day Name
    Zone Heating Setpoint All Days,  !- Friday Schedule:Day Name
    Zone Heating Setpoint All Days,  !- Saturday Schedule:Day Name
    Zone Heating Setpoint All Days,  !- Holiday Schedule:Day Name
    Zone Heating Setpoint All Days,  !- SummerDesignDay Schedule:Day Name
    Zone Heating Setpoint All Days,  !- WinterDesignDay Schedule:Day Name
    Zone Heating Setpoint All Days,  !- CustomDay1 Schedule:Day Name
    Zone Heating Setpoint All Days;  !- CustomDay2 Schedule:Day Name
----

.Schedule:Week:Daily　冷房設定温度
----
Schedule:Week:Daily,
    Zone Cooling Setpoint All Weeks,  !- Name
    Zone Cooling Setpoint All Days,  !- Sunday Schedule:Day Name
    Zone Cooling Setpoint All Days,  !- Monday Schedule:Day Name
    Zone Cooling Setpoint All Days,  !- Tuesday Schedule:Day Name
    Zone Cooling Setpoint All Days,  !- Wednesday Schedule:Day Name
    Zone Cooling Setpoint All Days,  !- Thursday Schedule:Day Name
    Zone Cooling Setpoint All Days,  !- Friday Schedule:Day Name
    Zone Cooling Setpoint All Days,  !- Saturday Schedule:Day Name
    Zone Cooling Setpoint All Days,  !- Holiday Schedule:Day Name
    Zone Cooling Setpoint All Days,  !- SummerDesignDay Schedule:Day Name
    Zone Cooling Setpoint All Days,  !- WinterDesignDay Schedule:Day Name
    Zone Cooling Setpoint All Days,  !- CustomDay1 Schedule:Day Name
    Zone Cooling Setpoint All Days;  !- CustomDay2 Schedule:Day Name
----

.Schedule:Week:Daily　室温制御方法
----
Schedule:Week:Daily,
    Control Type All Weeks,  !- Name
    Control Type All Days,   !- Sunday Schedule:Day Name
    Control Type All Days,   !- Monday Schedule:Day Name
    Control Type All Days,   !- Tuesday Schedule:Day Name
    Control Type All Days,   !- Wednesday Schedule:Day Name
    Control Type All Days,   !- Thursday Schedule:Day Name
    Control Type All Days,   !- Friday Schedule:Day Name
    Control Type All Days,   !- Saturday Schedule:Day Name
    Control Type All Days,   !- Holiday Schedule:Day Name
    Control Type All Days,   !- SummerDesignDay Schedule:Day Name
    Control Type All Days,   !- WinterDesignDay Schedule:Day Name
    Control Type All Days,   !- CustomDay1 Schedule:Day Name
    Control Type All Days;   !- CustomDay2 Schedule:Day Name
----


=== Schedule:Year
Schedule:Yearクラスでは、年間スケジュールを入力する。

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-schedules.html#scheduleyear[Schedule:Yearクラスの作成方法, role="external", window="_blank"]

.Schedule:Year　すきま風　
----
Schedule:Year,
    Sch 1,                   !- Name
    Fraction,                !- Schedule Type Limits Name
    Week Sch 1,              !- Schedule:Week Name 1
    1,                       !- Start Month 1
    1,                       !- Start Day 1
    12,                      !- End Month 1
    31;                      !- End Day 1
----

.Schedule:Year　暖房設定温度
----
Schedule:Year,
    Heating Setpoints,       !- Name
    Temperature,             !- Schedule Type Limits Name
    Zone Heating Setpoint All Weeks,  !- Schedule:Week Name 1
    1,                       !- Start Month 1
    1,                       !- Start Day 1
    12,                      !- End Month 1
    31;                      !- End Day 1
----

.Schedule:Year　冷房設定温度
----
Schedule:Year,
    Cooling Setpoints,       !- Name
    Temperature,             !- Schedule Type Limits Name
    Zone Cooling Setpoint All Weeks,  !- Schedule:Week Name 1
    1,                       !- Start Month 1
    1,                       !- Start Day 1
    12,                      !- End Month 1
    31;                      !- End Day 1
----

.Schedule:Year　室温制御方法
----
Schedule:Year,
    Zone Control Type Sched, !- Name
    Control Type,            !- Schedule Type Limits Name
    Control Type All Weeks,  !- Schedule:Week Name 1
    1,                       !- Start Month 1
    1,                       !- Start Day 1
    12,                      !- End Month 1
    31;                      !- End Day 1
----


=== ZoneInfiltration:DesignFlowRate
ZoneInfiltration:DesignFlowRateクラスでは、すきま風に関する設定を入力する。

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-airflow.html#zoneinfiltrationdesignflowrate[ZoneInfiltration:DesignFlowRateクラスの作成方法, role="external", window="_blank"]

.すきま風　
----
ZoneInfiltration:DesignFlowRate,
    Infil_1,                 !- Name
    Zone1,                   !- Zone or ZoneList Name
    Sch 1,                   !- Schedule Name
    Flow/Zone,               !- Design Flow Rate Calculation Method
    0.018,                   !- Design Flow Rate {m3/s}
    ,                        !- Flow per Zone Floor Area {m3/s-m2}
    ,                        !- Flow per Exterior Surface Area {m3/s-m2}
    ,                        !- Air Changes per Hour {1/hr}
    1,                       !- Constant Term Coefficient
    0,                       !- Temperature Term Coefficient
    0,                       !- Velocity Term Coefficient
    0;                       !- Velocity Squared Term Coefficient
----

=== OtherEquipment
OtherEquipmentクラスでは、内部発熱に関する設定を入力する。

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-internal-gains-people-lights-other.html#otherequipment[OtherEquipmentクラスの作成方法, role="external", window="_blank"]

.OtherEquipment
----
OtherEquipment,
    Euip 1,                  !- Name
    None,                    !- Fuel Type
    Zone1,                   !- Zone or ZoneList Name
    Sch 1,                   !- Schedule Name
    EquipmentLevel,          !- Design Level Calculation Method
    200,                     !- Design Level {W}
    ,                        !- Power per Zone Floor Area {W/m2}
    ,                        !- Power per Person {W/person}
    0,                       !- Fraction Latent
    0.6,                     !- Fraction Radiant
    0,                       !- Fraction Lost
    ,                        !- Carbon Dioxide Generation Rate {m3/s-W}
    General;                 !- End-Use Subcategory
----


=== ZoneControl:Thermostat
ZoneControl:Thermostatクラスでは、ゾーンを指定された温度に制御する方法について入力する。

ZoneControl:Thermostatは、制御スケジュールと1つ以上の制御オブジェクトを参照し、これらは1つ以上の設定値スケジュールを参照する。

.ZoneControl:Thermostat　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-controls-thermostats.html#zonecontrolthermostat[<bigladder>, role="external", window="_blank"]
----
ZoneControl:Thermostat,
    Zone 1 Thermostat,                !- Name
    Zone1,                            !- Zone or ZoneList Name
    Zone Control Type Sched,          !- Control Type Schedule Name
    ThermostatSetpoint:DualSetpoint,  !- Control 1 Object Type
    Heating Cooling Setpoints;        !- Control 1 Name
----

==== Name
任意の名称を入力する。

==== Zone or ZoneList Name
対象とするゾーンもしくはゾーンリストの名称を入力する。

==== Control Type Schedule Name
別途定義した制御スケジュール名を入力する。 制御スケジュールには、シミュレーション中に使用される制御タイプ番号を指定する。有効な制御タイプ番号は次のとおりである。

* 0 - 無制御（指定なし、またはデフォルト）
* 1 - 単一の加熱セットポイント
* 2 - 単一の冷房設定値
* 3 - 暖房/冷房の単一設定値
* 4 - 不感帯のある室温設定値（暖房と冷房）

例えば、ZoneControl:Thermostatから参照されるスケジュールが、特定の時間帯に制御タイプが4である場合、その時間帯に「不感帯のある室温設定値（暖房と冷房）」制御が使用されることを示している。

==== Control 1 Object Type
コントロールタイプの種類を次の4つの選択肢から選択する。

* ThermostatSetpoint:SingleHeating　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-controls-thermostats.html#thermostatsetpointsingleheating[<bigladder>, role="external", window="_blank"]
* ThermostatSetpoint:SingleCooling　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-controls-thermostats.html#thermostatsetpointsinglecooling[<bigladder>, role="external", window="_blank"]
* ThermostatSetpoint:SingleHeatingOrCooling　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-controls-thermostats.html#thermostatsetpointsingleheatingorcooling[<bigladder>, role="external", window="_blank"]
* ThermostatSetpoint:DualSetpoint　https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-controls-thermostats.html#thermostatsetpointdualsetpoint[<bigladder>, role="external", window="_blank"]

Case 600 では　ThermostatSetpoint:DualSetpoint　を選択する。

==== Control 1 Name
別途定義したコントロールタイプの名称を入力する。


=== ThermostatSetpoint:DualSetpoint

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-controls-thermostats.html#thermostatsetpointdualsetpoint[ThermostatSetpoint:DualSetpointの作成方法, role="external", window="_blank"]

.ThermostatSetpoint:DualSetpoint　[<bigladder>, role="external", window="_blank"]
----
ThermostatSetpoint:DualSetpoint,
    Heating Cooling Setpoints,  !- Name
    Heating Setpoints,          !- Heating Setpoint Temperature Schedule Name
    Cooling Setpoints;          !- Cooling Setpoint Temperature Schedule Name
----

==== Name
任意の名称を入力する。

==== Heating Setpoint Temperature Schedule Name
暖房運転時設定温度のスケジュール名称を入力する。

==== Cooling Setpoint Temperature Schedule Name
冷房運転時設定温度のスケジュール名称を入力する。


=== ZoneHVAC:IdealLoadsAirSystem

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-forced-air-units.html#zonehvacidealloadsairsystem[ZoneHVAC:IdealLoadsAirSystemの作成方法, role="external", window="_blank"]

最もシンプルなゾーン装置は、ZoneHVAC:IdealLoadsAirSystemコンポーネントです。
ZoneHVAC:IdealLoadsAirSystemは、ユーザーが完全な空調システムをモデル化することなく、建物の性能を検討したい場合に使用されます。
このような場合、通常は ZoneHVAC:IdealLoadsAirSystem が唯一の空調コンポーネントとなります。
理想的なシステムに必要なのは、ゾーン制御、ゾーン機器構成、および理想的な負荷システムコンポーネントだけです。
リターン・プレナムの使用はオプションで、AirloopHVAC:ReturnPlenumオブジェクトを使用する必要があります。

このコンポーネントは、無限または有限の冷暖房能力で動作させることができます。
無限容量または有限容量のいずれのモードでも、ユーザーは冷暖房のオン/オフスケジュールや外気の制御を指定できます。
また、オプションで、除湿、加湿、エコノマイザー、熱回収の制御も可能です。
このコンポーネントは、同じゾーンを担当する他のHVAC機器と組み合わせて使用することができます。

このコンポーネントは、ゾーンの排気条件（プレナムが取り付けられている場合はプレナムの出口条件）にある空気と指定された量の外気を混合し、
熱と湿気を100％の効率で加えたり取り除いたりして、指定された条件の給気流を作り出す理想的なユニットと考えることができる。
供給空気の調整に必要なエネルギーは計測され、DistrictHeatingおよびDistrictCoolingとして報告される。


注意事項： +
ZoneHVAC:IdealLoadsAirSystemでは、ゾーンから空気を抽出するために、ゾーンリターンノードまたはオプションのゾーンエキゾーストノードを使用します。AirloopHVAC:ReturnPlenumを使用する場合、理想負荷システムの入口はプレナム出口空気ノードに接続され、理想負荷システムの出口はゾーン入口ノードに接続される。
ゾーン排気ノードとプレナム入口空気ノードの間に接続されるノード名は、ZoneHVAC:EquipmentConnectionsおよびAirloopHVAC:ReturnPlenumオブジェクト内で一致しなければならない。
HVACコンポーネントがサービスを提供するすべてのゾーンには、たとえこのノードが何にも接続されていなくても、戻り空気ノードが必要である。
複数の理想的な負荷空気システムが同じAirloopHVAC:ReturnPlenumに接続されている場合、
理想的な負荷空気システムの1つがZoneHVAC:ReturnPlenum出口空気ノードに接続され、
同じリターンプレナムに接続されている残りの理想的な負荷空気システムがZoneHVAC:ReturnPlenum誘導空気出口ノードに接続されます。

ZoneHVAC:IdealLoadsAirSystemは、バージョン7.0（2011年10月）で大幅に拡張されました。
このアップグレードの一環として、供給空気流の含水率が変化すると、潜熱冷却（除湿）または潜熱加熱（加湿）の負荷が発生し、
DistrictCoolingおよびDistrictHeatingのエネルギー消費として計測されます。
バージョン7.0以前では、理想負荷システムが暖房モードの場合、顕熱のエネルギーのみが計測されていた。
この結果、特に「Humidification Control Type」の「ConstantSupplyHumidityRatio」オプションを使用している場合、
報告されるエネルギー使用量が以前のバージョンと比べて大幅に変化します。

バージョン7.0に移行した古いidfファイルは、除湿および加湿制御の両方にConstantSupplyHumidityRatioオプションを使用するように自動的に設定されますが、
これは本システムの旧バージョンで使用されていた制御と同等であるためです。
ただし、ユーザーはすべての湿度制御オプションを確認し、シミュレーションの目的に応じて最適なものを選択する必要があります。


.ZoneHVAC:IdealLoadsAirSystem
----
ZoneHVAC:IdealLoadsAirSystem,
    Zone1Air,                !- Name
    ,                        !- Availability Schedule Name
    NODE_1,                  !- Zone Supply Air Node Name
    ,                        !- Zone Exhaust Air Node Name
    ,                        !- System Inlet Air Node Name
    50,                      !- Maximum Heating Supply Air Temperature {C}
    13,                      !- Minimum Cooling Supply Air Temperature {C}
    0.010,                   !- Maximum Heating Supply Air Humidity Ratio {kgWater/kgDryAir}
    0.010,                   !- Minimum Cooling Supply Air Humidity Ratio {kgWater/kgDryAir}
    ,                        !- Heating Limit
    ,                        !- Maximum Heating Air Flow Rate {m3/s}
    ,                        !- Maximum Sensible Heating Capacity {W}
    ,                        !- Cooling Limit
    ,                        !- Maximum Cooling Air Flow Rate {m3/s}
    ,                        !- Maximum Total Cooling Capacity {W}
    ,                        !- Heating Availability Schedule Name
    ,                        !- Cooling Availability Schedule Name
    ConstantSupplyHumidityRatio,  !- Dehumidification Control Type
    ,                        !- Cooling Sensible Heat Ratio {dimensionless}
    ConstantSupplyHumidityRatio,  !- Humidification Control Type
    ,                        !- Design Specification Outdoor Air Object Name
    ,                        !- Outdoor Air Inlet Node Name
    ,                        !- Demand Controlled Ventilation Type
    ,                        !- Outdoor Air Economizer Type
    ,                        !- Heat Recovery Type
    ,                        !- Sensible Heat Recovery Effectiveness {dimensionless}
    ;                        !- Latent Heat Recovery Effectiveness {dimensionless}
----

==== Name
任意の名称を入力する。この名称は　ZoneHVAC:EquipmentList から参照される。

==== Zone Supply Air Node Name
給気ノードの名称を入力する。これは、本コンポーネントがサービスを提供するゾーンのゾーン給気ノードの1つと同じでなければならない。

==== Maximum Heating Supply Air Temperature {^o^C}
給気温度の最大値を入力する。

==== Minimum Cooling Supply Air Temperature {^o^C}
給気温度の最小値を入力する。

==== Maximum Heating Supply Air Humidity Ratio {kgWater/kgDryAir}
給気湿度の最大値を入力する。

==== Minimum Cooling Supply Air Humidity Ratio {kgWater/kgDryAir}
給気湿度の最小値を入力する。選択肢は以下の4つである。

==== Dehumidification Control Type
除湿の制御方式を選択する。選択肢は以下の4つである。

* ConstantSensibleHeatRatio
* Humidistat
* None
* ConstantSupplyHumidityRatio

==== Humidification Control Type
加湿の制御方式を選択する。選択肢は以下の3つである。

* None
* Humidistat
* ConstantSupplyHumidityRatio


=== ZoneHVAC:EquipmentList

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-equipment.html#zonehvacequipmentlist[ZoneHVAC:EquipmentListの作成方法, role="external", window="_blank"]

このクラスには、ゾーンにサービスを提供する全てのHVAC機器を登録し、それぞれの起動の優先順位を定義する。
リストの各項目には、4つのフィールドが関連付けられている。
Object TypeとNameは、特定の機器オブジェクトを識別する。
Cooling SequenceとHeat or No-Load Sequenceは、複数のタイプのHVAC機器があるゾーンのシミュレーションの順番を指定する。

.ZoneHVAC:EquipmentList
----
ZoneHVAC:EquipmentList,
    Zone1Equipment,          !- Name
    SequentialLoad,          !- Load Distribution Scheme
    ZoneHVAC:IdealLoadsAirSystem,  !- Zone Equipment 1 Object Type
    Zone1Air,                !- Zone Equipment 1 Name
    1,                       !- Zone Equipment 1 Cooling Sequence
    1,                       !- Zone Equipment 1 Heating or No-Load Sequence
    ,                        !- Zone Equipment 1 Sequential Cooling Fraction Schedule Name
    ;                        !- Zone Equipment 1 Sequential Heating Fraction Schedule Name
----

==== Zone Equipment 1 Object Type
ゾーンに設置されたHVAC機器の名称（ZoneHVAC:IdealLoadsAirSystem）を指定する。

==== Zone Equipment 1 Cooling Sequence
ゾーンサーモスタットが冷房を要求する際の、ゾーン機器のシミュレーション順序を指定する。

==== Zone Equipment 1 Heating or No-Load Sequence
ゾーンサーモスタットが暖房を要求した場合、もしくは負荷がない場合のゾーン機器のシミュレーション順序を指定する。


=== NodeList

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-node-branch-management.html#nodelist[NodeListの作成方法, role="external", window="_blank"]

.NodeList　[<bigladder>, role="external", window="_blank"]
----
NodeList,
    Zone1Inlets,             !- Name
    NODE_1;                  !- Node 1 Name
----

=== ZoneHVAC:EquipmentConnections

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-zone-equipment.html#zonehvacequipmentconnections[ZoneHVAC:EquipmentConnectionsの作成方法, role="external", window="_blank"]

ZoneHVAC:EquipmentConnectionsステートメントは、HVACの観点から各サーマルゾーンの詳細を定義する。
他のステートメントと同様に、このクラスの最初の2つの項目は、キーワードと識別名で、ゾーンをその幾何学的入力、内部利得など、入力のHVACセクションの他のステートメントにリンクする。
次の3つの項目は、以下に詳述するリスト（機器、吸気ノード、排気ノード）の名前である。
ゾーンからの排気ノードがない場合、このフィールドは空白になることに注意してください。
また、エアインレットノードがない場合、このフィールドは空白になりる。
最後に、ゾーン-HVACの記述を完成させるために、2つのノード名が必要である。
1つ目のノードは、空気のヒートバランスを実行するゾーンのメイン空気ノードである。
もう1つのノードは、ゾーンからの戻り空気の経路である。

.ZoneHVAC:EquipmentConnections
----
ZoneHVAC:EquipmentConnections,
    Zone1,                   !- Zone Name
    Zone1Equipment,          !- Zone Conditioning Equipment List Name
    Zone1Inlets,             !- Zone Air Inlet Node or NodeList Name
    ,                        !- Zone Air Exhaust Node or NodeList Name
    NODE_2,                  !- Zone Air Node Name
    NODE_3;                  !- Zone Return Air Node or NodeList Name
----

==== Zone Name（required）
ゾーン名称を入力する。

==== Zone Conditioning Equipment List Name（required）
「ZoneHVAC:EquipmentList」で定義した名称を入力する。

==== Zone Air Inlet Node or NodeList Name
給気に関するノード名称を入力する。

==== Zone Air Exhaust Node or NodeList Name
排気に関するノード名称を入力する。

==== Zone Air Node Name（required）
ゾーン空気に関するノード名称を入力する。

==== Zone Return Air Node or NodeList Name
還気に関するノード名称を入力する。


=== Output:Variable

==== Surface Outside Face Incident Solar Radiation Rate per Area

参考： https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-thermal-zone-description-geometry.html#surface-outside-face-incident-solar-radiation-rate-per-area-wm2[<bigladder>, role="external", window="_blank"]
